### ISSUE TITLE
Command Feature Request - "bench"

### ISSUE THREAD

**Issue by CMCDragonkai** [bobthecow/psysh#102]
I find myself sometimes wanting to know how long a snippet of code takes to execute, in order to compare different snippets quickly.

Would be great if there was a `bench begin` command. For this to work, it might need to start a "subbuffer" which accumulates any code", and then `bench execute`, which might then run the code and return some data.

**Comment by bobthecow** [comment]
See #138 for a WIP implementation of this :)

**Comment by jacobbednarz** [comment]
@CMCDragonkai in the meantime, you could try [jacobbednarz/php-bench](https://github.com/jacobbednarz/php-bench). That allows you to profile multiple functions or snippets against each other.

Would also love to see this in a REPL though.

**Comment by bobthecow** [comment]
Oh! This exists now, as the `timeit` command 😄
