### ISSUE TITLE
symfony 2.6 composer compatibility

### ISSUE THREAD

**Issue by ghost** [bobthecow/psysh#137]
Currently the dependency on symfony/console is declare as `"symfony/console": "~2.3.10|~2.4.2|~2.5"` which make the installation of psysh complex in a symfony 2.6 app. Including ~2.6 would probably work apart if there was some incompatibility change in the console that I'm not aware of.

**Comment by bobthecow** [comment]
`~2.5` means `2.*, >=3.5.0`, so that should support 2.6 just fine.

**Comment by bobthecow** [comment]
`2.*, >=2.5.0` rather :)
