### ISSUE TITLE
use statement of startup script ignored

### ISSUE THREAD

**Issue by flip111** [bobthecow/psysh#139]
script:
```php
<?php
require_once __DIR__.'/../vendor/autoload.php';
require_once __DIR__.'/../database.php';

use RedBean_Facade as R;

R::debug(true);
R::freeze(false);
```

command: `psysh bin\r.php`
code: `$test = R::findAll('user')`
error: `PHP Fatal error:  Class 'R' not found`

**Comment by bobthecow** [comment]
It's likely an issue with your autoloader, and it's probably not finding `RedBean_Facade`. You can test this by replacing `R::` with the full class name.

This works for me:

```php
<?php
use StdClass as S;
$s = new S;
```

```
$ psysh test.php
Psy Shell v0.3.2 (PHP 5.6.4 — cli) by Justin Hileman
>>> ls -al

Variables:
  $s   <stdClass #0000000034a87a0c000000011e732eb5>
  $_   null
```
