### ISSUE TITLE
Symfony's TableHelper is deprecated

### ISSUE THREAD

**Issue by antonioribeiro** [bobthecow/psysh#156]
Got this message on latest Symfony:

    exception 'ErrorException' with message '"Symfony\Component\Console\Helper\TableHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\Table" instead.' in /var/www/tests/l5/vendor/symfony/console/Symfony/Component/Console/Helper/HelperSet.php:86

And you are using it here:

    vendor/psy/psysh/src/Psy/Command/HelpCommand.php:use Symfony\Component\Console\Helper\TableHelper;
    vendor/psy/psysh/src/Psy/Command/ListCommand.php:use Symfony\Component\Console\Helper\TableHelper;

**Comment by bobthecow** [comment]
But we're not using 3.0, yet, so there's absolutely no reason for Symfony to be complaining so loud :)

What version of PsySH and Symfony Console are you running?

**Comment by antonioribeiro** [comment]
The problem is not really on 3.0, it was removed from it, but in 2.7.*. But it all started with me trying to use Laravel dev-master (5.1), wich requires symfony 2.7 :)

The whole problem is in getHelperSet(), which unconditionally raises that exception. TableHelper itself doesn't if you instantiate it with false;

**Comment by bobthecow** [comment]
This is a backwards compatibility break. Please take it up with Symfony :)

**Comment by antonioribeiro** [comment]
I did: https://github.com/symfony/symfony/issues/13732.

**Comment by bobthecow** [comment]
Well that wasn't very helpful.

I'll try to get a better fix in before 2.7 ships. I'm also happy to accept pull requests if you need it sooner :)

**Comment by antonioribeiro** [comment]
Nice, thank you! :)

**Comment by bobthecow** [comment]
No problem!
