### ISSUE TITLE
Mention required dependencies

### ISSUE THREAD

**Issue by theofidry** [bobthecow/psysh#160]
As I installed psysh on a fresh Ubuntu install, I've got the error `sqlite pdo driver not found` when I tried to get the doc for the function `var_dump` (after adding the doc for native PHP function). This issue is caused by the missing package `php5-sqlite`. It's not that of an issue, but I though that it may been useful to specify it somewhere in the doc.

**Comment by bobthecow** [comment]
It's not a required dependency, it's a highly suggested dependency :)

I've added it to `composer.json` as well, so Composer will let you know that you should install it if it's not already installed.

The trouble with adding it to the documentation is that (1) nobody reads documentation, and (2) your specific solution only works for your specific linux distro. There are dozens of packages or compile flags or `.dll` or `.so` files, or whatever other ways that everyone else should get that extension. In fact, it comes pre-compiled in PHP for many (most?) users. The best PsySH can really do is tell you the package is missing.

**Comment by johnbendi** [comment]
I installed via compose and still get this:
`SQLite PDO driver not found`
