### ISSUE TITLE
Use case with Symfony2

### ISSUE THREAD

**Issue by theofidry** [bobthecow/psysh#162]
I installed psysh as a composer dev dependency and they put `eval(\Psy\sh());` in my controller where I wanted a breakpoint. However it just does a loop without starting the psysh shell.

I tried that on Ubuntu with phpStorm.

**Comment by bobthecow** [comment]
For now, you need to be running your application in the command line PHP server for the breakpoint to work.

```bash
php -S localhost:3000 index.php # or whatever your front controller's name is...
```

See #121 for conversation around making it work without the command line server.

**Comment by theofidry** [comment]
Hmm actually I'm using the Symfony server (`php app/console server:start`) which uses the build-in PHP server.

**Comment by bobthecow** [comment]
Oh, then maybe I misunderstood what you were asking. What happens when you hit that controller with `eval(\Psy\sh())` in it?

**Comment by theofidry** [comment]
I wait for ages and an error is returned once the timeout is reached.

**Comment by theofidry** [comment]
Maybe it's my require that is not good. I cannot check at the moment so I'll tell you that when I can get my hand on it again.

**Comment by bobthecow** [comment]
I'll set up a Symfony app and see if I can reproduce. What Symfony version are you running? Can you paste me the output of `php -v`, `psysh -v` and `php -i | grep -i readline`?

**Comment by theofidry** [comment]
I have no access to my machine right now. But if I remember right it's PHP 5.6, Symfony 2.7 and for psysh it's a fresh install so I guess the latest version.

**Comment by theofidry** [comment]
Found something? Still can't get it working :(

**Comment by theofidry** [comment]
I properly retested on Symfony2. The include works fine, however impossible to make the `eval(\Psy\sh());` no matter how I run the server, via `php app/console server:run` or `php app/console server:start`.

**Comment by theofidry** [comment]
I've found a bundle and forked it to add some things: [theofidry/PsyshBundle](https://github.com/theofidry/PsyshBundle). Now I can properly start a PsySH shell and use Symfony component in it. But the use case of the breakpoint (using the `eval(\Psy\sh());`) has yet to work with the Symfony build-in server. At this point, I do not know if it comes from PsySH or the wrapper used by Sensio for the Symfony build-in server. Do you have any idea?

**Comment by jrobeson** [comment]
according to http://stackoverflow.com/questions/9538435/symfony2-with-php-5-4-built-in-server#9555588 you should be able to run it directly by passing the path to the router file. 

```bash
cd /path/to/symfony/web
php -S ../vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php
```

if that doesn't work due to pathing issues, try copying the router_dev.php to /web

**Comment by theofidry** [comment]
It works! Thanks @jrobeson and sorry for the lat answer :)

**Comment by titolendable** [comment]
thanks @jrobeson that did the trick, it works. I wonder why it doesn't work with the symfony server:run command. When I execute the following command, it get stuck as @theofidry described: 

$php app/console server:run 0.0.0.0:8080 --router=vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php

**Comment by theofidry** [comment]
@titolendable you might want to take a look at [PsyshBundle](https://github.com/theofidry/PsyshBundle) for a Symfony integration ;)

**Comment by titolendable** [comment]
@theofidry I am using it, maybe I am missing something, but I do not think the bundle provides a way to start the server, only to fire the shel with the symfony kernel booted. I run $php app/console psysh, but what I would like is to make it work with http requests. Something I accomplished using @jrobeson's suggestion but not with the native symfony server:run command. Am I doing something wrong?

**Comment by theofidry** [comment]
I don't know, at the time I've written the doc it was working (cf. [PsySH with breakpoints](https://github.com/theofidry/PsyshBundle/blob/master/src/Resources/doc/breakpoint.md)). I haven't tested it since then as for breakpoints I find more convenient to use XDebug with an IDE like phpStorm. Would be awesome if the interactive shell provided with phpStorm while doing step by step debugging would be PsySH though.
