### ISSUE TITLE
Can't exit PsySH by calling 'exit' on PHP 5.3.10

### ISSUE THREAD

**Issue by mrdziuban** [bobthecow/psysh#164]
I'm running on PHP 5.3.10. When PsySH loads, the message is `Psy Shell v0.4.0 (PHP 5.3.10-1ubuntu3.15 — cli) by Justin Hileman`

When trying to exit by issuing the command `exit`, I get the error:

`PHP Fatal error:  Call to undefined function Psy\TabCompletion\readline_callback_handler_remove() in /home/ubuntu/psysh/psysh/src/Psy/TabCompletion/AutoCompleter.php on line 94`

Readline is enabled as I'm able to navigate my command history with the up/down arrow keys, and checking if `function_exists('readline_callback_handler_remove')` return false, but `function_exists('readline_read_history')` returns true. Anything I can do to get this working?

EDIT: I'm using the develop branch as it contains another fix (debug_backtrace) for PHP 5.3.

**Comment by bobthecow** [comment]
Yeah. We probably need more test coverage for this sort of thing.

Can you tell me the output of `php -i | grep -i readline`?

**Comment by mrdziuban** [comment]
It just returns one line that says `readline`

**Comment by bobthecow** [comment]
Hmm. Check the output around it? `php -i | grep -i -C10 readline`

**Comment by mrdziuban** [comment]
The output around it is:

```
Linked Version => 1.2.3.4

Directive => Local Value => Master Value
zlib.output_compression => Off => Off
zlib.output_compression_level => -1 => -1
zlib.output_handler => no value => no value

Additional Modules

Module Name
readline
sysvsem
sysvshm

Environment

Variable => Value
TERM => xterm-256color
SHELL => /bin/bash
XDG_SESSION_COOKIE => XXXXXX
SSH_CLIENT => XX.XX.XXX.XX XXXXX XX
```

This is from `/etc/php5/cli/php.ini`. Readline doesn't appear under 'Additional Modules' when checking `/etc/php5/apache2/php.ini`.

**Comment by bobthecow** [comment]
That's strange. What's the output from `function_exists('readline_list_history')`?

**Comment by mrdziuban** [comment]
That returns false

**Comment by bobthecow** [comment]
Okay, I think I know what's going on. One more: `readline_info()`

**Comment by mrdziuban** [comment]
```
[
    "line_buffer"     => "readline_info()\n",
    "point"           => 0,
    "end"             => 0,
    "library_version" => "EditLine wrapper",
    "readline_name"   => ""
]
```

**Comment by bobthecow** [comment]
Bingo!

When PHP decided to switch over to libedit instead of GNU readline by default, they did a really crap job. They only implemented part of the API. It's still not all the way implemented.

PsySH works around the incomplete implementation where we can ([see the Libedit readline wrapper](https://github.com/bobthecow/psysh/blob/master/src/Psy/Readline/Libedit.php)).

But apparently they used to support even less of the API when they first made the switch. Ugh. I guess we'll add a check for that function's existence before calling it.

**Comment by bobthecow** [comment]
Okay. There's a fix in the develop branch. Give it a shot and let me know if you have any other issues.

**Comment by mrdziuban** [comment]
That works perfectly, thanks for the quick fix and for being so responsive!

**Comment by bobthecow** [comment]
:+1:

No problem! I'll try to get a release out today so everyone else benefits. Let me know if you run into any other 5.3 issues.

**Comment by mrdziuban** [comment]
Awesome, I do prefer using the compiled phar, so let me know when the release goes live.

**Comment by bobthecow** [comment]
Done. Download v0.4.1 from psysh.org for great justice!

**Comment by mrdziuban** [comment]
Perfect, thanks again!
