### ISSUE TITLE
Presenters vs dump (and VarDumper)

### ISSUE THREAD

**Issue by barryvdh** [bobthecow/psysh#165]
As I understand it, Presenters are a way to present an object in a simple way, right? Which is pretty cool because if (in Laravel for example) just do `$app = app()` the shell always displays the object. And that would be pretty large without the Presenter.

But when I run `dump $app`, shouldn't that give me more information? Eg, private properties, methods etc etc.

A cool way to do this would be the new Symfony VarDumper component: http://symfony.com/doc/current/components/var_dumper/introduction.html (and http://symfony.com/doc/current/components/var_dumper/advanced.html for some more customisation).

It also already has a CLI Dumper but could also dump to plain text. And doesn't have any external dependancies.

This is a better alternative then var_dump(), because it handles recursion/depth better, and is a bit prettier. You can try this in Laravel/Symfony with just calling `dump($var)`, but I would think that the dump command should be more like that. 

(And you can always just use the presenter by just calling the variable, without `dump`)

**Comment by Markcial** [comment]
have you tried to do a `ls -la $object`?

**Comment by barryvdh** [comment]
Okay did not know that. That's useful, but not quite the same.

**Comment by Markcial** [comment]
why? it shows public private or protected properties or mehods as constatns.

![screenshot from 2015-02-26 12 04 45](https://cloud.githubusercontent.com/assets/208523/6390803/c0a3a0f2-bdaf-11e4-93e0-08fd6786c11e.png)

**Comment by barryvdh** [comment]
Yes but it doesn't give the current state and nested properties etc, right?
The `dump` method is just a different thing then the `list` command.

**Comment by barryvdh** [comment]
I think it's probably 2 things

 - The dump command uses the Presenters, so you can't use a Presenter to give a simplified version of an object and still dump all information.
 - Instead of using the default Object dumper, the VarDumper could be used for deeper/more robust information.

**Comment by Markcial** [comment]
I sincerely don't see where is the trouble, the list command would fit for all of your needs, if you think that the feature needs more completion you are free to collaborate with a PR, but IMHO the list command is enough. Maybe the repo owner is able to help you better with your issue.

**Comment by barryvdh** [comment]
Well I'm okay with submitting a PR myself but would like some feedback first.

**Comment by bobthecow** [comment]
Check `dump -h` :)

 * `dump -a $object` dumps private and protected properties.
 * `dump --depth 100 $object` dumps deeper than the default 10. Be careful with this, as it doesn't do recursion checking :P

**Comment by bobthecow** [comment]
Presenters and VarDumper are made to do the exact same thing. Presenters just do it in a prettier way ;)

**Comment by barryvdh** [comment]
Okay maybe it's just me or the Laravel specific presenters, but for example, when I create a Laravel Model, the output from `dump -a` is the same as just returning the object.

`ls -la` does help, but doesn't nest. See the differences:

    >>> $user = new App\User(['name' => 'Barry vd. Heuvel']);
    => <App\User #00000000703978830000000066114da2> {
           name: "Barry vd. Heuvel"
       }
    >>> dump --all $user
    <App\User #00000000703978830000000066114da2> {
        name: "Barry vd. Heuvel"
    }
    >>> dump -a --depth=10 $user
    <App\User #00000000703978830000000066114da2> {
        name: "Barry vd. Heuvel"
    }
    >>> dump($user)
    App\User {#796
      #table: "users"
      #fillable: array:3 [
        0 => "name"
        1 => "email"
        2 => "password"
      ]
      #hidden: array:2 [
        0 => "password"
        1 => "remember_token"
      ]
      #connection: null
      #primaryKey: "id"
      #perPage: 15
      +incrementing: true
      +timestamps: true
      #attributes: array:1 [
        "name" => "Barry vd. Heuvel"
      ]
      #original: []
      #relations: []
      #visible: []
      #appends: []
      #guarded: array:1 [
        0 => "*"
      ]
      #dates: []
      #casts: []
      #touches: []
      #observables: []
      #with: []
      #morphClass: null
      +exists: false
    }
    => null

    >>> ls -la $user

    Class Constants:
      CREATED_AT   "created_at"
      UPDATED_AT   "updated_at"

    Class Properties:
      $appends           []
      $attributes        Array(1)
      $booted            Array(1)
      $casts             []
      $connection        null
      $dates             []
      $dispatcher        <Illuminate\Events\Dispatcher #000000001f7f8607000000007f889a29>
      $exists            false
      $fillable          Array(3)
      $globalScopes      []
      $guarded           Array(1)
      $hidden            Array(2)
      $incrementing      true
      $manyMethods       Array(3)
      $morphClass        null
      $mutatorCache      Array(1)
      $observables       []
      $original          []
      $perPage           15
      $primaryKey        "id"
      $relations         []
      $resolver          <Illuminate\Database\DatabaseManager #000000001f7f869e000000007f889a29>
      $snakeAttributes   true
      $table             "users"
      $timestamps        true
      $touches           []
      $unguarded         false
      $visible           []
      $with              []

For example, the `hidden` array isn't visible in the dump. I'm guessing that that would be expected with the `dump --all` option.

**Comment by bobthecow** [comment]
It looks like you're using the dev version of Laravel, right?

The Eloquent Model presenter only shows attributes (not all the wiring that's there for making it an active record style ORM). And it only shows attributes with values, IIRC. So if you have a password set, it'll show you the password when you dump with `-a`. This is on purpose :)

See the screenshots in this comment: https://github.com/laravel/framework/pull/7208#issuecomment-75386250

**Comment by bobthecow** [comment]
A Presenter should not show everything that's in `var_dump`... there's always `var_dump` if you need that. A Presenter should show what you would most likely want to see when you try to dump. It specifically hides empty and uninteresting things.

It's entirely possible that an Eloquent Model presenter should be presenting more than it currently does. In fact, it's probably quite likely. But it definitely shouldn't be showing everything from `dump()` or `var_dump()`

**Comment by barryvdh** [comment]
Okay I guess I was just confused by the terminology then, between `var_dump($a)`, `dump $a`, `ls -la $a` and just `$a`.

Will just use `dump($a)` when I need it then ;) Thanks anyways

**Comment by bobthecow** [comment]
I know almost nothing about how models are actually used in Laravel IRL, so if there's something that *should* be in the presenter, I'd love to know :)
