### ISSUE TITLE
windows couple of minor things

### ISSUE THREAD

**Issue by isimmons** [bobthecow/psysh#17]
.psysh directory created in C:\ . Don't know is this something you can change for windows to use the %HOMEPATH% variable?

Also, I can barely read the blue text against a semi transparent over black background in conemu. Any chance of making it brighter or is there a way for me to do that?

Thanks

**Comment by sailorsteve** [comment]
I had the same issue as @isimmons of being unable to read the blue text on a dark background on Windows. I am using Git Bash inside of Console2. For those who may be experiencing the same thing, Console2 makes it easy to map the console colors. Go to Edit -> Settings..., select Console and remap blue to something lighter. All is now good!
