### ISSUE TITLE
Tab completion and history do not work when readline is not installed

### ISSUE THREAD

**Issue by avindra** [bobthecow/psysh#177]
Tab completion and command history are not working when readline is missing.

I didn't see an open issue for this and there isn't documentation, so I'm logging it here.

**Comment by GrahamCampbell** [comment]
Is this a bug? I thought this was intentional, because those features require that extension.

**Comment by avindra** [comment]
That was my thought too. In any case, it is not documented anywhere.

http://psysh.org/

There is a slight mention of potential issues in the "optional" configuration section, but that's about it.

Unless there is another documentation site I'm not aware of.

**Comment by bobthecow** [comment]
I don't think it's possible to have tab completion or history without readline. If you don't have readline (or libedit) enabled in your PHP, you're running a degraded experience for any command line usage, and there's not much we can do about it from our end.

It's mentioned if you install via Composer (see the "Suggests" list in composer.json or [on the PsySH Packagist page](https://packagist.org/packages/psy/psysh)), but we could do a better job of calling it out on the website.

**Comment by cevarief** [comment]
I have readline installed but still can't figure out how to enable tab completion. When i press tab, it just give tab, no completion. Any can tell me ?

**Comment by bobthecow** [comment]
@cevarief Run this in PsySH and tell me what it says?

    >>> $c = new Psy\Configuration
    >>> $c->getReadline()

**Comment by cevarief** [comment]
~~~
>>> $c = new Psy\Configuration
=> <Psy\Configuration #0000000017a554ca00000000723cfdd1> {}
>>> $c->getReadline()
=> <Psy\Readline\Transient #0000000017a554c800000000723cfdd1> {}
>>> function_exists('readline');
=> true
>>> function_exists('pcntl_signal') && function_exists('posix_getpid');
=> true
~~~

**Comment by bobthecow** [comment]
Does your PsySH config file disable deadline, by any chance? It should be supported if `function_exists('readline')`, but you're getting the Transient implementation.

**Comment by cevarief** [comment]
I've set to true in config file : 'useReadline' => true,
~~~
>>> $c = new Psy\Configuration
=> <Psy\Configuration #00000000425e590e0000000030bf413c> {}
>>> $c->getReadline()
=> <Psy\Readline\Libedit #00000000425e59100000000030bf413c> {}
~~~

Still no luck :)

**Comment by bobthecow** [comment]
Yeah, that's not right. If you're running the latest PsySH, and you're getting a Libedit or GNUReadline service back when you call getReadline, you should have tab completion :)

**Comment by bobthecow** [comment]
@cevarief Do you mind opening a new issue with as much detail as possible, since your issue isn't really related? (feel free to copy/paste as much of your comments from here as needed)

**Comment by bobthecow** [comment]
A note about readline/libedit has been added to the tab completion feature section of psysh.org. It seemed best to mention it in context, where users would be fairly likely to notice after their tab completion didn't work :)

Closing this for now. Feel free to send a PR against the gh-pages branch (or the README in develop branch) if you have a better idea on how to let people know.

Closing for now.
