### ISSUE TITLE
list command does not show attributes or function results

### ISSUE THREAD

**Issue by Markcial** [bobthecow/psysh#178]
Sometimes i find myself trying to list from attributes or function calls without having any results.

Example : 

``` bash
ls -la $foo->bar
```

of 

``` bash
ls -la $foo->getBar()
```

ending in a Unknown target exception.

If the command could be able to resolve the target and then list the properties would be a good time saver.

I offer myself to improve this feature whenever i got spare time.

**Comment by bobthecow** [comment]
Yes, that's the plan. One of these days.

The intent is to run the target through PHPParser. If it's a variable name, use the current implementation. If it's an expression, evaluate it and use the result as the target. This depends on `$shell->eval()` or something similar, so we're well on our way to having better targets :)

**Comment by bobthecow** [comment]
Heh. I fixed this two years ago :P
