### ISSUE TITLE
Japanese manual's some characters are garbled

### ISSUE THREAD

**Issue by gitetsu** [bobthecow/psysh#182]
Like image below(\<E3\>\<81\>\<A7\>).

![screen shot 2015-03-20 at 03 00 39](https://cloud.githubusercontent.com/assets/44036/6737184/66be7512-cead-11e4-9995-48d6ffe1cce7.png)

It's possible to reploduce in both environments:
* CentOS6: PHP 5.6.2 (remi repo, --with-libedit, I cannot type Japanese character too, related to #148)
* ArchLinux: PHP 5.6.6 (--with-readline, I can)

Do you happen to know the reason?
Or, could you tell me how to generate a manual splite file?

**Comment by bobthecow** [comment]
I imagine it's broken in the manual db, but I'm not sure why it would be. I'd expect encoding to either be broken all the time, or work all the time, not just be broken for one character (in this case, it looks like the character is `で`).

I'm able to reproduce it on my Mac as well, but I get the appropriate output when I run `echo "で"` in either `psysh` or `php -a`.

So it's likely a result of some broken parsing or string replacement when building the manual database. The weird thing is, the three bytes it's outputting manually are definitely the bytes of the UTF character, so it's not the usual mojibake where part of a unicode character is misinterpreted:

```
で
HIRAGANA LETTER DE
Unicode: U+3067, UTF-8: E3 81 A7
```

**Comment by gitetsu** [comment]
Thank you for answering :)

It seems this problem happens at [bin/build_manual#L269](https://github.com/bobthecow/psysh/blob/master/bin/build_manual#L269).
I var_dumped at L270, `$doc` is correct but `$formatted` is broken.

I will let you know if I can find more detail.

**Comment by bobthecow** [comment]
Oh. It's doing a word wrap right in the middle of a unicode character.

**Comment by bobthecow** [comment]
`htmlwrap` needs to be updated to use mbstring versions of all the functions it calls.

**Comment by bobthecow** [comment]
Also, `htmlwrap` is expecting space delimited strings. TBH I don't know the best practices as far as how to wrap Japanese or Chinese characters, I'd welcome any suggestions you have there :)

**Comment by gitetsu** [comment]
Okay. I will take a look into it.

**Comment by gitetsu** [comment]
Mmm... replacing all occurrences of  `strlen` with `mb_strlen`, `substr` with `mb_substr` in `htmlwrap` seems to fix this mojibake, but it also breaks wrap :(

**Comment by bobthecow** [comment]
Would it be appropriate to hard wrap after a certain number of characters, rather than looking for a space like it's currently doing? What are the wrapping rules in Japanese?

**Comment by bobthecow** [comment]
BAM!

![screen_shot_2015-03-21_at_11_40_19_am](https://cloud.githubusercontent.com/assets/53660/6766336/5ef8b636-cfbf-11e4-9ef1-85022a252323.png)

_And_ I implemented Kinsoku Shori!

Do me a favor? [Download the manual db file from here](https://www.dropbox.com/s/tdro0rqor3qpmb1/php_manual.sqlite?dl=1) and make sure it's not doing anything dumb, since I don't actually know what it says :)

**Comment by bobthecow** [comment]
The new manual versions have been shipped, you can download them from the links in the README. It's still got a few issues, but it's better than the old ones, and _very much_ better for the CJK versions. I'll count this one as done. Feel free to re-open (or open a new issue) if you run into anything else :)

**Comment by gitetsu** [comment]
Wow! Looks great!

Sorry for my late reply.
And thank you very much. I really appreciate it!
