### ISSUE TITLE
Add usages in doc

### ISSUE THREAD

**Issue by theofidry** [bobthecow/psysh#190]
Maybe it would be great to add some use cases:

* Laravel: PHP Artistan tinker (use natively PsySH in Laravel5)
* ZF2: [PsySH module](https://zfmodules.com/gianarb/zf2-psysh-module)
* eZ: [eZ debug shell](https://github.com/lolautruche/ezsh)
* Drupal: [drush-psysh](https://github.com/drush-ops/drush)

Would be awesome to have one with Symfony too...

**Comment by GrahamCampbell** [comment]
That link you've posted for laravel is incorrect. It's for laravel 4 which doesn't use psysh, it uses boris.

**Comment by theofidry** [comment]
Okay sorry, I found this article after looking for "psysh laravel" so I did not dig too much into it.

**Comment by GrahamCampbell** [comment]
That link is still wrong.

**Comment by GrahamCampbell** [comment]
Laravel 5 natively uses psysh. Look: https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/TinkerCommand.php.

**Comment by GrahamCampbell** [comment]
I'm the one that moved Laravel over to it, and then @bobthecow awesomeified it.

**Comment by theofidry** [comment]
Okay fixed, thanks :)

**Comment by bobthecow** [comment]
* [artisan tinker for Laravel](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/TinkerCommand.php)
 * [eZ Debug Shell for eZ Publish](https://github.com/lolautruche/ezsh)
 * [drush-psysh for Drupal](https://github.com/grota/drush-psysh)
 * [magerun console command for Magento](https://github.com/netz98/n98-magerun/blob/develop/src/N98/Magento/Command/Developer/ConsoleCommand.php)
 * [sf1-psysh-bootstrap for Symfony](https://github.com/varas/sf1-psysh-bootstrap)
 * [sf2-psysh-bootstrap for Symfony2](https://github.com/varas/sf2-psysh-bootstrap)
 * [symfony-repl for Symfony2](https://github.com/luxifer/symfony-repl)
 * [psymf for Symfony2](https://github.com/navitronic/psymf)
 * [wp-cli shell](https://github.com/wp-cli/wp-cli/blob/master/php/commands/shell.php)

**Comment by bobthecow** [comment]
@GrahamCampbell Speaking of, Laravel docs basically don't even mention `tinker`.

**Comment by theofidry** [comment]
@bobthecow Thanks for the links! You really should mention them on the website or README they're great !

**Comment by bobthecow** [comment]
These have been added to the README (in develop, it'll be updated on the repo home once that's merged to master).

**Comment by theofidry** [comment]
Great thanks!

**Comment by theofidry** [comment]
Could it be possible to add [theofidry/PsyshBundle](https://github.com/theofidry/PsyshBundle) to the list too?

There is some use cases in the doc. It's a first draft but the gist of it is there. It will need a little bit of rewording and some screenshot to make it more readable and friendly, but the uses cases are not all Symfony specific and any feedback is welcome!

**Comment by theofidry** [comment]
ping @bobthecow

**Comment by theofidry** [comment]
Cf. #208

**Comment by bobthecow** [comment]
:+1:
