### ISSUE TITLE
load a file

### ISSUE THREAD

**Issue by theofidry** [bobthecow/psysh#191]
You can already load a php file by doing `psysh path/to/phpfile.php`. However in the case where you have a wrapper, like [navitronic/psymf](https://github.com/navitronic/psymf) for using it with Symfony2 context, it's not possible anymore:

```
# repl is the name of the psysh command loaded with Symfony2 context
php app/console repl path/to/phpfile.php

[RuntimeException]   
  Too many arguments. 
```

So instead for testing my class I instantiate it loading it with it's full path, ex:

```
# in psysh shell with Symfony2 context
$userController = new AppBundle\Controller\UserController()

# do my operations on '$userController'...
```

But I find it really inconvenient to do that. An alternative is:

```
# in psysh shell with Symfony2 context
use AppBundle\Controller\UserController as UserController
$userController = new UserController()

# do my operations on '$userController'...
```

Still, the best thing would be to load the whole `src/AppBundle/Controller/UserController.php` file with it's context (like all with all the `use` statement declared in the file). No idea how to achieve that?

**Comment by bobthecow** [comment]
The `use` statements in a file are specific to that file. There's no way in PHP to "load" the use statements of one file into another file or interactive session.

**Comment by theofidry** [comment]
too bad :( Still thanks for the help
