### ISSUE TITLE
Fatal error when eval'ing "self", "static" or "parent"

### ISSUE THREAD

**Issue by Rican7** [bobthecow/psysh#193]
I was trying to create an example class with a factory method in Psysh when I noticed that using any statically resolved keywords like `self`, `static`, or `parent` were causing a fatal error.

Example:

![screen shot 2015-04-02 at 6 11 22 pm](https://cloud.githubusercontent.com/assets/742384/6974823/ef36bb50-d963-11e4-9da4-205b38900cb7.png)

The expectation is that the following code should work without error:

```php
class Foo
{
    public static function bar()
    {
        return new self();
    }
}

var_dump(Foo::bar());
```

**Comment by bobthecow** [comment]
Thanks for reporting. There's a fix in a70709b (in the develop branch) and it'll go in the next release.

**Comment by Rican7** [comment]
Oh. Awesome. :smiley:

Thanks for the quick response. Feel free to close this, then.

**Comment by GrahamCampbell** [comment]
It should get autoclosed by github when 0.5.0 is released.

**Comment by Rican7** [comment]
:+1:
