### ISSUE TITLE
Very Stange Issue On Windows

### ISSUE THREAD

**Issue by GrahamCampbell** [bobthecow/psysh#194]
https://i.starbs.net/XX5d

psysh wrote that to my disk when i made a syntax error and missed a comma in an array

**Comment by bobthecow** [comment]
That is really strange. As far as I know, the only thing that writes to the disk at all is `hist` command when called with `--save`.

Do you have the exact input that did this? Can you reproduce it?

**Comment by GrahamCampbell** [comment]
I ran this code in artisan tinker:

```php
App\User::forceCreate(array(
    'name' => 'Steven'
    'email' => 'steven@example.org'
));
```

Taken from https://github.com/laravel/framework/issues/8268.

**Comment by GrahamCampbell** [comment]
Fresh laravel/laravel install btw. :)
