### ISSUE TITLE
Run terminal commands directly from psysh

### ISSUE THREAD

**Issue by victorvalentee** [bobthecow/psysh#195]
It would be very nice to run terminal commands directly from psysh (like Facebook's phpsh).

To do this in phpsh, you just have to start with "!". Example: !whoami will give you your user name.

![screen shot 2015-04-06 at 11 55 37 am](https://cloud.githubusercontent.com/assets/4733160/7007011/e62b8e94-dc53-11e4-92a4-9d1c3969edbc.png)

**Comment by nateabele** [comment]
I had this thought cross my mind once, but then I immediately realized it was fraught with peril.

**Comment by victorvalentee** [comment]
It just annoys me that sometimes I have to change terminals just to run an "ls", or any other simple command.
Are you concerned about actions people could take with this kind of "power"? Mess up the code or the system?
Wouldn't they be able to do it without this functionality being embedded in psysh anyways?

**Comment by bobthecow** [comment]
Wanna know a secret?

![screen shot 2015-04-06 at 11 47 36 pm](https://cloud.githubusercontent.com/assets/53660/7016661/535d9670-dcb7-11e4-81b1-e4b702c7b28e.png)

**Comment by victorvalentee** [comment]
@bobthecow this is great. Keep up the good work, man.
