### ISSUE TITLE
Psysh messes the open file handle

### ISSUE THREAD

**Issue by shark0der** [bobthecow/psysh#197]
See the screenshots for a better explanation.
1) Without psysh
![image](https://cloud.githubusercontent.com/assets/528959/7201855/d84479fc-e514-11e4-9f75-4342c6e0f95e.png)
2) With psysh
![image](https://cloud.githubusercontent.com/assets/528959/7201860/efa4f2a2-e514-11e4-8275-01bd5d150c76.png)

Code:
```<?php
require '/usr/local/bin/psysh';

function getNext() {
    $f = fopen('input.csv', 'r');
    while (!feof($f)) {
        $line = fgetcsv($f);
        eval(\Psy\sh());
        yield $line;
    }
}

foreach (getNext() as $value) {
    print_r($value);
}
```

**Comment by bobthecow** [comment]
Try `\Psy\Shell::debug(get_defined_vars())` instead of `eval(\Psy\sh())`

**Comment by shark0der** [comment]
The one you suggested works well.

**Comment by bobthecow** [comment]
The problem was that PsySH was (mistakenly) returning the file handle variable that you'd passed in initially, and it wasn't happy about making the round trip (because PHP can't serialize/unserialize resources). This has been fixed in the `develop` branch, feel free to test that out and confirm :)
