### ISSUE TITLE
How to indent in psysh REPL

### ISSUE THREAD

**Issue by xjchengo** [bobthecow/psysh#199]
while i define a function in pshsh, how to indent the code block conveniently?

**Comment by bobthecow** [comment]
I'm not entirely sure what you're asking. Do you mind giving an example?

**Comment by xjchengo** [comment]
```
>>>function hello_world () {
...____echo 'hello, world!';
...}
```

Like the example above, the underscore represents blank. In editor, I can insert four blank by typing tab. But in psysh, tab is used to completion. So is there any way to insert real tab conveniently?

**Comment by bobthecow** [comment]
You can insert a literal tab character by typing `ctrl+v tab`.

**Comment by xjchengo** [comment]
Wow, it works. Thanks. I am curious it is a feature of psysh or shell.

**Comment by bobthecow** [comment]
That's a feature of readline and libedit, which PsySH uses to handle all input. That hotkey also works for inserting a literal tab in Bash, as well.
