### ISSUE TITLE
Class name resolution with class keyword fails

### ISSUE THREAD

**Issue by byCedric** [bobthecow/psysh#202]
So I was playing with Laravel 5.1 the other day and I noticed the use of the ["new" class name resolution](http://php.net/oop5.basic#language.oop5.basic.class.class) of PHP 5.5. So I tried the new feature in Psysh. It turns out every time I try to use it, no matter which class, it always raises a fatal error `Class constant '_myclass_::class' not found in eval()'d code on line 1`.

I'm not sure _if_ Psysh is supposed to handle the relative "new" get_class() equivalent, since the composer requirement is PHP 5.3 and above, but it sure would be useful.

```
>>> phpversion();
=> "5.6.9"
>>> $user = new \App\User();
=> <App\User #00000000062c588e0000000151eca6ab> {}
>>> $class = \App\User::class;
PHP Fatal error:  Class constant 'App\User::class' not found in eval()'d code on line 1
```

**Comment by bobthecow** [comment]
Thanks for reporting this. It has been fixed in the development branch, and will go out in the 0.5.0 release!

**Comment by byCedric** [comment]
Thanks for the quick response. I will try it out asap!
