### ISSUE TITLE
PsySH chokes on recursive functions

### ISSUE THREAD

**Issue by MrDys** [bobthecow/psysh#216]
It seems like PsySH doesn't know what to do with recursive functions:

![screen shot 2015-07-16 at 9 32 01 am](https://cloud.githubusercontent.com/assets/123333/8724968/8c572c84-2b9f-11e5-9b1e-7a477fae9a3e.png)

I've even tried pre-defining the function in ~/.psysh/rc.php:

![screen shot 2015-07-16 at 9 34 01 am](https://cloud.githubusercontent.com/assets/123333/8724971/99d8e26c-2b9f-11e5-9567-d3ec830432f8.png)

**Comment by bobthecow** [comment]
Thanks for reporting. This has been fixed in v0.5.2 :)
