### ISSUE TITLE
Issue assigning anonymous function to a variable

### ISSUE THREAD

**Issue by paolodina** [bobthecow/psysh#217]
```
$ psysh
Psy Shell v0.5.1 (PHP 5.5.9-1ubuntu4.11 — cli) by Justin Hileman
>>> $foo = function() {};
=> Closure {#173
     file: "/home/vagrant/.composer/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(76) : eval()'d code"
     line: "1 to 2"
   }
```

Any hint?

**Comment by GrahamCampbell** [comment]
@paolodina That's not an error...

**Comment by GrahamCampbell** [comment]
That's us describing the closure you've made.

**Comment by paolodina** [comment]
I'm really sorry, first time using php.

**Comment by bobthecow** [comment]
@GrahamCampbell I did like the old style Closure formatting, where it showed you the actual function signature :)

**Comment by GrahamCampbell** [comment]
Yeh, me too.

**Comment by bobthecow** [comment]
@paolodina It's not your fault, the output isn't as intuitive as it could be. For future reference, anything starting with `=>` is the output of the previous command. Errors are in RED and stand out a lot more :)
