### ISSUE TITLE
Old-style Closure dump format?

### ISSUE THREAD

**Issue by bobthecow** [bobthecow/psysh#218]
The new Closure formatting feels less intuitive and easily grokkable than before. Should we re-implement the function-signature-style formatting in terms of VarDumper? I took a look, but didn't get very far. @nicolas-grekas how tough would this be?

**Comment by nicolas-grekas** [comment]
you could do this by adding a virtual prop, let's name it "signature", when you generate the signature of the closure in PHP style?

**Comment by bobthecow** [comment]
It would be awesome to show *less* when dumping a Closure, not more :)

Compare:

<img width="762" alt="screen shot 2015-08-23 at 10 27 58 am" src="https://cloud.githubusercontent.com/assets/53660/9429358/130ce098-4982-11e5-8bbe-5bbc48d0466e.png">

<img width="762" alt="screen shot 2015-08-23 at 10 27 55 am" src="https://cloud.githubusercontent.com/assets/53660/9429360/151b23b8-4982-11e5-81a6-ed106b08207f.png">

My preference would be to show the old style for most output, and the new style (maybe with the signature as well?) for `dump --all` and possibly regular `dump`.

**Comment by nicolas-grekas** [comment]
Just acking this. So, you would also represent "use" right at their place
in the signature I believe. When default arg values are array, would you
present them on the same line, inlined?

**Comment by nicolas-grekas** [comment]
What about this:
```
=> Closure {#177
    signature: "function ($a) use ($b)",
    use: [
      "$b" => 5,
    ],
    file: "/home/nicolas.grekas/Code/psysh/src/Psy/ExecutionLoop/Loop.php(76) : eval()'d code",
    line: "1 to 2",
}
```

And in short mode (the default one), we hide everything but the signature?
```
=> Closure {#177
    signature: "function ($a) use ($b)"
}
```

I'd like to keep the `Closure {#177` info, it's important to still tell the user that an anonymous functions is an object of type `Closure` imo.

**Comment by bobthecow** [comment]
@nicolas-grekas I'm all about removing redundant or obvious information where possible. We probably don't need to tell users that an anonymous function is an object of type Closure because all anonymous functions are objects of type Closure ;)

Is there a straightforward way to render it just like before (or maybe with `#177` in between the parens)? If not, that's cool, but I feel like that's the most information dense way to represent anonymous functions and it'd be awesome if we could do it again.

**Comment by nicolas-grekas** [comment]
Fixed by https://github.com/symfony/symfony/pull/27768
