### ISSUE TITLE
Unable to add my own implementation of the Closure caster

### ISSUE THREAD

**Issue by ramondelafuente** [bobthecow/psysh#219]
I was trying to use PsySH as a repl for Lambdalicious, and need to set my own version of the Closure dumper.

Calling `addCasters()` on the `\Psy\Configuration` runs `addCasters()` on the Presenter, which in turn runs that on the `Cloner()`. But both are instantiated in the code without a way to override, and the Cloner already has a set of `$defaultCasters` in `AbstractCloner` that I can't seem to avoid.

All-in-all it is unclear to me how set my own Casters in the right spot. Is there an example I can look at?

**Comment by GrahamCampbell** [comment]
Casters have been removed in 0.5.

**Comment by bobthecow** [comment]
Presenters have been removed. Casters have been added :)

**Comment by nicolas-grekas** [comment]
@ramondelafuente I may help. Casters are called in registration order, which means if yours is last, it can completely ignore what any previous did. Just for my curiosity, what is your caster doing?
You may also be interested in http://symfony.com/doc/current/components/var_dumper/advanced.html#casters

**Comment by bobthecow** [comment]
I'm closing this one due to inactivity. If you have further questions, please feel free to re-open it :)
