### ISSUE TITLE
Add automatic update checks

### ISSUE THREAD

**Issue by bobthecow** [bobthecow/psysh#230]
It's not always obvious when a new version is available (see comments on #225).

Since this package is often installed as a binary, or installed globally, or installed in many different projects, it would be super useful to have some sort of automatic update check. That said, automatic updating is problematic, so let's just add a check and prompt the user to update.

As I see it, there are a few options:
1. Automatically check for updates every time PsySH launches.
2. Automatically check for updates once per day/week/month.
3. Prompt the user to let PsySH check for updates always/daily/weekly/monthly.
4. Don't check for updates ever.

I don't think any of these are mutually exclusive. If there were a couple of configuration options, say:

``` php
[
  'updateCheck' => 'automatic', // or 'prompt', 'never'
  'updateCheckInterval' => 'daily', // or 'always', 'weekly', 'monthly'
]
```

… then we could cover all these options and let the user decide what's best for them.

A sane default would probably be "prompt weekly", but I don't have a strong preference. In the prompt, we could also let the user know about the configuration options:

> It has been over a week since PsySH was updated. Check for updates?
> (To automatically check for updates, or to change how often you're prompted, see …)

Alternatively, on the first prompt we could ask the user what their preferences are and store those.

I'd also probably suppress the check/prompt/etc if PsySH is invoked via `eval(Psy\sh())` (i.e. as an interactive debugger rather than a REPL).

/cc @jimdelois @theofidry

**Comment by theofidry** [comment]
:+1: :)

I would let the default at monthly check: weekly seems a bit too much and it would also be the same frequency as composer check.

**Comment by GrahamCampbell** [comment]
> I would let the default at monthly check

Monthly is way too long IMO. Daily would make more sense.

**Comment by bobthecow** [comment]
If it's automatic, daily is fine. If it's prompting, daily would be super annoying :)

**Comment by GrahamCampbell** [comment]
> If it's prompting, daily would be super annoying :)

Mayby we need an option for people to reply to the prompt with "remind me later"?

**Comment by theofidry** [comment]
Maybe you can do an automatic check daily but in that case it would be better to leave things at showing a notice to tell the user an update is available.

**Comment by GrahamCampbell** [comment]
Yeh, maybe. We'd need to make sure subsequent warnings are unobtrusive though. I'd probably want the initial warning to be quite clear though.

**Comment by bobthecow** [comment]
Once we've established that their current version is outdated, we can just add "Update available" to the header every time it starts. Something like:

```
Psy Shell v0.6.0-dev (PHP 7.0.0RC1 — cli) by Justin Hileman
Update available — http://psysh.org
>>>
```
