### ISSUE TITLE
Can't find the documentation file for PHP

### ISSUE THREAD

**Issue by digfish** [bobthecow/psysh#233]
On a Laravel 5 project under Windows 10 Home (64-bit,portuguese), psysh is not able to find the documentation database file (php_manual.sqlite) under the standard location C:\Users\[username]\AppData\Roaming\PsySh .
 Usually I start PsySh under laravel with

`php artisan tinker` 

under the root directory of the project.
I tried to use a configuration file for PsySh like the one it is quoted in the github page and call it at the start of execution of psysh with:

`php artisan tinker -vvv ./psysh-config.php`

but that does not work, either.

**Comment by bobthecow** [comment]
Sorry about the delayed response.

Is your filesystem case sensitive? It should be `PsySH` not `PsySh`, so that might be it.

Otherwise, run `Psy\info()` in psysh and let me know what it says?

**Comment by jaden** [comment]
I'm running psysh globally with the same problem of not finding the documentation DB file.

It's located here: C:\Users\dan\AppData\Roaming\PsySH\php_manual.sqlite 

This is the output of Psy\info()
```
>>> Psy\info()
=> [
     "PsySH version" => "v0.5.2",
     "PHP version" => "5.6.13",
     "default includes" => [],
     "require semicolons" => false,
     "config file" => [
       "default config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "pcntl" => [
       "pcntl available" => false,
       "posix available" => false,
     ],
     "readline" => [
       "readline available" => false,
     ],
     "history" => [
       "history file" => "C:\Users\dan\.config/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => false,
       "custom matchers" => [],
     ],
   ]
```

**Comment by digfish** [comment]
Sorry for answering just now, here is the output of Psy\info() on my system:
```
=> [
     "PsySH version" => "v0.6.0-dev",
     "PHP version" => "5.6.11",
     "default includes" => [],
     "require semicolons" => false,
     "config file" => [
       "default config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "pcntl" => [
       "pcntl available" => false,
       "posix available" => false,
     ],
     "readline" => [
       "readline available" => false,
     ],
     "history" => [
       "history file" => "C:\Users\sam\.config/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => false,
       "custom matchers" => [],
     ],
   ]
```
I also have the documentation sqlite file located on  C:\Users\sam\AppData\Roaming\PsySH\php_manual.sqlite

**Comment by bobthecow** [comment]
Sorry for dropping the ball on this. Do you mind checking `getenv('APPDATA')` inside PsySH and seeing what it says?

**Comment by bobthecow** [comment]
Oh, and `getenv('HOME')`

**Comment by jaden** [comment]
I found that the APPDATA path wasn't one of the data dirs being checked. Due to the use of the XDG Base Directory specification, Windows paths aren't included.

These are the paths that _are_ being checked:
```
C:\Users\dan/.psysh/php_manual.sqlite
C:\Users\dan\.local\share/psysh/php_manual.sqlite
/usr/local/share/psysh/php_manual.sqlite
/usr/share/psysh/php_manual.sqlite
```

In my opinion, all that needs to change is the documentation. Putting php_manual.sqlite in C:\Users\dan/.psysh/ works fine.

I've submitted a pull request with the documentation change.

And for the sake of completeness, here's the info you requested.
```
>>> getenv('APPDATA');
=> "C:\Users\dan\AppData\Roaming"
>>> getenv('HOME');
=> "C:\Users\dan"
>>> file_exists(getenv('APPDATA') . '/PsySH/php_manual.sqlite');
=> true
```

**Comment by bobthecow** [comment]
So the bug here is that the presence of a HOME environment variable is throwing off the AppData directory support. I'll get a fix in for that :)

**Comment by bobthecow** [comment]
@digfish Can you confirm that you have `getenv('HOME')` as well?
