### ISSUE TITLE
Could not fetch ::class consts properly

### ISSUE THREAD

**Issue by lvht** [bobthecow/psysh#238]
When execute `A::class`,  no matter the class `A` is exists or the `A` is an `interface`, we should get `"A"`, but given
```
PHP Fatal error:  Class 'A' not found in eval()'d code on line 1
```

In fact, there is no need to check the existance of class while fetching the `::class` const.

**Comment by GrahamCampbell** [comment]
I thought this was already fixed?

**Comment by lvht** [comment]
@bobthecow Would you like to offer a new release schedule?

**Comment by bobthecow** [comment]
@GrahamCampbell That was a different issue. The issue fixed here is that PHP lets you call `::class` on *anything*, whether it exists or not, and it just returns the fully-qualified name you referred to it as.

```php
use ImaginaryNamespace\ImaginaryClass;
echo ImaginaryClass::class;
```

… works in PHP even if there's no such namespace and no such class.

**Comment by GrahamCampbell** [comment]
Right. :)

**Comment by bobthecow** [comment]
@lvht I'm not sure when the next release will be yet. Feel free to use the dev version in the meantime :)

**Comment by GrahamCampbell** [comment]
NB, you can use `0.6.*` to install it.

**Comment by GrahamCampbell** [comment]
Rather than `0.5.*`.

**Comment by bobthecow** [comment]
but you might need an `@dev` depending on your minimum stability settings, yeah?

**Comment by GrahamCampbell** [comment]
Yeh. ;)
