### ISSUE TITLE
"Class 'A' not found in eval()'d code" when a class refers to itself

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#241]
Psy Shell v0.6.0-dev (PHP 5.5.9-1ubuntu4.11 — cli) by Justin Hileman
    >>> class A { static function f() { return new A; } }
    PHP Fatal error:  Class 'A' not found in eval()'d code on line 1

The same code works with `eval` or other PHP shells.

**Comment by bobthecow** [comment]
This might already be fixed in the dev branch, if you want to take a look there.

**Comment by tgr** [comment]
Can reproduce on 652fec4.

**Comment by kocoten1992** [comment]
@tgr , running into it, a work around maybe this?

```return new self```

**Comment by GrahamCampbell** [comment]
What about on the latest version?

**Comment by kocoten1992** [comment]
@GrahamCampbell same with 0.7.1

Maybe a patch like this: check if the return instance is the same name at the class, if so, pass it for the time being.

Not sure how it play with namespace, but dealing with that later :dancer:

**Comment by bobthecow** [comment]
Sorry about the wait. This has been fixed in `develop` and will go in the next point release.
