### ISSUE TITLE
unset($resource) does not release the resource

### ISSUE THREAD

**Issue by mpyw** [bobthecow/psysh#242]
PHP Manual says [here](http://php.net/manual/en/language.types.resource.php#language.types.resource.self-destruct)...

> Thanks to the reference-counting system introduced with PHP 4's Zend Engine, a resource with no more references to it is detected automatically, and it is freed by the garbage collector. For this reason, it is rarely necessary to free the memory manually.

Both of the following codes work expectedly. We can safely delete `test.txt`. 

``` php
$fp = fopen('test.txt', 'a');
fclose($fp);
while (true) { }
```

``` php
$fp = fopen('test.txt', 'a');
unset($fp);
while (true) { }
```

However, on PsySH ...

![d6e399fd-ac01-331f-d8c8-a5704b8472b7](https://cloud.githubusercontent.com/assets/1351893/10248337/cfa24486-6959-11e5-94eb-15f58c4aa61b.png)

It seems that PsySH has a bug around the implemention of symbol table...

**Comment by GrahamCampbell** [comment]
I think this is intentional is it not?

**Comment by GrahamCampbell** [comment]
Due to the way the internals work.

**Comment by mpyw** [comment]
> Due to the way the internals work.

Yes, PsySH seems to have powerful features for reflection. Even so, all variables (and resources) related to `$fp` should be completely released after `unset($fp)`.

**Comment by bobthecow** [comment]
I'm not seeing this behavior on `v0.6.0-dev`. Do you mind checking the dev branch to see if it's resolved?

**Comment by mpyw** [comment]
Umm...

![2015-10-03 11 43 32](https://cloud.githubusercontent.com/assets/1351893/10261136/0771c836-69c4-11e5-8027-fcbcb2bea6c7.png)

I also found important things. The manual removal with GUI seems to be blocked, whereas the command `rm test.txt` works in any cases. What does it mean?

**Comment by bobthecow** [comment]
This still looks fine to me… (`v0.7.1`, PHP `v7.0.3`, El Capitan)

Maybe it was just the wrong version of PHP / OS that was getting you?

**Comment by mpyw** [comment]
Now I'm using PHP `7.0.1` and OSX `10.11.3`. I can still get the error :tired_face:

**Comment by beyondlimits** [comment]
Windows 7, PHP 7.1.0 - tested and couldn't reproduce it. Right after the resource is unset I was able to remove the file.

**Comment by bobthecow** [comment]
Does this issue persist? I'm still unable to reproduce it.
