### ISSUE TITLE
Method definition error with symfony 3.0

### ISSUE THREAD

**Issue by rkgrep** [bobthecow/psysh#247]
Error appears both in PHP 5.5 and PHP 7.0
````
[ErrorException]                
Declaration of Psy\Shell::renderException() should be compatible with Symfony\Component\Console\Application::renderException(Exception $e, Symfony\Component\Console\Output\OutputInterface $output)
````

**Comment by GrahamCampbell** [comment]
https://github.com/bobthecow/psysh/commit/b80a2f679649e007f7d87df9f8da40bddf93e9a4

**Comment by GrahamCampbell** [comment]
Already been fixed.

**Comment by rkgrep** [comment]
This happened on a fresh laravel 5.2 installation. Looks like invalid dependency.

**Comment by GrahamCampbell** [comment]
> This happened on a fresh laravel 5.2 installation. Looks like invalid dependency.

Not an invalid dependency. Laravel 5.2 is NOT ready yet. We're waiting for a v0.6.0 release here, which will happen before Laravel v5.2.0 is marked as stable, and ready for use.

**Comment by rkgrep** [comment]
Not in Laravel, but in PsySH. It allows Symfony 3.0, however it is not supported. Of course, this is not critical for v0 releases.

**Comment by bobthecow** [comment]
@rkgrep it's been fixed in PsySH, but only on HEAD. If you want to use PsySH with Symfony 3.x before the 0.6.0 release, change your dependency to `0.6.x-dev`.

**Comment by GrahamCampbell** [comment]
> change your dependency to 0.6.x-dev.

Not possible since laravel has a hard dependency on 0.5.x. As soon as 0.6.0 is tagged, we'll change it.

**Comment by bobthecow** [comment]
:+1:
