### ISSUE TITLE
0.6.x Release

### ISSUE THREAD

**Issue by GrahamCampbell** [bobthecow/psysh#248]
How far off is this now @bobthecow? Anything I can do to help. This will basically be a blocker for the Laravel 5.2.0 release.

**Comment by GrahamCampbell** [comment]
I think the plan for Laravel 5.2 is to release it in about 5 or 6 weeks.

**Comment by GrahamCampbell** [comment]
That's not an official statement though. Just my personal guess. I've not actually talked to Taylor about when he plans to release, recently.

**Comment by bobthecow** [comment]
I don't know of any blockers, other than confidence in the stability of a dependency on an unreleased Symfony 3.x.

I'm traveling this week, but I'm happy to cut a release next week unless there's something more we want to get in 0.6.0.

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by bobthecow** [comment]
@GrahamCampbell how are you feeling about the current state of the dev branch? Anything you want to see in it?

**Comment by GrahamCampbell** [comment]
Give me a few mins. :)

**Comment by GrahamCampbell** [comment]
Ok, I think we're ready now. :)

**Comment by bobthecow** [comment]
:ship:d
