### ISSUE TITLE
loading all your namespaces

### ISSUE THREAD

**Issue by BardiaAfshin** [bobthecow/psysh#259]
I'm kicking of psysh and doing 

```php
require_once('./vendor/autoload.php');
```

but when I try to
```php
use my\library
```

It returns false. How do you successfully load all your registered namespaces via composer autoloader into psysh so you can test drive your code from the REPL?

**Comment by bobthecow** [comment]
The use is actually working, the `false` is a bug :)

**Comment by bobthecow** [comment]
Okay, a fix is in the dev branch. Thanks for reporting!
