### ISSUE TITLE
[Question] About Jupyter integration

### ISSUE THREAD

**Issue by castarco** [bobthecow/psysh#267]
Hello,

I'm starting to contribute to the Jupyter-PHP project ( https://github.com/dawehner/jupyter-php , a "kernel" to integrate the PHP language into the Jupyter/IPython notebook ).

One of the commented tasks in the TODO list is to integrate a complete REPL instead of using `eval`, and that's the reason why I'm telling it here.

First, before delving into PsySH related points, I'll comment the basic details of how works the integration with Jupyter.

This is (deprecated by now, IPython was renamed to Jupyter) the command to launch a PHP Jupyter notebook:

``` bash
ipython notebook --KernelManager.kernel_cmd="['php', '/path-to/ipython-php/ipython_php.php', '{connection_file}']"
```

The jupyter binary is executed, and then it does an `exec` call to the `php /path-to/ipython-php/ipython_php.php` command. Both binaries can stablish communication through a ZMQ channel, and there is a basic RPC specification created over ZMQ.

There are three basic methods that can be used in the RPC system of Jupyter:
- execute requests
- history request
- shutdown

I don't know right now if there is a more rich set of RPC methods, these are the implemented methods in the current PHP "kernel".

As you can imagine, the _execute requests_ are fulfilled with simple `eval` calls, and the history is maintained by the kernel, but it might be better.
---

My question starts here. If I want to integrate PsySH... what's the better way to do it? I've though on many options, but I don't know if I'm missing something nor what's the best of them:
- Use PsySH as a requirement and use a subset of its components.
- Wrap the PsySH executable binary and communicate with it with "pipes" (I think this approach is a little bit weird, but it's another option).
- Integrate the "kernel" capabilities in form of PsySH plugin (I remember something about a plugins system that was being developed many months ago for PsySH).
- Integrate the "kernel" capabilities inside the core of PsySH (I think this is a little bit weird too).
---

**Some thoughts:**
- Personally, I prefer the first option, because it brings some independence between projects.
- The second option is a little bit problematic because it poses a lot of limits on what can we do with the internal state of the "kernel".
- The third option is tied to the finishing of the plugins system, but I haven't read nothing about this subproject state in many months, and I'm not sure if this is compatible with the Jupyter communication schema.
- About the fourth option, well... it smells to excessive coupling.
---

What do you think?

Thank you for your time!

**Comment by bobthecow** [comment]
_[copying my responses from the gitter channel]_

PsySH should work for that.

You should be able to use PsySH by swapping out the input and output classes for something that maps to the ZMQ.

> And is possible to use their classes as a dependency for another composer package? Or the distribution only has the PHAR binary?

Yeah, it works as either a phar or a composer dependency. The projects that ship with it (Laravel, Drush, etc) all use it that way. The phar is mostly for convenience.

I think there are a couple of issues on the repo about interactive web shells, someone might have already done some of the work.

> I've integrated psysh into a framework-less project (we mostly use libraries through Composer instead), pretty painlessly. Making a myapp shell command was as simple as adding psysh in composer.json and writing a few lines of code.

For the jupyter integration it shouldn't be much more than that. Shell::run accepts an InputInterface and OutputInterface instance. By default they use stdin and stdout. But you could just as easily pass in a pair of services that talk to jupyter.

you might not even need input interface, actually. you might want shell eval instead. depends on how it's easiest to map to jupyter.

wait, i'm misremembering. you wouldn't use inputinterface at all. that's for the command line arguments.

you'd implement an outputinterface service (like https://github.com/bobthecow/psysh/blob/master/src/Psy/Output/ShellOutput.php) and a readline service (like https://github.com/bobthecow/psysh/blob/master/src/Psy/Readline/Transient.php)

(the readline instance would give you access to history as well)

**Comment by bobthecow** [comment]
(for posterity) check out https://github.com/Litipk/Jupyter-PHP and please contribute :)
