### ISSUE TITLE
PHP7 Ubuntu 14.04 fails to arrow history

### ISSUE THREAD

**Issue by miraage** [bobthecow/psysh#269]
Here is result of up/down.

```
Psy Shell v0.5.2 (PHP 7.0.0-2+deb.sury.org~trusty+1 — cli) by Justin Hileman
>>> ^[[A^[[B
```

**Comment by miraage** [comment]
Looks like it's PHP related error because `php -a` gives same.

**Comment by bobthecow** [comment]
Try running it inside `rlwrap`?

**Comment by msheakoski** [comment]
I noticed that for PHP 5.x on Ubuntu, the `php5-readline` package is installed by default, but PHP 7 (via `ppa:ondrej/php-7.0`) does not install it. `sudo apt-get install php7.0-readline` fixed it for me. After that, it was no longer necessary to use `rlwrap`.

**Comment by bobthecow** [comment]
Oh, nice! Thanks @msheakoski
