### ISSUE TITLE
Display ascii code large 128 has problem in windows 10 chinese version

### ISSUE THREAD

**Issue by wwfifi** [bobthecow/psysh#270]
windows 10 chinese version default use gbk encode in console, so display some ascii code large 128 not correct.
Shell.php about line 836:
```return sprintf('Psy Shell %s (PHP %s — %s)', self::VERSION, phpversion(), php_sapi_name());```
display:
```Psy Shell v0.6.1 (PHP 5.5.26 鈥?cli) by Justin Hileman```
line 624 display also not correct.

**Comment by bobthecow** [comment]
I've added a `useUnicode` config option in the `develop` branch. It lets you explicitly disable PsySH-generated unicode character output, which should do the trick for you.

At some point I plan to add code point detection for Windows users which will toggle the `useUnicode` option automatically, depending on the current code point. But for now, it'll be available via a config option :)

**Comment by bobthecow** [comment]
This has been fixed in the latest release. Please set `'useUnicode' => false` in your psysh config to use alternate glyphs.
