### ISSUE TITLE
Test failure with PHP-Parser 1.2.1

### ISSUE THREAD

**Issue by toddmazierski** [bobthecow/psysh#273]
## Description

A test failure occurs if the [minimum required version](https://github.com/bobthecow/psysh/blob/753011e4e8fb5a14fdfb1cb0891b668dc8c24e50/composer.json#L19) (1.2.1) of PHP-Parser is used:

```
1) Psy\Test\CodeCleaner\ValidClassNamePassTest::testProcessValid with data set #22 ('$obj = new class() {}')
Psy\Exception\ParseErrorException: PHP Parse error: Syntax error, unexpected T_CLASS on line 1

/home/tmazierski/development/psysh/src/Psy/Exception/ParseErrorException.php:40
/home/tmazierski/development/psysh/test/Psy/Test/CodeCleaner/CodeCleanerTestCase.php:44
/home/tmazierski/development/psysh/test/Psy/Test/CodeCleaner/ValidClassNamePassTest.php:130
/usr/share/composer/vendor/phpunit/phpunit/src/TextUI/Command.php:179
/usr/share/composer/vendor/phpunit/phpunit/src/TextUI/Command.php:132
```

## Cause

I _think_ this is because only PHP-Parser 2.x supports PHP 7.0, but I'm not sure what the best solution is. A couple I thought of were:

1. Require PHP-Parser 2.x in development
2. Add a conditional to the test

**Comment by GrahamCampbell** [comment]
This is intentional.

**Comment by GrahamCampbell** [comment]
PHP 7 is ONLY supported if you use PHP-Parser 2.x.

**Comment by GrahamCampbell** [comment]
> Require PHP-Parser 2.x in development

No. We also want to allow 1.x for PHP 5.

**Comment by toddmazierski** [comment]
Hi, @GrahamCampbell! I'm not entirely sure I'm following. If a developer has the minimum version of PHP-Parser installed, and s/he runs the unit tests, a test failure ought to be expected?

**Comment by GrahamCampbell** [comment]
This is a bug in php-parser 1.x allowing itself to be installed on php 7. That's out of our control.

**Comment by toddmazierski** [comment]
> This is a bug in php-parser 1.x allowing itself to be installed on php 7. That's out of our control.

Ah, sorry, I should have mentioned this in the original description, but I'm using PHP 5.

**Comment by GrahamCampbell** [comment]
Ok, then, our min version must reflect what's needed to get most thing to work, not everything.

**Comment by toddmazierski** [comment]
Fair enough! :smile: Just thought I'd make note of it. Thanks for considering it.

**Comment by bobthecow** [comment]
Oh, this test case probably should be gated behind a check for PHP 7. It worked with an older version of PHP Parser 1.x, but my guess is that it was unintentional on their part?

**Comment by GrahamCampbell** [comment]
> Oh, this test case probably should be gated behind a check for PHP 7.

The issue was present on PHP 5. I just originally assumed it was due to PHP 7.

> Ah, sorry, I should have mentioned this in the original description, but I'm using PHP 5.

**Comment by GrahamCampbell** [comment]
Let me send a PR to replicate this.

**Comment by GrahamCampbell** [comment]
https://github.com/bobthecow/psysh/pull/274

**Comment by GrahamCampbell** [comment]
Let's see what travis actually does here.

**Comment by GrahamCampbell** [comment]
There is indeed an error. Looks like we need to skip that test on php parser 1.x.

**Comment by GrahamCampbell** [comment]
Maybe we need to work php-parser 1.x test into the travis build matrix?

**Comment by bobthecow** [comment]
That seems reasonable, since we support it :)
