### ISSUE TITLE
Allow declare(strict_types=1)

### ISSUE THREAD

**Issue by tom--** [bobthecow/psysh#275]
Does psysh allow me to declare(strict_types=1)?

If no, could this feature be added somehow? Perhaps typing it as the first thing in a new session. Perhaps as a command like flag `-s`.

**Comment by bobthecow** [comment]
This _should_ be fixed by nikic/PHP-Parser@719ca71d4ac80e1985dcd91dd8ec5a47db58ad80. I'll take a look and see.

**Comment by bobthecow** [comment]
Yeah, it looks like that commit fixes the parse error. Once PHP-Parser cuts a new release, parsing it will work as expected. It might take some shenanigans to get the strict types declaration to carry over between lines (kind of like the way we do namespaces), but that would prolly be mostly copypaste.

**Comment by GrahamCampbell** [comment]
This can be closed now?

**Comment by GrahamCampbell** [comment]
Oh, wait, no. No php-parser release yet. ;(

**Comment by bobthecow** [comment]
<img width="762" alt="screen shot 2016-03-05 at 11 47 59 pm" src="https://cloud.githubusercontent.com/assets/53660/13552978/b498e72e-e32c-11e5-8555-cdd715003939.png">

Let's see your `php -a` do _that_ :P

**Comment by bobthecow** [comment]
This is fixed in develop and will go out in the next release. Note that you'll need to upgrade to the latest PHP Parser release for it to work.

**Comment by tom--** [comment]
Tekspacular! Thank you.
