### ISSUE TITLE
Implement rlwrap (History)

### ISSUE THREAD

**Issue by kbirmhrjn** [bobthecow/psysh#276]
The fact that the up/down arrow doesn't work for looking up the history, while ssh'ing vagrant box is a shame. we need a way to achieve it.

**Comment by bobthecow** [comment]
I'm assuming Ubuntu? `sudo apt-get install php7.0-readline` :)

**Comment by bobthecow** [comment]
@kbirmhrjn Please let me know if this didn't fix the issue for you, and we can reopen.

**Comment by kbirmhrjn** [comment]
yeah, your solution fixed it. ;)

**Comment by bobthecow** [comment]
:+1:

**Comment by ezmiller** [comment]
+1 I'd like a solution too, but I'm on Mac.

**Comment by ezmiller** [comment]
This isn't maybe a perfect solution, but it's working for me on os x:
```Bash
brew update
brew install rlwrap
rlwrap psysh
```
