### ISSUE TITLE
How to include psysh in php file?

### ISSUE THREAD

**Issue by we138** [bobthecow/psysh#277]
I am trying to use the *psysh* debugger and install it via *composer*. But I can't find how I can call it from simple php file, the official tutorial says:

    add a this line in code eval(\Psy\sh());

but if I write this the interpretator doesn't know this function. How can I correctly include psysh functions in my code?

**Comment by bobthecow** [comment]
You either require it, or you require an autoloader that knows where it is.

Did you install it locally or globally via Composer? Do you use Composer for your project already, or is this the only thing you're using composer for?

**Comment by we138** [comment]
I install composer only psysh.But yesterday I find solution, thank you :)

**Comment by bobthecow** [comment]
:+1: Glad to hear :)
