### ISSUE TITLE
Environment variable support / Xdebug

### ISSUE THREAD

**Issue by rayfoss** [bobthecow/psysh#286]
With vanilla phpunit I am able to set `-d key[=value]            Sets a php.ini value.` and it will work with the current shell's environment variables such as  `XDEBUG_CONFIG="idekey=atom"` however with php -a and Psych, var_dump($_ENV) comes out empty and xdebug_break() statements don't break.

I'm trying to step through with xdebug and codebug/Xdebug by artbek. Running code with phpunit or the browser works fine, but I can't get it to stop in a php interactive shell.

**Comment by bobthecow** [comment]
you should be able to launch psysh with env vars (depending on your shell, something like `XDEBUG_CONFIG="idekey=atom" psysh ...`) and those will pass through to everything.

**Comment by passcod** [comment]
Well, this doesn't work. I've tried all the various standard ways of passing env to a program, and none work. But deeper than that, the `$_ENV` is always `[]`, which means that _none_ of the environment is passing through. My environment has about two dozen variables in it by default, and none of them are getting through? Not surprising trying to set extra ones doesn't work, then.

So I experimented a bit:

```php
#!/usr/bin/env php
<?php var_dump($_ENV);
```

Put that in a file, make it executable… no environment gets through! Hence, this is not a Psysh problem, it's a PHP problem. For the sake of record, PHP versions:

```
PHP 7.0.10 (cli) (built: Aug 21 2016 07:35:18) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

Interestingly, though, using `getenv()` works! So it's just `$_ENV` not getting populated. And what does the manual say about [`$_ENV`](https://secure.php.net/manual/en/reserved.variables.environment.php)? Not much, except for the first comment:

> If your `$_ENV` array is mysteriously empty, but you still see the variables when calling `getenv()` or in your `phpinfo()`, check your http://us.php.net/manual/en/ini.core.php#ini.variables-order ini setting to ensure it includes "`E`" in the string.

Oh dear! Seems it is, after all, not a Psysh problem, not a PHP problem, but a configuration problem. And when you're fishing for your php.ini to correct this, remember some installations have a separate config for the CLI…
