### ISSUE TITLE
not support direct closure call

### ISSUE THREAD

**Issue by condy0919** [bobthecow/psysh#287]
when eval ```print (function($x){return $x;})(1);``` statement, it gives such error: ```PHP Parse error: Syntax error, unexpected '(' on line 1``` .
while it's valid code in ```php -a``` mode.

**Comment by Taluu** [comment]
It also works in `php -r` (had this problem too a short while ago).

But I'm not sure this isn't a problem with PHP-Parser rather than psysh

**Comment by bobthecow** [comment]
You're right, it's PHP-Parser. But they added support for this recently. You might need to grab the psysh dev branch (or update dependencies yourself) to get it though?

**Comment by bobthecow** [comment]
This works great in v0.7.0. Upgrade :)

**Comment by condy0919** [comment]
thanks a lot :+1:

**Comment by bobthecow** [comment]
No problem.
