### ISSUE TITLE
Support short class name for class auto-completion

### ISSUE THREAD

**Issue by theofidry** [bobthecow/psysh#292]
When using the default PsySH shell (`v0.7`), if I try the tab auto-completion when having typed "R", I will get:
- `RuntimeException`
- `RangeException`
- `RecursiveIteratorIterator`

But if I have a service `Dummy/Run`, it won't appear... I guess it's because the classname matcher doesn't account for the class short names. It would be great if their could be a support for it!

Cheers

**Comment by theofidry** [comment]
I naively tried to change https://github.com/bobthecow/psysh/blob/master/src/Psy/TabCompletion/Matcher/ClassNamesMatcher.php#L45 for including short class names as well:

```php
array_filter(
                get_declared_classes(),
                function ($className) use ($quotedClass) {
                    $shortClassName = substr($className, strrpos($className, '\\') + 1);

                    $classNameMatch = AbstractMatcher::startsWith($quotedClass, $className);
                    $shortClassNameMatch = AbstractMatcher::startsWith($quotedClass, $shortClassName);

                    return $classNameMatch || $shortClassNameMatch;
                }
            )
```

But somehow psysh just becomes unresponsive after that :/

**Comment by bobthecow** [comment]
Unfortunately this isn't possible, due to limitations in readline. It strips out completions that don't match the current input, so even if we provide `Dummy\Run` as a completion for `Ru`, readline would refuse to show it :(
