### ISSUE TITLE
Drop PHP 5.3 Support

### ISSUE THREAD

**Issue by GrahamCampbell** [bobthecow/psysh#293]
Just wondering what you're feelings are about this right now?

**Comment by bobthecow** [comment]
I personally think everyone should be using PHP 7 at this point.

Some projects are plumbing, and some projects are porcelain. I see PsySH more as plumbing. And while it's awesome to have new high efficiency washing machines, and low flow shower heads, and fancy double-flush-volume toilets, it's not the plumbing's place to tell you that it's time to upgrade :)

PsySH needs to just work, wherever you put it. So until it's more of a pain than it's worth to support 5.3, or something comes along that can't be just as easily backwards compatible, I'm not inclined to drop it.

**Comment by GrahamCampbell** [comment]
Sure. ;)

**Comment by GrahamCampbell** [comment]
Maybe in like 5 years' time, we can bump psysh onto PHP 7 only? :P

**Comment by bobthecow** [comment]
:)

**Comment by Taluu** [comment]
I'd say 10 years. :trollface:
