### ISSUE TITLE
Configuring output colours?

### ISSUE THREAD

**Issue by nkmathew** [bobthecow/psysh#296]
Can't find documentation on this. Is it possible?

**Comment by bobthecow** [comment]
It's possible to disable them, but not to change what colors they are. Why do you ask?

**Comment by nkmathew** [comment]
The backgrounds for the error messages are quite glaring. Wouldn't mind just having simply a bold red foreground for errors.

![](http://i.imgur.com/lZUTBwj.png)

**Comment by bobthecow** [comment]
Yeah, if it's going to supply a background color, it should supply foreground as well :)
