### ISSUE TITLE
string assignment causes PHP Fatal error

### ISSUE THREAD

**Issue by condy0919** [bobthecow/psysh#297]
the output is 

Psy Shell v0.7.2 (PHP 7.0.5 — cli) by Justin Hileman

> > > $text = "hello"
> > > PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\VarDumper\Dumper\iconv_strlen() in phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Dumper/CliDumper.php:172
> > > Stack trace:
> > > # 0 phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Cloner/Data.php(179): Symfony\Component\VarDumper\Dumper\CliDumper->dumpString(Object(Symfony\Component\VarDumper\Cloner\Cursor), 'hello', false, 0)
> > > # 1 phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Cloner/Data.php(91): Symfony\Component\VarDumper\Cloner\Data->dumpItem(Object(Psy\VarDumper\Dumper), Object(Symfony\Component\VarDumper\Cloner\Cursor), Array, 'hello')
> > > # 2 phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Dumper/AbstractDumper.php(121): Symfony\Component\VarDumper\Cloner\Data->dump(Object(Psy\VarDumper\Dumper))
> > > # 3 phar:///usr/bin/psysh/src/Psy/VarDumper/Presenter.php(119): Symfony\Component\VarDumper\Dumper\AbstractDumper->dump(Object(Symfony\Component\VarDumper\Cloner\Data), Object(Closure))
> > > # 4 phar:///usr/bin/psysh/src/Psy/Shell.php(741): Psy\Va in phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Dumper/CliDumper.php on line 172

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\VarDumper\Dumper\iconv_strlen() in phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Dumper/CliDumper.php on line 172

Error: Call to undefined function Symfony\Component\VarDumper\Dumper\iconv_strlen() in phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Dumper/CliDumper.php on line 172

Call Stack:
    0.0010     380976   1. {main}() /usr/bin/psysh:0
    0.0209    1111736   2. Psy{closure}() /usr/bin/psysh:141
    0.1015    4094416   3. Psy\Shell->run() phar:///usr/bin/psysh/src/Psy/functions.php:208
    0.1044    4302000   4. Symfony\Component\Console\Application->run() phar:///usr/bin/psysh/src/Psy/Shell.php:273
    0.1047    4302864   5. Psy\Shell->doRun() phar:///usr/bin/psysh/build-vendor/symfony/console/Application.php:117
    0.1058    4302920   6. Psy\ExecutionLoop\ForkingLoop->run() phar:///usr/bin/psysh/src/Psy/Shell.php:307
    0.1063    4303264   7. Psy\ExecutionLoop\Loop->run() phar:///usr/bin/psysh/src/Psy/ExecutionLoop/ForkingLoop.php:79
    0.1067    4313272   8. Psy\ExecutionLoop{closure}() phar:///usr/bin/psysh/src/Psy/ExecutionLoop/Loop.php:135
    3.7883    4405872   9. Psy\Shell->writeReturnValue() phar:///usr/bin/psysh/src/Psy/ExecutionLoop/Loop.php:84
    3.7884    4405872  10. Psy\Shell->presentValue() phar:///usr/bin/psysh/src/Psy/Shell.php:632
    3.7884    4405872  11. Psy\VarDumper\Presenter->present() phar:///usr/bin/psysh/src/Psy/Shell.php:741
    3.7908    4450520  12. Symfony\Component\VarDumper\Dumper\AbstractDumper->dump() phar:///usr/bin/psysh/src/Psy/VarDumper/Presenter.php:119
    3.7909    4450144  13. Symfony\Component\VarDumper\Cloner\Data->dump() phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Dumper/AbstractDumper.php:121
    3.7914    4454488  14. Symfony\Component\VarDumper\Cloner\Data->dumpItem() phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Cloner/Data.php:91
    3.7914    4454520  15. Symfony\Component\VarDumper\Dumper\CliDumper->dumpString() phar:///usr/bin/psysh/build-vendor/symfony/var-dumper/Cloner/Data.php:179

**Comment by bobthecow** [comment]
It looks like the Symfony VarDumper component might be missing a dependency on the iconv polyfill. cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
We don't want to load the polyfill by default because it's a heavy one and iconv is really widespread and should be a default dependency (we have the same logic with e.g. the tokenizer extnsion).
If this policy, doesn't fit psysh's, then I'd recommend adding the iconv polyfill to psysh's composer.json file.

**Comment by bobthecow** [comment]
That seems entirely reasonable, but also leads to unexpected things like this. Should we add a suggested dependency on `ext-iconv`, with a message about how to install the polyfill then?

**Comment by bobthecow** [comment]
Though in this exact case, that wouldn't help, because this is the pre-packaged phar rather than a composer install. For that I suppose we could ship a polyfilled version of psysh. We definitely don't want to include it by default, since that increases the size of the phar by ~2.5x :-/

Are there any other assumed extensions that aren't declared? I'm more than happy to ship a bloated version along with the regular one just to make peoples' lives easier, I just need to know what to put in it :)

**Comment by nicolas-grekas** [comment]
AFAIK, iconv is the only polyfill in this case. Good to go with the big phar for me also.

**Comment by bobthecow** [comment]
The next release will include four versions of the phar: normal, "compat" (which includes polyfills for intl and readline), and php 5.3 versions of both. They'll be available via the repo's releases page.

**Comment by bobthecow** [comment]
Check out https://github.com/bobthecow/psysh/releases for the "compat" releases, which include the intl polyfill (and a bonus readline one as well).
