### ISSUE TITLE
How can I select which php version to use?

### ISSUE THREAD

**Issue by skuzye** [bobthecow/psysh#298]
Hi, I've been looking for a way to choose which php version so use but I couldn't so far. I'm using Archlinux and I installed php and php56 (from AUR). This means that I have 2 commands for php: /usr/bin/php and /usr/bin/php56 for versions 7 and 5.6 respectively.

I'm clearly missing something. Can someone please help?

**Comment by bobthecow** [comment]
You can just call psysh using the PHP version you want. If you're using the phar in pwd, it'd be something like this:

```
/path/to/php/version ./psysh
```

**Comment by skuzye** [comment]
I worked, thanks!
