### ISSUE TITLE
Chinese (Simplified) manual is gibberish in Windows 10 console

### ISSUE THREAD

**Issue by ejzhang** [bobthecow/psysh#299]
Like this:

> Description:
>   鐢ㄥ洖璋冨嚱鏁拌繃婊ゆ暟缁勪腑鐨勫崟鍏?

I tried to set 'useUnicode' => false in config.php like issues #270, but it's ineffectiveness.

**Comment by GrahamCampbell** [comment]
Have you got mb-string installed?

**Comment by ejzhang** [comment]
I was enabled extension=php_mbstring.dll in php.ini.

**Comment by bobthecow** [comment]
What happens if you run `chcp 65001` before starting PsySH?

**Comment by ejzhang** [comment]
It's still gibberish after chcp 65001, but it back to normal when scroll.
![psy](https://cloud.githubusercontent.com/assets/452491/14411028/d53dd3b8-ff6f-11e5-9a99-6b408bea5559.gif)

**Comment by ejzhang** [comment]
Sorry! It's problem of Windows.

**Comment by bobthecow** [comment]
I've never had much luck getting unicode to work on Windows. What happens if you launch cmd with the `/U` flag?

**Comment by bobthecow** [comment]
Added a [Troubleshooting section to the wiki with this](https://github.com/bobthecow/psysh/wiki/Troubleshooting).

Closing for now, but feel free to continue the conversation if you come up with anything better :)
