### ISSUE TITLE
It doesn't works: getting "???)??" and then exits

### ISSUE THREAD

**Issue by nikoskip** [bobthecow/psysh#306]
Hi,

I'm trying for first time to use PsySH but it doesn't working for me.

![image](https://cloud.githubusercontent.com/assets/1230033/15294093/d5d328f0-1b58-11e6-8a14-5c14fc8969a9.png)

I'm running PHP 5.3.29 on OSX "El Capitan".

**Comment by bobthecow** [comment]
Where did you get your PHP 5.3 on El Capitan?

**Comment by nikoskip** [comment]
I installed it using Brew.

**Comment by bobthecow** [comment]
Hmm. I haven't been able to sort this out yet. Something about the phar compilation doesn't play nice with PHP 5.3, or at least the default settings on OS X.

I'll keep digging, but in the meantime, the composer-based install works just fine :)

**Comment by nikoskip** [comment]
Thanks, I will try with Composer.

**Comment by nikoskip** [comment]
When I tried to install Composer, it complained about the `detect_unicode` setting:

![image](https://cloud.githubusercontent.com/assets/1230033/15558157/fac284ae-22a5-11e6-901c-4dcff841284d.png)

So, I set it to `Off` and now I can execute PsySH but I'm getting a syntax error. It's complaining about the array syntax.

```
PHP Parse error:  syntax error, unexpected '[', expecting ')' in phar:///usr/local/bin/psysh/build-vendor/nikic/php-parser/lib/PhpParser/ParserFactory.php on line 26
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/psysh:0
PHP   2. call_user_func:{/usr/local/bin/psysh:141}() /usr/local/bin/psysh:141
PHP   3. Psy\{closure}() /usr/local/bin/psysh:141
PHP   4. Psy\Shell->__construct() phar:///usr/local/bin/psysh/src/Psy/functions.php:169
PHP   5. Psy\Configuration->getCodeCleaner() phar:///usr/local/bin/psysh/src/Psy/Shell.php:74
PHP   6. Psy\CodeCleaner->__construct() phar:///usr/local/bin/psysh/src/Psy/Configuration.php:692
PHP   7. Psy\ParserFactory->createParser() phar:///usr/local/bin/psysh/src/Psy/CodeCleaner.php:59
PHP   8. Psy\ParserFactory->hasKindsSupport() phar:///usr/local/bin/psysh/src/Psy/ParserFactory.php:71
PHP   9. class_exists() phar:///usr/local/bin/psysh/src/Psy/ParserFactory.php:47
PHP  10. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/psysh/src/Psy/ParserFactory.php:47
PHP  11. Composer\Autoload\includeFile() phar:///usr/local/bin/psysh/build-vendor/composer/ClassLoader.php:301

Parse error: syntax error, unexpected '[', expecting ')' in phar:///usr/local/bin/psysh/build-vendor/nikic/php-parser/lib/PhpParser/ParserFactory.php on line 26

Call Stack:
    0.0079     669880   1. {main}() /usr/local/bin/psysh:0
    0.0158    2055128   2. call_user_func:{/usr/local/bin/psysh:141}() /usr/local/bin/psysh:141
    0.0158    2055128   3. Psy\{closure}() /usr/local/bin/psysh:141
    0.0201    2903208   4. Psy\Shell->__construct() phar:///usr/local/bin/psysh/src/Psy/functions.php:169
    0.0201    2903256   5. Psy\Configuration->getCodeCleaner() phar:///usr/local/bin/psysh/src/Psy/Shell.php:74
    0.0206    2961792   6. Psy\CodeCleaner->__construct() phar:///usr/local/bin/psysh/src/Psy/Configuration.php:692
    0.0209    2984880   7. Psy\ParserFactory->createParser() phar:///usr/local/bin/psysh/src/Psy/CodeCleaner.php:59
    0.0209    2984928   8. Psy\ParserFactory->hasKindsSupport() phar:///usr/local/bin/psysh/src/Psy/ParserFactory.php:71
    0.0209    2985064   9. class_exists() phar:///usr/local/bin/psysh/src/Psy/ParserFactory.php:47
    0.0209    2985424  10. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/psysh/src/Psy/ParserFactory.php:47
    0.0209    2985424  11. Composer\Autoload\includeFile() phar:///usr/local/bin/psysh/build-vendor/composer/ClassLoader.php:301
```

**Comment by DaGhostman** [comment]
@nikoakip that seems to be a problem with PHP 5.3, short array syntax is available in 5.4+.

I think this should be added as requirement in composer, @bobthecow thoughts?

**Comment by nikoskip** [comment]
@DaGhostman yes it's a problem with the array short array syntax. I will try with php-parser version 1, it seems that it's coded for running in PHP 5.3 >=.

**Comment by nikoskip** [comment]
So, I modified the php-parser dependency on the composer.json file to use version 1 and now is working.

**Comment by bobthecow** [comment]
You shouldn't need to modify the composer dependency, but if you're using the same install with different PHP versions you might get incompatible versions installed.

The next release will ship prebuilt phars specifically for php 5.3, though.

**Comment by bobthecow** [comment]
Check out https://github.com/bobthecow/psysh/releases for PHP 5.3 specific releases :)
