### ISSUE TITLE
Null bytes in string get truncated in output

### ISSUE THREAD

**Issue by MazeChaZer** [bobthecow/psysh#310]
```
$ psysh
>>> "\0\0\0\0"
=> "\x00" 
```

```
$ php -a
php > var_export("\0\0\0\0");
'' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . ''
```

I know that null bytes can be a problem because they terminate strings in C, but I don't know where to start looking for this bug.

**Comment by bobthecow** [comment]
Thank you for reporting. This is fixed in the dev branch and will go out in the next release.

**Comment by MazeChaZer** [comment]
Thanks!
