### ISSUE TITLE
PHAR version: Call to undefined method PhpParser\Node\Scalar\LNumber::parse()

### ISSUE THREAD

**Issue by squarefractal** [bobthecow/psysh#313]
# Introduction

Under certain circumstances, psysh will have trouble parsing statements such as `$q = $db->getNode(2000)`, giving up with the error:

	PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Scalar\LNumber::parse() in phar:///home/fractal/.bin/psysh/build-vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php:2401

This only affects the PHAR version of psysh and not with the composer-installed version. This bug seems to be only reproducible with a particular composer package; and I have been unable to come up with a smaller testcase that shows the problem; and so this report is a bit long.

# Prerequisities:

* An installation of [Neo4j](https://neo4j.com/download/)
* `composer require everyman/neo4jphp psy/psysh`
* PHAR version of psysh.

I'm using PHP-7 under Debian.

# Steps to reproduce:

Run the PHAR version of psysh, and type in:

	>>> require_once 'vendor/autoload.php'
	=> Composer\Autoload\ClassLoader {#166}
	>>> $db = new \Everyman\Neo4j\Client()
	=> Everyman\Neo4j\Client {#167}
	>>> $db->getTransport()->setAuth('neo4j', 'neo4j') # neo4j username, neo4j password
	=> Everyman\Neo4j\Transport\Curl {#171}
	>>> $q = $db->getNode(2000)
	PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Scalar\LNumber::parse() in phar:///home/fractal/.bin/psysh/build-vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php:2401
	Stack trace:
	#0 phar:///home/fractal/.bin/psysh/build-vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(244): PhpParser\Parser\Php7->reduceRule394()
	#1 phar:///home/fractal/.bin/psysh/src/Psy/CodeCleaner.php(158): PhpParser\ParserAbstract->parse('<?php $q = $db-...')
	#2 phar:///home/fractal/.bin/psysh/src/Psy/CodeCleaner.php(112): Psy\CodeCleaner->parse('<?php $q = $db-...', false)
	#3 phar:///home/fractal/.bin/psysh/src/Psy/Shell.php(483): Psy\CodeCleaner->clean(Array, false)
	#4 phar:///home/fractal/.bin/psysh/src/Psy/Shell.php(358): Psy\Shell->addCode('$q = $db->getNo...')
	#5 phar:///home/fractal/.bin/psysh/src/Psy/ExecutionLoop/Loop.php(70): Psy\Shell->getInput()
	#6 phar:///home/fractal/.bin/psysh/src/Psy/ExecutionLoop/Loop.php(135): Psy\ExecutionLoop\{closure}(Object(Psy\Shell))
	#7 phar:///home/fractal/.bin/psysh/src/Psy/E in phar:///home/fractal/.bin/psysh/build-vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php on line 2401

# Expected behaviour:

(that happens with the composer version of psysh)

	>>> $q = $db->getNode(2000)
	=> null

I'll be happy to provide any clarifications that may be needed.

**Comment by bobthecow** [comment]
I'm unable to reproduce this locally, but I can think of a few things to check:

* does your local `composer.json` share any dependencies with PsySH?
* what happens when you start up the PHAR version and just type `2000`?
* what happens when you start up the PHAR version, load `vendor/autoload.php` and type `2000`?
* what happens when you run the PHAR version from inside a script that has already loaded your autoloader?

```
<?php
require_once 'vendor/autoload.php';
require 'psysh';

eval(Psy\sh());
```

… can you reproduce now?

**Comment by squarefractal** [comment]
...and apparently, after downloading a new copy of the PHAR PsySH, I can't reproduce this either. Closing this issue.

Sorry for the trouble and the time wasted.

**Comment by bobthecow** [comment]
No worries. I'm glad you got it sorted :)
