### ISSUE TITLE
multiline comments break the parser

### ISSUE THREAD

**Issue by mfurlend** [bobthecow/psysh#315]
Often times I will write a class in an IDE, and then copy/paste it into psysh to test it out. Single-line comments are handled correctly (ignored), but multiline comments (such as those produced by PHPDoc blocks) break the parser.

Example:

```
>>> class TestClass {
...     /** @param array $array
PHP Parse error: Unterminated comment on line 2
>>>
```

**Comment by bobthecow** [comment]
Thank you for reporting. This has been fixed in the development branch and will go out in the next release!
