### ISSUE TITLE
Show code inside closure

### ISSUE THREAD

**Issue by still-dreaming-1** [bobthecow/psysh#318]
It would be awesome to be able to show the code inside a closure. Using some php magic I am able to write my php classes javascript style where I add "methods" to objects on the fly and then return a copy of that object instead of constructing new ones. But these methods are actually just properties that are closures. Using that technique, if psysh could show me the code inside a closure, I could develop and test entire classes inside psysh. I could redefine the methods to fix bugs. When I want to save it to a source file after some coding, I could do:

`show $my_class`

And have it show all the "methods" that I just wrote inside that class.

**Comment by bobthecow** [comment]
That sounds kind of insane. But if you want to take a shot at it, I'm happy to review pull requests and make suggestions :)

**Comment by still-dreaming-1** [comment]
> That sounds kind of insane
That is good news! When I sound insane it usually means I am onto something great. Also, any sufficiently innovative idea is almost by definition going to sound insane to the majority of people. Anyway, I agree the exact way of developing I described sounds pretty annoying, and I'm sure it would also lead to performance issues for at least some versions of PHP, if not all of them. But I think it could be incorporated into very helpful tools. It would be nice to get more of a "live" feel when programming in PHP. Perhaps a REPL could be integrated into an editor or IDE in such a way that the REPL is executing code at the same time you edit your code in a source file. This may at times involve redefining a method in the REPL, which could be emulated by replacing methods with closures and then reassigning the closure variable. Alternatively, the REPL could start over to avoid naming collisions from redefining a method, but that could have performance issues. Of course all that is beside the point.

As far as how to show the code inside the closure, the only thing I can think of is grab it from a file. So as it is being typed into the REPL, it could be saved to a file, or at least something that gets registered as one, and then the file could be run as the REPL's way of executing the code. Then reflection could tell you which file it is from and show you the source code from it.

It does sound interesting to attempt myself. Right now I'm pretty maxed out on projects... Maybe some day.
