### ISSUE TITLE
psysh prints the php hashbang when used as library

### ISSUE THREAD

**Issue by epeli** [bobthecow/psysh#320]
In the script at https://git.io/psysh the first line is `#!/usr/bin/env php` which is cool when psysh is used as a script directly.

But when it's required for wp-cli for example the hashbang is printed to the stdout which breaks some of my scripts using wp-cli.

Example:

I have following configuration for wp-cli in `$HOME/.wp-cli/config.yml`

``` yaml
require:
  - /usr/local/bin/psysh
```

To be able to use `wp shell` with psysh easily. But then I have script checking wp version and now `wp core version` prints:

```
#!/usr/bin/env php
4.6
```

instead of just

```
4.6
```

Which obviously breaks things.

**Comment by bobthecow** [comment]
This is a limitation of PHP, unfortunately. I would recommend installing a copy of PsySH via composer, and requiring the composer autoload in your wp-cli config.

**Comment by andreiglingeanu** [comment]
I managed this thing by building small commands I use everytime, they are constructed like this:

`wp-path`
```bash
wp eval 'echo ABSPATH;' | tail -n 1
```

Not very pretty, but it works for me.
