### ISSUE TITLE
how can I use as a composer script?

### ISSUE THREAD

**Issue by yozman** [bobthecow/psysh#328]
#I already install `psysh` use `composer`
```json
{
  ...
  "config": {
    "process-timeout": 0
  },
  "require": {
    ...
    "psy/psysh": "0.7.*",
    ...
  },
  "scripts": {
    "fly": "vendor/bin/psysh"
  }
  ...
}
```

It's works when I run `./vendor/bin/psysh`
but when I use as composer script
run `composer fly`
it will auto exit
the output is like this
```shell
> vendor/bin/psysh
Psy Shell v0.7.2 (PHP 7.0.9 - cli) by Justin Hileman

Exit: Ctrl+D
```

could you please tell me
how can I use `psysh`
as a composer script
like `composer fly`?

**Comment by bobthecow** [comment]
I don't know much about composer scripts, but it looks like it's running command line executables in a non-interactive subshell or something. [Defining a PHP callback-style script](https://getcomposer.org/doc/articles/scripts.md#defining-scripts) works great, though:

```php
namespace MyVendor;

class Scripts {
    public static function psysh() {
        eval(Psy\sh());
    }
}
```

```json
{
    ...
    "require": {
        "psy/psysh": "^0.7.2",
        ...
    },
    "scripts": {
        "fly": "MyVendor\\Scripts::psysh"
    }
}
```

**Comment by bobthecow** [comment]
Closing, as this is an issue with Composer, not PsySH. See composer/composer#5856 😄
