### ISSUE TITLE
How to invoke command `wherami` after start

### ISSUE THREAD

**Issue by piotr-galas** [bobthecow/psysh#329]
I use psysh for debugging and it would be nice to see breakepoint. 
You provide `whereami` command but i want to invoke it just after psysh start.
Is it possible?

**Comment by hashar** [comment]
Maybe inject the command to the input?
```php
$shell = new \Psy\Shell();
$shell->addInput('whereami');
$shell->run();
```

That seems to do the trick for me.

**Comment by piotr-galas** [comment]
Thank you very much @hashar.  
Your solution work , but it is difficult to  implement. 
When I invoke debugger like you describe i am in  wrong place, somewhere in vendor.

I use this library by putting `eval(\Psy\sh());`  When I put it in code,the  `Shell::debug` method is invoked. To achieve my goal I just dirty put `$shell->addInput('whereami');` to vendor. Dirty, but it work.

Btw.
 I came from rails community, where similar debugger is used by everybody. I don't understand why don't authors improve this library to be more user friendly.  If you debug you always want to put environment on console. I can create PR with this, but I am afraid that authors don't want it. 
I wait an answer almost 3 months.

**Comment by hashar** [comment]
Psysh is mostly a single person effort (90% of commits) and it is working reasonably well for most users.

You can't really compare to rails which is a full framework, that has been going for years and is probably the de facto standard framework for ruby web development. There is a lot more of effort being put into it.

In PHP world, maybe Symfony or Zend frameworks have their own equivalents.

As to why authors "don't improve" Psy, it is OpenSource so really the users most of the time ends up being the authors.  If there are only few patches being send to improve it, either Psy does not have much interested or it is working fine enough for almost everyone :]

There are other tools to interact/debug a PHP software such as XDebug XHProf which have integration in Eclipse/IntelliJ/PhpStorm.  A click to set a breakpoint, run, step in the interactive console done :]

**Comment by piotr-galas** [comment]
@hashar you are right. I think it is better tool then XDEbug and setiing breakpoints in IDE.
In my opinion it is not comparable. With this great tool you can change or invoke everything you want in the fly. I complained because nobody answer me 3 months. I know that it is open source, and people spend private time to improve it. 

Thanks one more time.

**Comment by bobthecow** [comment]
Thanks for the feature request. This will now happen by default for any `Psy\Shell::debug()` or `eval(Psy\sh())` calls. 

It might be worth adding a config setting to suppress this, but mebbe we'll wait until someone complains :P

**Comment by bobthecow** [comment]
It's in the `develop` branch and will go out with the next stable release.
