### ISSUE TITLE
Rebuild phar?  PHP 7.1 bug in symfony/var-dumper

### ISSUE THREAD

**Issue by yuloh** [bobthecow/psysh#330]
When using the PHAR on PHP 7.1 any command outputs this notice:

```php
Psy Shell v0.7.2 (PHP 7.1.0RC6 — cli) by Justin Hileman
>>> echo 'hi'
hi⏎
PHP Notice:  A non well formed numeric value encountered in phar:///usr/local/bin/psysh/build-vendor/symfony/var-dumper/Cloner/VarCloner.php on line 298
```

It's caused by [a bug in symfony/var-dumper](https://github.com/symfony/symfony/commit/37b299bb3ea4af1f624ff51666e25b8de2de6ee8) which was fixed, but I guess the PHAR was compiled before it was fixed.

**Comment by bobthecow** [comment]
I've been waiting on the 3.x stable release of PHP Parser for full PHP 7.1 support, so I haven't cut a release yet. It's on beta 3, so hopefully it'll be out any day now?

In the meantime, it's pretty easy to build the phar yourself to pull in the latest var-dumper.

**Comment by GrahamCampbell** [comment]
develop branch is ready now :)

**Comment by bobthecow** [comment]
I'm working on a release now :)

**Comment by yuloh** [comment]
Thanks everyone, new release looks great 👍 👍

**Comment by bobthecow** [comment]
The fancy new automatic release build stuff I had set up on CI timed out, so I'll get the prebuilt phar released… hopefully tonight?
