### ISSUE TITLE
psysh acts as a console for codeigniter

### ISSUE THREAD

**Issue by lufeihaidao** [bobthecow/psysh#332]
In ci2, running `php -d auto_prepend_file=index.php -a` will works like a ruby on rails console. How to implement it with psysh?

I tried to add index.php in config file but got failed.

**Comment by bobthecow** [comment]
You should be able to run `psysh index.php`, but I've never used it so I don't know for sure.

**Comment by bobthecow** [comment]
Were you able to get this sorted out?

**Comment by lufeihaidao** [comment]
@bobthecow Not yet, sorry...
