### ISSUE TITLE
PHP Notice:  Undefined index: end inTabCompletion\AutoCompleter.php on line 55

### ISSUE THREAD

**Issue by asolopovas** [bobthecow/psysh#333]
Hi I am using Win10x64 with php7.1 ReadLine enabled but getting no auto completion as it throws the error.

**Comment by bobthecow** [comment]
Try again with v0.8.0? (released approximately 30 seconds after you opened this issue 😛)

**Comment by asolopovas** [comment]
Tried same thing

**Comment by bobthecow** [comment]
Okay. Thank you for reporting. I'll take a look at it this evening.

**Comment by bobthecow** [comment]
@asolopovas Sorry about the delay! I haven't been able to reproduce, and I was waiting to get my Windows VM to behave again so I could check there… Odds of that happening any time soon are kinda slim. Do you mind doing some remote debugging in the meantime?

Just paste in the result of running `readline_info()` inside psysh?

**Comment by asolopovas** [comment]
@bobthecow Sorry for delay as well, I don't mind just let me know what should I do. Currently `readline_info()` returns 
```
[
     "line_buffer" => "",
     "point" => 15,
     "readline_name" => "",
     "attempted_completion_over" => 0,
]
```

**Comment by bobthecow** [comment]
That's not nearly enough info :-/

Does `Psy\info()` work for you?

**Comment by asolopovas** [comment]
PHP error:  Cannot instantiate interface Psy\VersionUpdater\Checker in C:\vhosts\3oakdb\vendor\psy\psysh\src\Psy\functions.php on line 56

**Comment by bobthecow** [comment]
Oh, that was a bug in the last version of psysh. Update to the latest release and try again?

**Comment by asolopovas** [comment]
```
Psy Shell v0.8.2 (PHP 7.1.0 — cli) by Justin Hileman
>>> Psy\info()
PHP error:  Undefined index: library_version in C:\vhosts\3oakdb\vendor\psy\psysh\src\Psy\functions.php on line 89
```

**Comment by bobthecow** [comment]
Oh, yeah. That won't work. I just pushed a change to develop which should help with the output. But it doesn't help with your strangely missing readline info :(

**Comment by jens1o** [comment]
I still have this problem with the latest release.

**Comment by bobthecow** [comment]
@jens1o can you show me the output of `\Psy\info()`?

**Comment by jens1o** [comment]
Of course, here you go @bobthecow 

```
array(12) {
  'PsySH version' =>
  string(6) "v0.8.5"
  'PHP version' =>
  string(5) "7.1.5"
  'default includes' =>
  array(0) {
  }
  'require semicolons' =>
  bool(false)
  'error logging level' =>
  int(32767)
  'config file' =>
  array(3) {
    'default config file' =>
    string(46) "C:/Users/Jens/AppData/Roaming/PsySH/config.php"
    'local config file' =>
    NULL
    'PSYSH_CONFIG env' =>
    bool(false)
  }
  'updates' =>
  array(4) {
    'update available' =>
   bool(false)
    'latest release version' =>
    string(6) "v0.8.5"
    'update check interval' =>
    string(6) "weekly"
    'update cache file' =>
    string(53) "C:/Users/Jens/AppData/Roaming/PsySH/update_check.json"
  }
  'pcntl' =>
  array(2) {
    'pcntl available' =>
    bool(false)
    'posix available' =>
    bool(false)
  }
  'readline' =>
  array(3) {
    'readline available' =>
    bool(true)
    'readline enabled' =>
    bool(true)
    'readline service' =>
    string(20) "Psy\Readline\Libedit"
  }
  'history' =>
  array(3) {
    'history file' =>
    string(49) "C:/Users/Jens/AppData/Roaming/PsySH/psysh_history"
    'history size' =>
    NULL
    'erase duplicates' =>
    NULL
  }
  'docs' =>
  array(4) {
    'manual db file' =>
    string(53) "C:/Users/Jens/AppData/Roaming/PsySH/php_manual.sqlite"
    'sqlite available' =>
    bool(true)
    'db schema' =>
    string(5) "1.0.0"
    'db built at' =>
    string(31) "Sun, 22 Mar 2015 05:16:50 +0000"
  }
  'autocomplete' =>
  array(2) {
    'tab completion enabled' =>
    bool(true)
    'custom matchers' =>
    array(0) {
    }
  }
}

**Comment by bobthecow** [comment]
Thanks! And now the output of `readline_info()`?

**Comment by jens1o** [comment]
```
[
     "line_buffer" => "",
     "point" => 15,
     "readline_name" => "",
     "attempted_completion_over" => 0,
]
```

**Comment by bobthecow** [comment]
That's really strange. It knows you're 15 characters into the line, but doesn't show us the actual line. I don't think we're going to be able to do autocomplete with whatever is going on here. For comparison, here's `readline_info()` on a well-behaved system:

```
=> [
     "line_buffer" => "readline_info()",
     "point" => 15,
     "end" => 15,
     "mark" => 0,
     "done" => 1,
     "pending_input" => 0,
     "prompt" => ">>> ",
     "terminal_name" => "xterm-256color",
     "library_version" => "7.0",
     "readline_name" => "other",
     "attempted_completion_over" => 0,
   ]
```

We could probably make it work without `end`, `mark`, `done`, and `pending_input`, if it at least provided `line_buffer`.

Sorry, I don't know what to do here other than disable tab completion on systems like this :(

**Comment by jens1o** [comment]
Okay, thanks for your effort :)

**Comment by bobthecow** [comment]
Okay. I just pushed a fix for the exception, and a workaround that should actually provide _some_ autocomplete results for you now. They won't be amazing, so no promises :)

Do you mind giving the `develop` branch a spin?

**Comment by jens1o** [comment]
Yes, I do. Give me some minutes. :)

**Comment by jens1o** [comment]
Wow. This works absolutly. Love it  ❤️ 

Thanks!

When's the next release? 😋

**Comment by bobthecow** [comment]
Soon 😄
