### ISSUE TITLE
git.io/psysh serves version 0.7.2

### ISSUE THREAD

**Issue by squarefractal** [bobthecow/psysh#338]
This is kinda unimportant, but the link featured on the homepage, https://git.io/psysh apparently serves version 0.7.2 instead of 0.8.0.

**Comment by bobthecow** [comment]
Yep. The automatic build via CI failed, so I'll have to upload a manual build. I'm planning on taking care of that this weekend.

**Comment by dereckson** [comment]
https://raw.githubusercontent.com/bobthecow/psysh/gh-pages/psysh still contains the 0.7.2 version

**Comment by bobthecow** [comment]
Sorry about the delay. The version on psysh.org has been updated.
