### ISSUE TITLE
Use statement grouping is not supported

### ISSUE THREAD

**Issue by squarefractal** [bobthecow/psysh#340]
PHP 7 introduced a feature where you could group use statements of the form:

	use A\B;
	use A\C;
	use A\D\E;

like so:

	use A\{B, C, D\E};

which does not work in psysh:

	>>> use Symfony\Component\Yaml\{Yaml, Exception\ParseException}
	=> null
	>>> Yaml::parse('foo: bar')
	PHP Fatal error:  Class 'Yaml' not found in eval()'d code on line 1
	>>> use Symfony\Component\Yaml\Yaml
	=> null
	>>> Yaml::parse('foo: bar')
	=> [
	     "foo" => "bar",
	   ]

**Comment by bobthecow** [comment]
Thanks for reporting! This has been fixed in the `develop` branch, and will go out in the next release. In the meantime, feel free to test out the dev branch and let me know if it's not working as you'd expect :)

**Comment by squarefractal** [comment]
Works as expected, closing issue.
