### ISSUE TITLE
psysh\bin called from script using passthru makes no-op

### ISSUE THREAD

**Issue by davidsosavaldes** [bobthecow/psysh#343]
It's possible to execute psysh shell inside script that's called with passthru?

**Comment by bobthecow** [comment]
`passthru` is probably the wrong approach to use PsySH. I won't go as far as saying it's unsupported, but I doubt it'll ever work cleanly. A better approach would be to either execute `psysh` and pass your app's bootstrap file as an include, or write a custom wrapper that programmatically starts the `Psy\Shell` inside your app's environment.

From bcit-ci/CodeIgniter4#367 it looks like you're moving away from `passthru` anyway, so should we close this issue?
