### ISSUE TITLE
Not working with PHP >= 7.1

### ISSUE THREAD

**Issue by bukowskiadam** [bobthecow/psysh#345]
```
eval(\Psy\sh());
```
won't work with PHP >= 7.1, because now you can't reassign `$this`.

Code below causes error
```
<?php
extract(array('this' =>'xxx'));
```
https://3v4l.org/YFMcj

**Comment by Charl13** [comment]
I have the same problem.

**Comment by bobthecow** [comment]
Thanks for reporting! There should be a fix for this in `develop` now. Do you mind giving it a spin to make sure it solves your problems?

**Comment by bukowskiadam** [comment]
Working like a charm. :+1:

Should I close the issue right now or you'll close it after merging to master?

**Comment by bobthecow** [comment]
Thanks. I'll close the issue (or rather, it'll close itself) when this is merged into master.

**Comment by Charl13** [comment]
Works for me on 7.1.0 :+1:
