### ISSUE TITLE
Fatal error when inheriting final class not handled by PsySH

### ISSUE THREAD

**Issue by squarefractal** [bobthecow/psysh#349]
When I try to extend a final class, PsySH automatically exits without handling the error:

    >>> class TransitionFunction extends Closure {}
    Fatal error: Class TransitionFunction may not inherit from final class (Closure) in phar:///data/data/com.termux/files/home/psysh/src/Psy/ExecutionLoop/Loop.php(80) : eval()'d code on line 3
    $ # exits to shell prompt

PsySH should be able to handle this error like other errors.

This is on PHP 7.1.1,

**Comment by bobthecow** [comment]
If you have pctnl installed / enabled, it does handle this (though not as gracefully as some other issues).

**Comment by bobthecow** [comment]
This has been fixed in `develop` and will go out in the next stable release. Thanks for reporting!
