### ISSUE TITLE
Is it possible to execute inline php script without dropping to shell?

### ISSUE THREAD

**Issue by rawaludin** [bobthecow/psysh#350]
In my app (Laravel), sometimes I just want to drop to psy shell to generate Authorization key. This easily done using one line command. Something like this:

````
❯ php artisan tinker
Psy Shell v0.7.2 (PHP 7.0.7 — cli) by Justin Hileman
>>> app('Tymon\JWTAuth\JWTAuth')->attempt(['email' => '2light.hidayah@gmail.com', 'password' => 'sup3rs3cr3t!@#'])
=> "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjUsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdCIsImlhdCI6MTQ4NjE5NDc2NCwiZXhwIjoxNDg2MzM4NzY0LCJuYmYiOjE0ODYxOTQ3NjQsImp0aSI6ImMzOTZjNDFlZmM0YzlkNzEzMmIyN2I4YzRhODFkZjIxIn0.g4dOmJ9V1-NwsH1N9HFy5BVXiDDKWIYyMbU6NUNEIv8"
>>>
````

Then I copied the result. 

Is it possible to make the command as paramater and get result as output? This way, I could pipe it to another program like `pbcopy`.

Maybe something like this:

```
php artisan tinker << "my command" | pbcopy
```

**Comment by bobthecow** [comment]
psysh just reads from stdin, so it's possible to do something like this:

```bash
echo '42' | psysh | pbcopy
```

… but this does bring along a lot of other baggage. Ideally if input comes from stdin we'd suppress the prompt, and if stdout is being piped somewhere, we'd suppress all the other stuff, and just show the eval result.

**Comment by bobthecow** [comment]
This just landed in the develop branch :) 

<img width="762" alt="Screen Shot 2019-04-07 at 9 27 00 PM" src="https://user-images.githubusercontent.com/53660/55698715-0f5bc500-597c-11e9-9541-5fdb39c0a407.png">

<img width="762" alt="Screen Shot 2019-04-07 at 9 27 09 PM" src="https://user-images.githubusercontent.com/53660/55698718-1551a600-597c-11e9-8095-38f33fc328d4.png">

**Comment by ahinkle** [comment]
@bobthecow Hey, awesome work. I was trying to accomplish this recently with an extension idea. Looking for a way to execute tinker with a one liner. Any ideas how to get this within Artisan?

**Comment by bobthecow** [comment]
It might just work, once you’re running the next PsySH release? The `-r` flag wouldn’t, but the rest of the changes are about making it do the right thing when getting input from stdin rather than interactively.
