### ISSUE TITLE
Support for global scope

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#353]
It would be great if there was a way to set the shell to use the global scope (for debugging legacy applications which heavily rely on global configuration). `Shell::setScopeVariables()` can load the values from the global scope, but does not actually give access to it.

Downstream patch where this came up: https://gerrit.wikimedia.org/r/#/c/334217/

**Comment by bobthecow** [comment]
If we're going to add a feature like this, the config option should be called `register_globals` :trollface: 

Seriously, this is kind of horribad. I understand the reasoning, but I'm reluctant to make this a configurable feature for PsySH. I wouldn't want to legitimize it in any way by adding a config option for it :)

That said, it's totally possible, and it's not nearly as awful as #354 would be.

All you need is a code cleaner pass:

```php
class MyCodeAbusesGlobals extends \Psy\CodeCleaner\CodeCleanerPass
{
    private static $superglobals = array(
        'GLOBALS', '_SERVER', '_ENV', '_FILES', '_COOKIE', '_POST', '_GET', '_SESSION'
    );

    public function beforeTraverse(array $nodes)
    {
        $names = array();
        foreach (array_diff(array_keys($GLOBALS), self::$superglobals) as $name) {
            array_push($names, new \PhpParser\Node\Expr\Variable($name));
        }

        array_unshift($nodes, new \PhpParser\Node\Stmt\Global_($names));

        return $nodes;
    }
}
```

… then, where you call `new \Psy\Shell`, do a slightly more complicated dance:

```php
$traverser = new \PhpParser\NodeTraverser();
$codeCleaner = new \Psy\CodeCleaner(null, null, $traverser);

// add this after initializing the code cleaner so all the default passes get added first
$traverser->addVisitor(new MyCodeAbusesGlobals());

$config = new \Psy\Configuration(array(
    'codeCleaner' => $codeCleaner,
));

$shell = new \Psy\Shell($config);
$shell->run();
```

… and you're set!

<img width="762" alt="screen shot 2017-02-08 at 8 30 18 am" src="https://cloud.githubusercontent.com/assets/53660/22747064/c9955e82-edda-11e6-8121-9f19cb44e01f.png">

[globaltest.php gist](https://gist.github.com/bobthecow/da8d425e7c00ee3473e1049380f70d07)

**Comment by hashar** [comment]
@bobthecow I can't believe you got as far as providing a screenshot reflecting our context.  Kudos!   Would we be able to incorporate your code above in MediaWiki which is licensed under GPL 2+?  We would of course gives proper attribution !

**Comment by bobthecow** [comment]
i copy/pasted just the bit i actually needed to test this. see the gist :)

sure! you can use that code.

**Comment by hashar** [comment]
I have integrated your code to what will hopefully become the MediaWiki shell command ( https://gerrit.wikimedia.org/r/#/c/334217/4 ).  Thank you, you have been a huge time saver!

**Comment by tgr** [comment]
Awesome, thanks a lot for looking into it!

If I understand correctly, this is not a perfect simulation of global scope, as newly created variables won't be global, and global variables defined by some method called from the shell won't become visible. As far as I can see that would not be relevant for the MediaWiki use case though as all globals should be declared up front in the initialization step before `Psy\Shell` is invoked.

I suppose this can be closed as declined then? (I much prefer doing it outside the PsySH codebase as well, I just assumed there is no way to do it without modifying the loop code, which is not subclassing-friendly.)

**Comment by bobthecow** [comment]
> If I understand correctly, this is not a perfect simulation of global scope
 
Correct, it's not actually global scope, but is pretty close. All global variables will always be visible and usable as soon as they're declared, as this code cleaner pass runs every time code is executed. In my screenshot / example, `$wgReadOnly` was defined before the shell started running, but `$wgReadOnlyFile` was only declared when I ran `wfConfiguredReadOnlyReason`. Both of them ended up as real globals, available in local scope.

The one difference between this and actually running the REPL in global scope is that newly created variables inside the local scope won't automatically become globals, but if you run `global $foo` before you assign something to that, `$foo` will be a real global, just like all the others.

I feel like this is a fine compromise, and is actually preferable, as it lets you work with a legacy codebase that Does Things Wrong, but doesn't encourage you to continue doing the Wrong stuff yourself :)

**Comment by bobthecow** [comment]
Also, I don't have a Gerrit account, and am not going to set one up for a comment this trivial, but with this code cleaner you shouldn't need (and shouldn't use) `$shell->setScopeVariables( $GLOBALS );` anymore.

**Comment by hashar** [comment]
Hi @bobthecow , we recently had a conversation about the origin of MediaWiki interactive shell which made me refers to this task for the historical perspective.  Thank you for all the help you provided us five years ago on dealing with `$GLOBALS`!

**Comment by bobthecow** [comment]
Thank you for the comment, it means a lot to get feedback like this 🙂
