### ISSUE TITLE
Run commands on startup?

### ISSUE THREAD

**Issue by calebporzio** [bobthecow/psysh#362]
Here is my use case:

I often find myself hand-writing (with tab completion but still...) namespaced classes like so:
```php
>>> App\Models\User::first();
```

I want to be able to write this without manually writing `use` or `namespace` statements. 

```php
>>> User::first();
```

I've tried auto-including a file that contains the `use` statement, but because of the nature of php includes, the namespace and use won't bleed into the REPL, it will only be usable within the file.

If anybody knows of a way to achieve my goal - please let me know.

I think it would also be handy to have something like a psysh_rc - similar to a .bach_rc where you can automatically run through commands

Thanks!
- Caleb

**Comment by damiankloip** [comment]
If it helps, I do something which I think should help you out for my drush (Drupal) setup - creating aliases for each entity/model:

```php
foreach ($em->getDefinitions() as $entity_type) {
  $class = $entity_type->getClass();
  class_alias($class, (new \ReflectionClass($class))->getShortName());
}

```

that gets the class name only from the namespace, but simplified, if you just wanted to create aliases you can just do:

```php
class_alias($class, $alias);
```

and include that file in your psysh config file (`~/.config/psysh/config.php`):

```php
$config['defaultIncludes'][] = 'path/to/your/include';
```

More info at http://psysh.org/#configure . See the `defaultIncludes` documentation there.

**Comment by calebporzio** [comment]
Thanks @damiankloip ! I'm going to give that a whirl, that could be just what I'm looking for!

**Comment by calebporzio** [comment]
In case anyone is interested, here is my implementation:

My use case was specifically for "Model" classes in the Laravel framework.

```php
$finder = new \Symfony\Component\Finder\Finder();
$finder->files()->name('*.php')->in(base_path().'/app');

foreach ($finder as $file) {
    $namespace = 'App\\';

    if ($relativePath = $file->getRelativePath()) {
        $namespace .= strtr($relativePath, '/', '\\') . '\\';
    }

    $class = $namespace . $file->getBasename('.php');

    try {
        $r = new \ReflectionClass($class);

        if ($r->isSubclassOf('Illuminate\\Database\\Eloquent\\Model')) {
            class_alias($class, $file->getBasename('.php'));
        }
    } catch (Exception $e) {
        //
    }
}
```

**Comment by bobthecow** [comment]
Cool. I'm going to close this for now. Feel free to reopen if you have any additional issues.
