### ISSUE TITLE
Disable check for update

### ISSUE THREAD

**Issue by REBELinBLUE** [bobthecow/psysh#364]
Is there a way to disable the update check when you launch psysh? Can't find any mention in the documentation

At work we unfortunately have to use a proxy and although the `HTTP_PROXY` environment variables are set psysh doesn't pick them up so it sits trying to see if there is an update for 60 seconds each launch

**Comment by REBELinBLUE** [comment]
Well, I am an idiot, just found the option from looking through the source. Not sure how I missed it in the readme. Sorry about that

Possibly worth mentioning that it isn't on http://psysh.org/#configure

**Comment by bobthecow** [comment]
Oh, youre right. I really need to start automatically generating that so we don't have to manually keep it in sync.

**Comment by REBELinBLUE** [comment]
👍
