### ISSUE TITLE
installing without ssh access? (FTP only)

### ISSUE THREAD

**Issue by nekromoff** [bobthecow/psysh#366]
Is it possiblle to install and use psysh, when FTP only access is available? If so, how?

**Comment by bobthecow** [comment]
To install it, you can [grab the latest release](https://github.com/bobthecow/psysh/releases/latest) and just copy the Phar file over. 

I don't think you'll be able to use it without command line access, though. Did you have a specific use case in mind?

**Comment by nekromoff** [comment]
Yes, I was thinking about using it for running composer and artisan that I
am otherwise unable to run without SSH on the shared hosting. Is that a
valid use case?

**Comment by bobthecow** [comment]
I'm afraid not. PsySH is an interactive PHP session that runs from the command line, much like Composer and Artisan themselves do — sharing a lot of the same code, in fact!

If you can't run Composer or Artisan, then PsySH isn't going to help.

**Comment by nekromoff** [comment]
OK, thanks for the effort anyway!
