### ISSUE TITLE
Read the `.user.ini` in the current directory

### ISSUE THREAD

**Issue by CMCDragonkai** [bobthecow/psysh#370]
The `.user.ini` can be used to quickly set INI settings on a per-project/directory basis. Would be great if psysh read these files.

Maybe a combination of http://php.net/manual/en/function.ini-set.php and http://php.net/manual/en/function.parse-ini-file.php can be used?

**Comment by zonuexe** [comment]
See http://psysh.org/#user-local-config-files 

You can write code to explore and load `.user.ini` on `~/.config/psysh/config.php`.

**Comment by zonuexe** [comment]
@CMCDragonkai 

Perhaps the following code will recursively search `.user.ini`:

```php
/** @return string|false */
$search_user_ini = function ($dir) use (&$search_user_ini) {
    $dir =  rtrim($dir, DIRECTORY_SEPARATOR);
    if (is_dir($dir)) {
        $ini_file_name = $dir . DIRECTORY_SEPARATOR . '.user.ini';

        if (is_file($ini_file_name)) {
            return $ini_file_name;
        }

        $parent_dir = pathinfo($dir, PATHINFO_DIRNAME);

        if ($dir === $parent_dir) {
            return false;
        }

        return $search_user_ini($parent_dir);
    }

    return false;
};

$ini_path = $search_user_ini(getcwd());
if ($ini_path !== false) {
    $conf = parse_ini_file($ini_path);
    // ...
}
```

**Comment by bobthecow** [comment]
This has been added to the shiny new manual :)

https://github.com/bobthecow/psysh/wiki/Configuration#per-project-phpini-files

**Comment by CMCDragonkai** [comment]
Should that wiki be suggesting `.user.ini` not `.php.ini`?

**Comment by bobthecow** [comment]
Oh, good call. Fixing :)
