### ISSUE TITLE
Make it possible to search for function, class and method names.

### ISSUE THREAD

**Issue by cholthi** [bobthecow/psysh#371]
sometimes, after discovering a function maybe from manual or any source like SO, I quickly run it in the repl, but over time I forget the exact function names, this is particularly true for functions provided by extensions. So if there is a way for PsySH to allow us to interactively search for function or class names like the way `composer require vendor/package` does it.

perhaps sort of `doc search "function/method/class"`

**Comment by bobthecow** [comment]
i usually use `ls --classes --grep X` (and `--functions`, etc) to find function, class and method names. it accepts regex or just substring for the `--grep` argument.

**Comment by cholthi** [comment]
cute. could you please elaborate more on --grep usages

**Comment by bobthecow** [comment]
```
>>> ls -l --functions --grep array_s

Functions:
  array_search   function array_search($needle, $haystack, $strict = unknown)
  array_shift    function array_shift(&$stack)
  array_slice    function array_slice($arg, $offset, $length = unknown, $preserve_keys = unknown)
  array_splice   function array_splice(&$arg, $offset, $length = unknown, $replacement = unknown)
  array_sum      function array_sum($arg)
```

Yeah, it feels like "find a thing that i vaguely know what is" belongs in `ls`, and "read documentation" belongs in `doc`. If we did add a way to search for docs, it'd be inconsistent between "docs from the PHP manual" vs "docs for values in current context" vs "docs for userland code". I can't even think of how we'd make the latter two work in ways that aren't surprising.

And if you _did_ search, say for `doc search array` and it found 69 functions and classes would it … show the docs for all of them? Probably not. It would list out what you just found, so you could decide which to show docs for. So let's keep things simple and just use `ls` for that :)
