### ISSUE TITLE
Revert to a saner `wtf` command

### ISSUE THREAD

**Issue by supriyo-biswas** [bobthecow/psysh#372]
With PsySH 0.8.4, the behaviour of wtf has become very irritating to say the least. There's no indication of how many ?/!s one has to add to get the full stack trace, and having to remember it (after finding it by sheer luck) is no fun either.

Seriously, this isn't any fun; I've wasted hours figuring out why all my code was giving out shallow stack traces out of the blue.

I'd suggest something along the lines of:

```
>>> function z() { throw new RuntimeException; }
>>> function y() { z(); }
>>> function x() { y(); }
>>> wtf
RuntimeException with message ''
--
0:  () at vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(90) : eval()'d code:3
1:  z() at vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(90) : eval()'d code:3
2:  y() at vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(90) : eval()'d code:3
3:  x() at vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(90) : eval()'d code:1
4: eval() at vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php:90

[For more of the stack trace, use wtf ??]

>>> wtf ??
RuntimeException with message ''

<<Print the full stack trace>>
```

(If this is too much trouble, I can deal with the previous version of `wtf`.)

**Comment by bobthecow** [comment]
The previous version of `wtf` was a regression which caused it to print the stack trace several times :)

`wtf -a` will always show the full backtrace. Does that work for you?

**Comment by bobthecow** [comment]
How's this?

<img width="906" alt="screen shot 2017-05-16 at 7 26 05 am" src="https://cloud.githubusercontent.com/assets/53660/26111135/23cee10a-3a09-11e7-9fee-9449adc5a23f.png">

With this change, it always shows three lines by default. It gives you a hint (and the number of additional lines) if it suppresses any. And if it would only cut off a couple of lines, it just shows them all rather than saying "to see 1 more" or "to see 2 more".

**Comment by supriyo-biswas** [comment]
That's so much better, thanks for getting to this so quick!

(As an aside, I've always wanted to thank you for this awesome tool. It's what made me extremely productive with PHP and saved me countless hours, and has deepened my understanding of PHP in a way no other resource has done.)
