### ISSUE TITLE
CTRL-D triggers repeated insertion of ">>>"

### ISSUE THREAD

**Issue by benglass** [bobthecow/psysh#38]
Great project, love the idea of being able to inspect the state of my code from an interactive REPL.

I noticed in the REPL when I hit CTRL-D to terminate it inserts the string ">>>" over and over again until I hit CTRL-C to exit. Clearly I can use CTRL-C to exit but this seems like unwanted behavior. Possibly its from my terminal but i figured I'd post it here in case its not.

**Comment by avindra** [comment]
Can confirm that installing the readline extension fixes the issue. It is infinitely better now.

@bobthecow: Can you include a note on the main website, or even better, in the command line itself if readline is not installed? It's not clear that readline is really needed for proper functionality.

**Comment by bobthecow** [comment]
How 'bout we just fix it, instead? ;)
