### ISSUE TITLE
Error: Cannot re-assign $this with Laravel 

### ISSUE THREAD

**Issue by daggeto** [bobthecow/psysh#381]
Hi, i'm using Laravel 5.2. I added ` eval(\Psy\sh());` to code. When running tests i get this : 
```
Error: Cannot re-assign $this

/home/vagrant/Projects/ali/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php:62
/home/vagrant/Projects/ali/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php:135
/home/vagrant/Projects/ali/vendor/psy/psysh/src/Psy/ExecutionLoop/ForkingLoop.php:79
/home/vagrant/Projects/ali/vendor/psy/psysh/src/Psy/Shell.php:307
/home/vagrant/Projects/ali/vendor/symfony/console/Application.php:117
/home/vagrant/Projects/ali/vendor/psy/psysh/src/Psy/Shell.php:273
/home/vagrant/Projects/ali/vendor/psy/psysh/src/Psy/Shell.php:141
```

**Comment by bobthecow** [comment]
Yep! This is fixed. Unfortunately Laravel 5.2 is pinned to an older version of PsySH, and they probably won't cut a new release. So your options are:

1. Upgrade to Laravel 5.4
2. Downgrade to an older PHP version that doesn't throw this error
3. Call `\Psy\Shell::debug`, passing args manually, and don't pass a `$this` argument, to keep PsySH from esploding (this should theoretically work, though i haven't actually tried it)
4. Some Composer shenanigans to convince it to let you install a different version of PsySH (it should be backwards compatible, just not allowed by the Laravel composer dependencies)
5. Upgrade to Laravel 5.4 (pick this option!)

**Comment by GrahamCampbell** [comment]
Yeh, Laravel 5.2 is not supported anymore. I'd recommend getting on to php 7.1 and Laravel 5.4 asap. Laravel 5.5 will be out soon too. Also, the newer laravel versions don't have a hard dependency on psysh to avoid just this issue, so you can upgrade that component, without Laravel having to maintain it's BC, and without it forcing php parser on people.
