### ISSUE TITLE
array_multisort() results in fatal error in psysh

### ISSUE THREAD

**Issue by ramsey** [bobthecow/psysh#385]
When using `array_multisort()` in psysh, I receive a fatal error about variables being passed by reference. I am storing values to variables before I pass them into `array_multisort()`, and the same code behaves as expected when run from a script.

(Note, this code was taken from one of the [php-src array_multisort() tests](https://github.com/php/php-src/blob/master/ext/standard/tests/array/array_multisort_natural_incase.phpt).)

## Expected behavior illustrated from a script

<details>
    <summary>Click to expand array-multisort.php</summary>

``` php
<?php
$a = array(
    'Second',
    'First.1',
    'First.2',
    'First.3',
    'Twentieth',
    'Tenth',
    'Third',
);

$b = array(
    '2 a',
    '1 bb 1',
    '1 bB 2',
    '1 BB 3',
    '20 c',
    '10 d',
    '3 e',
);

array_multisort($b, SORT_NATURAL | SORT_FLAG_CASE, $a);

var_dump($a, $b);
```
</details>

<details>
    <summary>Click to expand output from array-multisort.php</summary>

```
$ php array-multisort.php
/Users/ramsey/Desktop/array-multisort.php:24:
array(7) {
  [0] =>
  string(7) "First.1"
  [1] =>
  string(7) "First.2"
  [2] =>
  string(7) "First.3"
  [3] =>
  string(6) "Second"
  [4] =>
  string(5) "Third"
  [5] =>
  string(5) "Tenth"
  [6] =>
  string(9) "Twentieth"
}
/Users/ramsey/Desktop/array-multisort.php:24:
array(7) {
  [0] =>
  string(6) "1 bb 1"
  [1] =>
  string(6) "1 bB 2"
  [2] =>
  string(6) "1 BB 3"
  [3] =>
  string(3) "2 a"
  [4] =>
  string(3) "3 e"
  [5] =>
  string(4) "10 d"
  [6] =>
  string(4) "20 c"
}
```
</details>

## Actual behavior seen in psysh

When using the same code in psysh, I received the following fatal error:

```
PHP Fatal error:  Only variables can be passed by reference in eval()'d code on line 1
```

<details>
    <summary>Click to expand psysh session showing behavior</summary>

```
$ psysh
Psy Shell v0.8.6 (PHP 7.1.3 — cli) by Justin Hileman
>>> $a = array(
...     'Second',
...     'First.1',
...     'First.2',
...     'First.3',
...     'Twentieth',
...     'Tenth',
...     'Third',
... );
=> [
     "Second",
     "First.1",
     "First.2",
     "First.3",
     "Twentieth",
     "Tenth",
     "Third",
   ]
>>> $b = array(
...     '2 a',
...     '1 bb 1',
...     '1 bB 2',
...     '1 BB 3',
...     '20 c',
...     '10 d',
...     '3 e',
... );
=> [
     "2 a",
     "1 bb 1",
     "1 bB 2",
     "1 BB 3",
     "20 c",
     "10 d",
     "3 e",
   ]
>>> array_multisort($b, SORT_NATURAL | SORT_FLAG_CASE, $a);
PHP Fatal error:  Only variables can be passed by reference in eval()'d code on line 1
>>> var_dump($a, $b);
phar:///Users/ramsey/bin/psysh/src/Psy/ExecutionLoop/Loop.php(90) : eval()'d code:1:
array(7) {
  [0] =>
  string(6) "Second"
  [1] =>
  string(7) "First.1"
  [2] =>
  string(7) "First.2"
  [3] =>
  string(7) "First.3"
  [4] =>
  string(9) "Twentieth"
  [5] =>
  string(5) "Tenth"
  [6] =>
  string(5) "Third"
}
phar:///Users/ramsey/bin/psysh/src/Psy/ExecutionLoop/Loop.php(90) : eval()'d code:1:
array(7) {
  [0] =>
  string(3) "2 a"
  [1] =>
  string(6) "1 bb 1"
  [2] =>
  string(6) "1 bB 2"
  [3] =>
  string(6) "1 BB 3"
  [4] =>
  string(4) "20 c"
  [5] =>
  string(4) "10 d"
  [6] =>
  string(3) "3 e"
}
=> null
>>>
```
</details>

**Comment by bobthecow** [comment]
Oh. Yeah. I bet I know why this is happening. 

It prolly works if you just pass `$b, $a`, right?

**Comment by ramsey** [comment]
Yes!

**Comment by bobthecow** [comment]
Sigh. This is why you don't design languages where core code and extensions can implement APIs that wouldn't be possible in userland code.

Per PHP docs, the signature for `array_multisort` is…

```
bool array_multisort ( array &$array1 [, mixed $array1_sort_order = SORT_ASC [, mixed $array1_sort_flags = SORT_REGULAR [, mixed $... ]]] )
```

… but if you ask `\ReflectionFunction`, the interface is…

```
bool array_multisort ( array &$arr1, mixed $&sort_order, mixed &$sort_flags [, mixed &$...] )
```

So when trying to save you from yourself, psysh correctly(?) prevents you from passing things to the second and third argument which can't be passed by reference. But `\ReflectionFunction` is lying.

The only way I can see to handle this is to add a blacklist of core / extension functions and methods where we can't get their correct signature via reflection.

**Comment by ramsey** [comment]
Reflection telling you that sort order and flags are by reference would appear to be a bug, to me. I reported a similar Reflection bug recently. I'll look at bugs.php.net when I get a chance to see if it's reported.

**Comment by bobthecow** [comment]
It's not, really. It's that Reflection is incapable of describing the actual API for this function:

```
bool array_multisort(array &$arr1, array &$arr2)
bool array_multisort(array &$arr1, int $sort_order, array &$arr2, int $sort_order2)
bool array_multisort(array &$arr1, int $sort_order, int $sort_flags, array &$arr2, int $sort_order2, int $sort_flags2)
bool array_multisort(array &$arr1, int $sort_order, int $sort_flags, array &$arr2, array &$arr3)
```

You can't tell whether a given argument will be passed by reference without knowing the values for all the preceding arguments. Hence,

> This is why you don't design languages where core code and extensions can implement APIs that wouldn't be possible in userland code.

😕

**Comment by bobthecow** [comment]
Good news! I went through all the functions in `get_defined_functions` in PHP 7.1.5 and it looks like `array_multisort` is the only one with this class of problem.

**Comment by bobthecow** [comment]
This has been fixed in the `develop` branch. It'll go out in the next release.

<img width="757" alt="screen shot 2017-06-18 at 2 08 07 pm" src="https://user-images.githubusercontent.com/53660/27264275-fb141276-542f-11e7-814c-789ac313f2df.png">

Thanks for reporting the issue!

**Comment by ramsey** [comment]
:thumbsup:
