### ISSUE TITLE
GUI similar to R-studio / Rodeo / Spyder

### ISSUE THREAD

**Issue by kanihal** [bobthecow/psysh#386]
I think, It would be awesome to create GUI for psysh similar that of Rodeo/Spyder for ipython (or R-Studio for R language)

Basically it should have 
- An editor window
- console window running psysh
- (ctrl+Enter) with cursor on any line should run that line in psysh console
- ?functionname : should show the manual/doc entry for that function in the console window
- variable viewer 
- history viewer

Attaching figures for reference:

![rodeo-overview](https://user-images.githubusercontent.com/7579686/27407690-0bbb0264-56f7-11e7-996f-53815cd92df9.png)
![spyder-windows-screenshot](https://user-images.githubusercontent.com/7579686/27407720-2800f514-56f7-11e7-8e93-7985b99927e8.png)
![rstudio-screenshot](https://user-images.githubusercontent.com/7579686/27407735-3addace0-56f7-11e7-9eb6-5748ae68bb26.png)

Would love hear comments about this idea. good? bad? meh?

I am not very well versed with gui development, If somebody would point me in the right direction, I am willing put in some time to work on this.

**Comment by bobthecow** [comment]
There's already a PsySH kernel for Jupyter, the language agnostic IPython successor: https://github.com/Litipk/Jupyter-PHP

As for Rodeo or RStudio, they're both fairly focused on data, plotting, visualizations, etc. Most of their features wouldn't really make sense with PHP, let alone with PsySH. Are there specific features from these that you'd like to see in a PsySH-aware GUI?

**Comment by kanihal** [comment]
I understand that there is no requirement for plotting/visualization for php.  What I want is an ide like gui with text editor, variable viewer with an INTERPRETED console.

**Comment by zonuexe** [comment]
That sounds good.  It is wonderful to add an interface to PsySH to work with such an IDE.
[Spyder IDE](https://github.com/spyder-ide) looks like a good product, but I do not know if it is a polyglot.

**Comment by kanihal** [comment]
Instead of having to build gui from bottom up, Is it possible to build a plugin which integrates psysh interpretive console for "phpstorm" (which already has good autocompletion and variable viewer for php)?
I don't it is even possible or not. Just wondering.

**Comment by zonuexe** [comment]
I am not familiar with IntelliJ IDEA/PhpStorm, so I do not know.
PhpStorm plug-in that integrates  and PsySH [does not yet exist](https://plugins.jetbrains.com/search/phpstorm?search=psysh), so it would be great if it was released.

**Comment by bobthecow** [comment]
Closing. User Jupyter, linked above :)
