### ISSUE TITLE
Possible to debug state of a running application being requested via HTTP

### ISSUE THREAD

**Issue by benglass** [bobthecow/psysh#39]
I am curious if there is a way or plans to support the ability to use the Debug functionality and have it triggered from an HTTP request to your application.

For example I want to be able to visit http://www.myapp.com in my browser (or event via a curl request/wget from the terminal would be fine) and still take advantage of the Debug functionality where I can explore he state of my app.

This would be similar to xdebug functionality minus the step debugging.

**Comment by Markcial** [comment]
Hi, i saw an open issue on the symfony component for this, would be nice, is there any PR started on this, should i start from scracth? is there anyone who had tried something with that? thanks

**Comment by bobthecow** [comment]
Closing this one in favor of #505 since they're substantially similar.
