### ISSUE TITLE
Add support for editing current command line in external editor

### ISSUE THREAD

**Issue by hackel** [bobthecow/psysh#392]
Often I find myself editing long, multi-line commands, and it would be really convenient to be able to just press a key and edit it in my editor (vim).  Ideally this would work just like the edit-and-execute-command in bash (ctrl-x ctrl-e).  Since psysh is already using readline (as is bash), hopefully it won't be difficult to port.  http://git.savannah.gnu.org/cgit/bash.git/tree/bashline.c#n944

**Comment by bobthecow** [comment]
Unfortunately I don't think we have access to readline in that way… the PHP implementations of readline are almost an afterthought :(

**Comment by krageon** [comment]
I can look into adding the required functions as a patch to the php readline plugin.

**Comment by krageon** [comment]
The referenced PR adds editing external files inline using whatever EDITOR your environment has. If/when I see that the PHP maintainers are accepting of changes to the readline extension, I will see if I can get some hotkey support.

**Comment by bobthecow** [comment]
I'm going to close this for now. Feel free to reopen if/when PHP readline support is improved enough to do it with a hotkey :)
