### ISSUE TITLE
Per project configuration not loaded on windows

### ISSUE THREAD

**Issue by underdpt** [bobthecow/psysh#393]
Hi,

I'm trying to use a `.psysh.php` configuration file on my project and It's not being loaded.

I found the problem to be on [Configuration.php#L186](https://github.com/bobthecow/psysh/blob/master/src/Psy/Configuration.php#L186):

```php
        $localConfig = getenv('PWD') . '/.psysh.php';
``` 

`getenv('PWD')` doesn't works on windows, as there's no `PWD` environment variable. Changing it to:

```php
        $localConfig = getcwd() . '/.psysh.php';
```

works, but I'm not sure this won't break using PWD environment variable from linux. 

I would suggest using `getenv('PWD')` unless it returns false, then using `getcwd()`:

```php
        $pwd = getenv('PWD') ?: getcwd();
        $localConfig = $pwd . '/.psysh.php';
```

**Comment by bobthecow** [comment]
Oh, good catch. `getcwd()` is completely portable. We should be using that here (like we do everywhere else in our code).

This has been fixed in the dev branch, and will go out with the next release. Thank you!
