### ISSUE TITLE
No support for goto

### ISSUE THREAD

**Issue by jens1o** [bobthecow/psysh#394]
When using:
```
Psy Shell v0.8.9 (PHP 7.1.7 — cli) by Justin Hilemanan
How are you doing sir? c:
>>> label: echo 'Hello World';
Hello World⏎��
>>> goto label;
PHP Fatal error:  'goto' to undefined label 'label' in C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code o
n line 1

Fatal error: 'goto' to undefined label 'label' in C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code on lin
e 1
```

I get a fatal error :/

btw, is there any issue where control characters aren't ignored?

**Comment by GrahamCampbell** [comment]
Meh. Not sure we should add support for goto tbh.

**Comment by zonuexe** [comment]
I think it is unexpected that `goto` causes a fatal error.  I will submit PR.

**Comment by bobthecow** [comment]
For things like this, my rule of thumb is that we shouldn't be _less_ useful than `php -a`. Looks like we meet that bar already 😄 

<img width="762" alt="screen shot 2017-07-07 at 5 12 51 pm" src="https://user-images.githubusercontent.com/53660/27980821-93a82cf0-6337-11e7-88a6-6fc9a74bfa61.png">

**Comment by jens1o** [comment]
But may I ask why you even fail in a fatal error, while it's a valid expression? Are gotos not supported in shells? 😭

**Comment by bobthecow** [comment]
Every input in a REPL is an eval, and gotos aren't supported between eval calls. Because what would that even do?

**Comment by jens1o** [comment]
It would save the gotos, and once we're jumping to one, we remember what was defined as that label, and then execute the code?

**Comment by GrahamCampbell** [comment]
Why though. What uses case is there for that?

**Comment by jens1o** [comment]
I planned to save a shortcut on the steps I do to validate everything(minify/compile scss, compile js) and so on. That's why I wanted to use labels which executes them repeatly. :/

**Comment by bobthecow** [comment]
use history replay!

in a REPL / eval context, goto doesn't really make sense because there's no previous execution to go back to. we could probably fake it by trying to replay history back to where the label was, but it gets complicated in all but the most trivial cases. we'd have to deal with rewriting part or all of the command containing the label (for example, if you `goto` a label inside a complicated if statement or something. 

but!

you can view, filter, search and replay your history using the `hist` command. check it out and see if it meets your needs :)

**Comment by jens1o** [comment]
The commands don't work for me, that's why I didn't used them...
![image](https://user-images.githubusercontent.com/11234139/27991708-928a7e38-647f-11e7-9568-346b2c538f48.png)

**Comment by jens1o** [comment]
History reply comes up with
```
>>> history replay
RuntimeException with message 'Too many arguments, expected arguments "command".'
```

**Comment by bobthecow** [comment]
Keeping them here is fine :)

Can you run `\Psy\info()` and paste the result?

**Comment by jens1o** [comment]
```
=> [
     "PsySH version" => "v0.8.9",
     "PHP version" => "7.1.7",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => "C:/Users/Jens/AppData/Roaming/PsySH/config.php",
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "updates" => [
       "update available" => false,
       "latest release version" => "v0.8.9",
       "update check interval" => "never",
       "update cache file" => "C:/Users/Jens/AppData/Roaming/PsySH/update_check.json",
     ],
     "pcntl" => [
       "pcntl available" => false,
       "posix available" => false,
     ],
     "readline" => [
       "readline available" => true,
       "readline enabled" => true,
       "readline service" => "Psy\Readline\Libedit",
     ],
     "history" => [
       "history file" => "C:/Users/Jens/AppData/Roaming/PsySH/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => "C:/Users/Jens/AppData/Roaming/PsySH/php_manual.sqlite",
       "sqlite available" => true,
       "db schema" => "1.0.0",
       "db built at" => "Sun, 22 Mar 2015 05:16:50 +0000",
     ],
     "autocomplete" => [
       "tab completion enabled" => true,
       "custom matchers" => [],
     ],
   ]
```

**Comment by bobthecow** [comment]
Do you mind looking at the history file listed above and seeing whether (1) it exists and (2) it has anything in it?

**Comment by jens1o** [comment]
Both are true, it exists and it has 200 lines.

**Comment by bobthecow** [comment]
if you're up for a bit more debugging…

```php
$hist = file_get_contents("C:/Users/Jens/AppData/Roaming/PsySH/psysh_history");

// confirm that it successfully opened

$rows = explode("\n", $hist);

// confirm that it exploded

array_shift($rows)

// tell me what that line output is 👆
```

**Comment by bobthecow** [comment]
Oh, completely unrelated, but you can drop the "Load and merge local config" bit from your config file. PsySH does that by default now.

**Comment by jens1o** [comment]
Okay, thanks. I'll do that steps.

**Comment by jens1o** [comment]
The line output is `ls` @bobthecow

**Comment by bobthecow** [comment]
I think I know the issue. There should be a magic line at the top of every readline and libedit history file that is just `_HiStOrY_V2_`. Somehow yours is missing this, which means the history command doesn't read it thinking it's not a valid history file. 

The number of ways PHP manages to screw up readline implementation never ceases to amaze me 😕

What kind of PHP are you running? And can you send the output of `readline_info()`?

**Comment by jens1o** [comment]
@bobthecow 
```php
array(4) {
  'line_buffer' =>
  string(0) ""
  'point' =>
  int(25)
  'readline_name' =>
  string(0) ""
  'attempted_completion_over' =>
  int(0)
}
```

**Comment by bobthecow** [comment]
Sorry. By "kind" I meant where did you get it? WAMP, or official Windows binaries, or cygwin or that crazy embedded Ubuntu thing, or something else entirely?

**Comment by jens1o** [comment]
Official Windows Binaries, I update it myself once there is a new version.
