### ISSUE TITLE
Update php_manual.sqlite

### ISSUE THREAD

**Issue by jens1o** [bobthecow/psysh#396]
May you please update your documentation file, because php 7.2 is right to come with new features and new, improved documentation? The latest build is more than 2 years old :/

**Comment by bobthecow** [comment]
Oh wow. I didn't realize it had been that long.

You're absolutely right. I've got an incomplete update to the manual build process that I've been meaning to finish, but since it's been so long, I should release an updated version using the old build process in the meantime.

**Comment by jens1o** [comment]
Maybe you set up a cronjob or manually do that before each release?

**Comment by bobthecow** [comment]
The process is a bit manual right now, and kind of a pain, which was part of the reason for the rewrite I mentioned :)

**Comment by bobthecow** [comment]
The manual files have been updated :)

**Comment by jens1o** [comment]
Thanks!

**Comment by jens1o** [comment]
But I wonder why the files are smaller? The actual manual is 7mb, and the previous one was 9,5mb big?

**Comment by bobthecow** [comment]
Good question. I'd guess that a bunch of stuff related to older PHP 5.x versions was removed?

But I can take a look and see if there are any glaring omissions when I get a minute.

**Comment by bobthecow** [comment]
Yeah, at a glance nothing seems really off. It added ~300 new doc entries (like ReflectionGenerator) and removed ~300 doc entries (like HttpRequest and friends).

**Comment by bobthecow** [comment]
If you iterate through each entry in the manual and write it to disk, you end up with almost exactly the same amount of disk space. I'm guessing the majority of the difference is in the sqlite driver / version used to generate it?

```
$ du -s *docs 
79640	newdocs
79704	olddocs
```

**Comment by bobthecow** [comment]
I did realize that the manual builder script wasn't handling namespaced classes, though, so I just updated it and rebuilt them all. So you prolly want to download the updated manual anyway :)

**Comment by jens1o** [comment]
Okay, thanks for your investigation. :)

**Comment by jens1o** [comment]
Err... I can't find them. It looks like you reset the repo a few commits but forgot to push your new manuals. :/

**Comment by bobthecow** [comment]
I did push them (and verified by downloading). Where were you trying to download them from?

**Comment by bobthecow** [comment]
I've pushed another build with some improvements on the last, as well.

The english manual is back up to 9.1mb :)

**Comment by jens1o** [comment]
Fine, thanks, now it's working!
