### ISSUE TITLE
Bug with float and locale "fr_FR"

### ISSUE THREAD

**Issue by drasill** [bobthecow/psysh#398]
This bug may occur with all locales which uses a comma instead of a dot, when casting float to strings.

It looks like the float is casted to string before being parsed:

```
> setlocale(LC_NUMERIC, 'fr_FR.utf8');
=> "fr_FR.utf8"
>>> 5.4
PHP Parse error:  syntax error, unexpected ',' in src/Psy/ExecutionLoop/Loop.php(90) : eval()'d code on line 1
```

Another 'funny' example :

```
>>> setlocale(LC_NUMERIC, 'en_US.utf8');
=> "en_US.utf8"
>>> ['a' => 'foo', 'b' => 5.4]
=> [
     "a" => "foo",
     "b" => 5.4,
   ]
>>> setlocale(LC_NUMERIC, 'fr_FR.utf8');
=> "fr_FR.utf8"
>>> ['a' => 'foo', 'b' => 5.4]
=> [
     "a" => "foo",
     "b" => 5,
     0 => 4000000000000004,
   ]
>>>
```

**Comment by bobthecow** [comment]
Thanks for reporting this! It's an issue with an underlying library, but I've added a workaround to the `develop` branch. Do you mind checking it out and making sure things work as you'd expect?

**Comment by drasill** [comment]
Hi, thank you for your fast answer.

I still have the same bug on the `develop` branch :

```
# On develop branch
Psy Shell v0.8.9 (PHP 5.6.30-1~dotdeb+7.1 — cli) by Justin Hileman
>>> [5.4]
=> [
     5,
     4000000000000004,
   ]
>>> (float)'5.4'
=> 5,4.0
>>> 5.4
PHP Parse error:  syntax error, unexpected ',' in /tmp/psysh/src/Psy/ExecutionLoop/Loop.php(90) : eval()'d code on line 1
```

(I cloned the repo, checked out `develop`, and exec `composer install`, maybe I'm missing something ?)

**Comment by bobthecow** [comment]
Hmm. Is `en_US` not available on your machine? Try changing `'en_US'` [here](https://github.com/bobthecow/psysh/blob/develop/src/Psy/CodeCleaner.php#L132), [here](https://github.com/bobthecow/psysh/blob/develop/src/Psy/VarDumper/Presenter.php#L53) and [here](https://github.com/bobthecow/psysh/blob/develop/src/Psy/VarDumper/Presenter.php#L120) to `'C'`?

**Comment by drasill** [comment]
Oh, indeed, I didn't think about that.

It's working with the locale `C`.
I don't have `en_US`, but I have `en_US.utf8` (it's a docker container).
And as such, it's also working with the locale `en_US.utf8`.

But I guess you should use `C` and not suppose the presence of a locale on the system.

Thanks again !

**Comment by bobthecow** [comment]
Okay. Now it's using `C` :)
