### ISSUE TITLE
Error not output correctly

### ISSUE THREAD

**Issue by wwulfric** [bobthecow/psysh#407]
php71

```php
$a = [];
$a[2];
```

will output `PHP error:  Undefined offset: 2 on line 1` however it's a notice and `php -a` will output `PHP Notice:  Undefined offset: 2 in php shell code on line 1`

**Comment by bobthecow** [comment]
PsySH was matching the output for errors on some older PHP version, but it's prolly time for an upgrade. Pushing changes to match `php -a` in 7.x :)
