### ISSUE TITLE
`global` keyword does work 

### ISSUE THREAD

**Issue by coderkd10** [bobthecow/psysh#408]
Supposedly php's `global` keyword does not work.
If a variable is defined outside the scope of a class and a class's method tries to access it by declaring it global it does not work and the variable remains empty.

**Comment by bobthecow** [comment]
It kind of works :)

Can you post a specific example that fails?

**Comment by andreiglingeanu** [comment]
It kind of worked for me too sometimes and sometimes it didn't. I don't have a proper explanation for it too :)

**Comment by coderkd10** [comment]
sorry for replying so late. Here's a very simple test case:

```php
<?php
	// FILE : global_test.php
	$NAME = "kedia";

	class Test {
		public function __constuct() {
		}
		public function greet() {
			global $NAME;
			return "Hello $NAME\n";
		}
	}

	function testFun() {
		global $NAME;
		return "Hello $NAME\n";
	}

	function main() {
		$t = new Test();

		echo "Running class : \n";
		echo $t->greet();
		echo "------------------\n";

		echo "Running Function : \n";
		echo testFun();
		echo "-------------------\n";

	}

	main();
?>
```

When run using the normal `php` cli we get the following :

```sh
$ php global_test.php
Running class :
Hello kedia
------------------
Running Function :
Hello kedia
-------------------
```
which is as we would expect.
But when run using `psysh`  (or including the file and running `main`) we get:

```sh
$ psysh global_test.php
Psy Shell v0.8.2 (PHP 5.6.30 — cli) by Justin Hileman
New version is available (current: v0.8.2, latest: v0.8.11)
Running class :
Hello
------------------
Running Function :
Hello
-------------------
>>>
``` 

from which it is clearly that global variable `$NAME` has not been used inside the class / function context.

Also I haven't updated `psysh` for a while (I'm running v0.8.2) so it might be because of that too. I'll try and update and report back.

**Comment by coderkd10** [comment]
ok I updated to the latest version (v0.8.11) and I get the same output.

**Comment by bobthecow** [comment]
Hmm. Yeah, I can see why that would fail.

You run into the same thing with PHP's interactive shell (or with just running things from a file) if you make the `require` call inside a closure (which is what PsySH is doing):

```
php > $foo = function () { require 'global_test.php'; };
php > $foo();
```

Other than not wrapping the execution inside a closure, which is bad for a whole host of other reasons, I can't see an easy way to fix this.

**Comment by bobthecow** [comment]
I've looked into it a bit more, and I don't have any clever fixes. Feel free to reopen if you have any ideas, but unfortunately i'm going to have to "wontfix" for now :(
