### ISSUE TITLE
Help with PHP functions

### ISSUE THREAD

**Issue by matheusfaustino** [bobthecow/psysh#409]
Hello guys, I'd like to thank you for this awesome package, very cool.
I'd like to know, if there is a way to get help (maybe some examples too) for PHP functions.
I was testing something with DateTime::createFromFormat and I had a doubt about a parameter and it will be useful if there is something like this. 

What do you think?

Thanks in advance.

**Comment by bobthecow** [comment]
`doc DateTime::createFromFormat` :)

**Comment by matheusfaustino** [comment]
Unbelievable… Thank you very much.

**Comment by bobthecow** [comment]
No problem! :)
