### ISSUE TITLE
automatic semicolon insertion

### ISSUE THREAD

**Issue by Zauberfisch** [bobthecow/psysh#41]
the statement "does automatic semicolon insertion" is not entirely true.

```
>>> 'foo'
=> "foo"
>>> if (true) { echo 'bar' }
PHP Parse error: Syntax error, unexpected '}', expecting ',' or ';' on line 1
>>> if (true) {
... echo 'foobar'
... }
PHP Parse error: Syntax error, unexpected '}', expecting ',' or ';' on line 3
```

as you can see, semicolon "insertion" in fact only appends to the end of an expression (meaning the if including the echo inside).  
a more correct statement/documentation would be to call it semicolon appendage at the end of line/expression/block.

**Comment by bobthecow** [comment]
Closing because that's no longer in the documentation (and hasn't been for a long time 😛).
