### ISSUE TITLE
short list with missing index gives notice

### ISSUE THREAD

**Issue by greg0ire** [bobthecow/psysh#414]
# Sample input

```php
[,$a, $b] = [1,2,3];
```

# Error message

> PHP Notice:  Trying to get property of non-object in phar:///home/gparis/bin/psysh/src/Psy/CodeCleaner/FunctionReturnInWriteContextPass.php on line 56

# Things that do work as expected

- `list(,$a, $b) = [1,2,3]`
- `[$a, $b,] = [1,2,3]`

Using Psy Shell v0.8.9 (PHP 7.1.4-1+deb.sury.org~yakkety+1 — cli)

**Comment by bobthecow** [comment]
Thank you for reporting this. It's been fixed in the `develop` branch and will go out in the next release.
