### ISSUE TITLE
FR: Provide no suggestions for `__construct`, `__wakeup`...

### ISSUE THREAD

**Issue by jens1o** [bobthecow/psysh#419]
Because it is not intended to do so, but psysh still suggests its usage. :/

**Comment by bobthecow** [comment]
:+1:

**Comment by jens1o** [comment]
May I take over that request and file a pr?

**Comment by bobthecow** [comment]
Absolutely. Pull requests are always welcome :)

**Comment by bobthecow** [comment]
Thanks again for the fix :)
