### ISSUE TITLE
Does psysh check for updates on every run?

### ISSUE THREAD

**Issue by SimonEast** [bobthecow/psysh#422]
I've noticed that when running psysh on my laptop on unstable internet connections (such as travelling on the train), psysh can sometimes take 10-15seconds to launch. I'm wondering if this is because it's checking online for updates. How often is this set to occur?

**Comment by bobthecow** [comment]
By default it checks weekly. You can override it by setting `updateCheck` to `"monthly"` or `"never"` in your PsySH config.

But we really should have a faster timeout than 10+ seconds. I'll limit the update check request to 3 seconds for now.

**Comment by bobthecow** [comment]
Okay, this should be much better after `b2df62d `. Thanks for reporting!
