### ISSUE TITLE
Powershell: `echo PHP_VERSION`'s output ends with weird characters.

### ISSUE THREAD

**Issue by jens1o** [bobthecow/psysh#426]
Having `echo PHP_VERSION`:
![image](https://user-images.githubusercontent.com/11234139/30784371-4be6e9fa-a154-11e7-84f7-fe6cbd366e37.png)
Having `echo PHP_VERSION . PHP_EOL`:
![image](https://user-images.githubusercontent.com/11234139/30784381-5bddfaf6-a154-11e7-86dd-c61c81ebd6c9.png)

I'd propose to automatically append `PHP_EOL` instead of weird characters.

**Comment by bobthecow** [comment]
See #69 for more discussion on this.

**Comment by jens1o** [comment]
thanks :)
