### ISSUE TITLE
No prompt (“>>>”) is displayed on Win10

### ISSUE THREAD

**Issue by zhekaus** [bobthecow/psysh#428]
If I run psysh inside GitBash or Cygwin, no prompt (">>>") is displayed. Arrows up&down doesn’t list the history. However, other things seemingly work.
There is no such a problem with cmd.exe. However, it sacrifices the colorful output.

Win10, Psy Shell v0.8.11 (PHP 7.1.10 — cli)

**Comment by bobthecow** [comment]
Can you paste the output of `Psy\info()`?

Shell history requires `readline`, and I believe this isn’t available in PHP under Windows. It can be installed in Cygwin, but might require a `—with-readline` flag? 

The prompt should be showing up, though. I’ll take a look at that.

**Comment by zhekaus** [comment]
Psy\info()
=> [
     "PsySH version" => "v0.8.11",
     "PHP version" => "7.1.10",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => null,
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "updates" => [
       "update available" => false,
       "latest release version" => "v0.8.11",
       "update check interval" => "weekly",
       "update cache file" => "~/AppData/Roaming/PsySH/update_check.json",
     ],
     "pcntl" => [
       "pcntl available" => false,
       "posix available" => false,
     ],
     "readline" => [
       "readline available" => true,
       "readline enabled" => true,
       "readline service" => "Psy\Readline\Libedit",
     ],
     "history" => [
       "history file" => "~/AppData/Roaming/PsySH/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => true,
       "custom matchers" => [],
     ],
   ]

**Comment by zhekaus** [comment]
```
Psy\info()
=> [
     "PsySH version" => "v0.8.11",
     "PHP version" => "7.1.10",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => null,
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "updates" => [
       "update available" => false,
       "latest release version" => "v0.8.11",
       "update check interval" => "weekly",
       "update cache file" => "~/AppData/Roaming/PsySH/update_check.json",
     ],
     "pcntl" => [
       "pcntl available" => false,
       "posix available" => false,
     ],
     "readline" => [
       "readline available" => true,
       "readline enabled" => true,
       "readline service" => "Psy\Readline\Libedit",
     ],
     "history" => [
       "history file" => "~/AppData/Roaming/PsySH/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => true,
       "custom matchers" => [],
     ],
   ]
```

**Comment by zhekaus** [comment]
I'm not sure about `-with-readline flag`... Where should I put it?

**Comment by bobthecow** [comment]
Looks like you've got readline anyway. It should be working :(

**Comment by bobthecow** [comment]
Readline support under Cygwin appears to be incomplete. See this comment on php.net:

http://php.net/manual/en/function.readline.php#121244

Closing this because there's not much we can do on our end. Sorry :(

**Comment by kip-13** [comment]
I figured out how resolve this problem in [cygwin](http://www.cygwin.com/) or [babun](http://babun.github.io/)(based on cygwin)

In babun you need to use the package manager `pact`(included) to download the correct PHP binary compatible and other packages to work correctly:

```bash
$ pact install php php-posix php-mbstring ....
```

In cygwin you need to use `apt-cyg`(use the binary from [here](https://github.com/transcode-open/apt-cyg)) or `pact`(too) to do the same:

```bash
$ apt-cyg install php php-posix php-mbstring ....
```

The situation with GitBash for Windows is that is a `MSYS` based on `MinGW` not compatible with `POSIX` and use the binary of `PHP` to `Windows` that have problems with `readline` funcs.

**Comment by bobthecow** [comment]
Thanks @kip-13!

Do you mind starting a page in the wiki about this?

**Comment by kip-13** [comment]
I write about this in a page @bobthecow, maybe in [Installation section](https://github.com/bobthecow/psysh/wiki/Installation) like other item in "More installation info" ?

**Comment by kip-13** [comment]
@bobthecow, added the [page](https://github.com/bobthecow/psysh/wiki/Windows) in the wiki, let me know if it's correct for you.
