### ISSUE TITLE
Support for PHP 7.1 array destructuring?

### ISSUE THREAD

**Issue by jpcaparas** [bobthecow/psysh#429]
Hi there, I have PHP 7.1 installed on my machine and array destructuring doesn't seem to work on Tinker v0.8.

On the REPL when I try to run these commands:

```php
$arr = ['Account Code' => 123];
list('Account Code' => $id) = $arr;
```

... it gives me an error:

```php
PHP Parse error: Syntax error, unexpected T_DOUBLE_ARROW, expecting T_PAAMAYIM_NEKUDOTAYIM on line 1
```

**Comment by bobthecow** [comment]
It works great!

<img width="762" alt="screen shot 2017-10-14 at 9 48 20 am" src="https://user-images.githubusercontent.com/53660/31577514-d45d4ebc-b0c4-11e7-9076-a1d61cee6f82.png">

My guess is that you've got an older version of PHP Parser, maybe via some transitive dependency? Try `composer update` and see if that sorts it out?

**Comment by bobthecow** [comment]
(Closing, but feel free to reopen if the issue persists)
