### ISSUE TITLE
Instantiating PHP data structures (php-ds) causes ErrorException in v0.8.13, not v0.8.1

### ISSUE THREAD

**Issue by denzel-morris** [bobthecow/psysh#433]
To replicate:
* Install `php-ds`
* Enter shell

v0.8.13
```php
Psy Shell v0.8.13 (PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> $set = new \Ds\Set();
ErrorException with message 'Object of class Ds\Set could not be converted to boolean'
>>> $vector = new \Ds\Vector();
ErrorException with message 'Object of class Ds\Vector could not be converted to boolean'
```
v0.8.1
```php
Psy Shell v0.8.1 (PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
New version is available (current: v0.8.1, latest: v0.8.13)
>>> $set = new \Ds\Set();
=> Ds\Set {#672}
>>> $vector = new \Ds\Vector();
=> Ds\Vector {#670}
```

**Comment by denzel-morris** [comment]
The issue was introduced in `symfony/var-dumper`, specifically: https://github.com/symfony/var-dumper/commit/67f5e39024bddfbdaf390569e58d9b72a12472e0#diff-d78a4edfbc2d4181348657de4ad6e53eR94. The problem is due to the first case clause:
```php
switch (true) {
                    case empty($v):
                    case true === $v:
                    case \is_int($v):
                    case \is_float($v):
                        continue 2;
```
which attempts to convert a `\Ds\Set` (as an example) to a boolean by way of `empty`. Since `Ds\Set` is not convertabe to a boolean, then an exception is thrown.

**Comment by bobthecow** [comment]
Open an issue with Symfony?

cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Or a bug in php-ds? No other PHP class behave like that AFAIK.

**Comment by nicolas-grekas** [comment]
@denzel-morris PR welcomed on symfony/symfony if you figure out a workaround.

**Comment by nicolas-grekas** [comment]
I think doing both is the best: report the bug to php-ds, and ship a workaround in Symfony

**Comment by denzel-morris** [comment]
@bobthecow indeed, that makes sense, initially I suspected the bug was in psysh until I inspected further.
@nicolas-grekas good idea, I'll open the issues when I have some free time, and then possibly look deeper into a fix as well. There're some edge cases that I feel must be thought through. Haven't had the time to think them through.

Thanks guys.
