### ISSUE TITLE
rmdir() failing in dnoegel/php-xdg-base-dir

### ISSUE THREAD

**Issue by mikeschinkel** [bobthecow/psysh#438]
I have installed `psysh` on a Mac in `/usr/local/bin` but every time I run if I get the following error thrown by [dnoegel/php-xdg-base-dir](https://github.com/dnoegel/php-xdg-base-dir):

    PHP Warning:  rmdir(/var/folders/.../T/php-xdg-runtime-dir-fallback-mschinkel): Directory not empty in phar:///usr/local/bin/psysh/build-vendor/dnoegel/php-xdg-base-dir/src/Xdg.php on line 110
    PHP Stack trace:
    PHP   1. {main}() /usr/local/bin/psysh:0
    PHP   2. Psy\{closure}() /usr/local/bin/psysh:141
    PHP   3. Psy\Shell->run() phar:///usr/local/bin/psysh/src/Psy/functions.php:325
    PHP   4. Psy\Shell->initializeTabCompletion() phar:///usr/local/bin/psysh/src/Psy/Shell.php:247
    PHP   5. Psy\Shell->addTabCompletionMatchers() phar:///usr/local/bin/psysh/src/Psy/Shell.php:990
    PHP   6. Psy\Shell->getTabCompletionMatchers() phar:///usr/local/bin/psysh/src/Psy/Shell.php:224
    PHP   7. Psy\Shell->all() phar:///usr/local/bin/psysh/src/Psy/Shell.php:200
    PHP   8. Psy\Shell->init() phar:///usr/local/bin/psysh/build-vendor/symfony/console/Application.php:641
    PHP   9. Psy\Shell->getDefaultCommands() phar:///usr/local/bin/psysh/build-vendor/symfony/console/Application.php:1163
    PHP  10. Psy\Configuration->getRuntimeDir() phar:///usr/local/bin/psysh/src/Psy/Shell.php:185
    PHP  11. Psy\ConfigPaths::getRuntimeDir() phar:///usr/local/bin/psysh/src/Psy/Configuration.php:348
    PHP  12. XdgBaseDir\Xdg->getRuntimeDir() phar:///usr/local/bin/psysh/src/Psy/ConfigPaths.php:153
    PHP  13. rmdir() phar:///usr/local/bin/psysh/build-vendor/dnoegel/php-xdg-base-dir/src/Xdg.php:110

I did submit [an issue](https://github.com/dnoegel/php-xdg-base-dir/issues/22) to that repo as well, but of course in order to fix this you would have to update your software to incorporate any potential fix if and when he updates, or address your need for that library with other code.

**Comment by bobthecow** [comment]
This should be fixed as of v0.8.15!
