### ISSUE TITLE
Documentation awesomeness

### ISSUE THREAD

**Issue by ianchanning** [bobthecow/psysh#439]
Not much to say other than this is an awesome tool. I experienced a rather nice side affect from it just now. One of the things I've always like about PHP is the documentation. Each function reference has useful examples with it, that along with the user examples that are submitted with each page.

Now we've got an excellent REPL to test out the code. I'm running on Windows so it's extra nice that it all just 'works'. I was having a brain fade and struggling to understand the weird requirement for `unset` when calling a [foreach by reference][1]. But now I can literally just copy and paste the code from there straight into psysh, which allows you to instantly see the quirk the example talks about:

![2017-11-15 00_31_35-greenshot](https://user-images.githubusercontent.com/233318/32810725-954e415e-c99c-11e7-8f60-8cb4b9321bf0.png)

  [1]: http://php.net/manual/en/control-structures.foreach.php

**Comment by bobthecow** [comment]
Awesome. Thank you for sharing :)
