### ISSUE TITLE
Add some documentation for running processes

### ISSUE THREAD

**Issue by nesk** [bobthecow/psysh#441]
I've just noticed Psy Shell was acting strange when running processes. See this example:

```php
>>> $p = proc_open('nc -l', [], $pipes)
=> process resource #190
>>> proc_get_status($p)['running']
=> false
```

I'm starting a new process with the listening mode of `netcat` here, which runs indefinitely. The `running` status property returns `false`, although the `netcat` process is still running. It seems like PHP can't see it running.

After searching for a while, I found the solution in bobthecow/psysh#198. There is a `usePcntl` option, I set it to `false` and now everything works fine, the `running` status property now returns `true`.
 
It would be worth talking about this kind of issue in the documentation. 🙂

**Comment by bobthecow** [comment]
Added to the Troubleshooting documentation: https://github.com/bobthecow/psysh/wiki/Troubleshooting
