### ISSUE TITLE
Add support for Symfony 4

### ISSUE THREAD

**Issue by msheakoski** [bobthecow/psysh#442]
Adding `|^4.0` to both of these version constraints should do the trick.
https://github.com/bobthecow/psysh/blob/b1d289c2cb03a2f8249912c53e96ced38f879926/composer.json#L17-L18

**Comment by mloberg** [comment]
I created a Pull Request for this in #444

**Comment by msheakoski** [comment]
Thank you for the fix! The change is live as of commit 86681ae and release v0.8.16. This issue can now be closed.
