### ISSUE TITLE
Error: mkdir(): Permission denied

### ISSUE THREAD

**Issue by 749** [bobthecow/psysh#443]
I am using psysh as part of larvel's tinker command, however after updating to the latest version (0.8.15) I am just getting the followin error:
```
In Configuration.php line 352:

  mkdir(): Permission denied

```

I am unable to get a stacktrace, so I have no clue how to debug the error, any ideas?

PHP Version info:
```
PHP 7.1.12-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 29 2017 10:03:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by 749** [comment]
Narrowing down the problem:
I was logged in as `user1` used `sudo su` to become super-user and then used `su user2` to become that user. however the `XDG_RUNTIME_DIR` still pointed to `/run/user/0`
could be a problem inside php or linux
Anyways when I directly used `sudo su user2` from user1 account, everything works as expected

**Comment by drblue** [comment]
I'm reposting my workaround from [issue #34 over at laravel/tinker](https://github.com/laravel/tinker/issues/34) here:

---

Had this for a while on a shared server but thanks to the posts by @ingria and @groovix I looked into it and a workaround (until someone knowledgeable fixes it) is to tell psysh to run in another directory where one has write access.

This can be done through either placing a config-file in `~/.config/psysh/config.php` or as `.psysh.php` in the root of a Laravel-project ([ref](https://github.com/bobthecow/psysh/wiki/Configuration)).

Here's my sample config-file (note that the psysh wiki [doesn't mention `runtimeDir`](https://github.com/bobthecow/psysh/wiki/Config-options) as a config option but [the source code lists it as a valid option](https://github.com/bobthecow/psysh/blob/master/src/Psy/Configuration.php#L57)):

```
// Temporary fix for issue #34 in laravel tinker where psysh
// tries to run in `/run/user/<uid>/psysh`.
//
// This overrides that behaviour to `.psysh/` inside the project
return [
	'runtimeDir'	=> './.psysh',
];
```

**Comment by drblue** [comment]
A quick side note from today: When I added `runtimeDir` to the config options on the psysh wiki, I noticed that the runtimeDir could be overriden by specifying the environment variable `XDG_RUNTIME_DIR`. In my case with my shared server, it was set to `/run/user/1011`, which didn't exist on and nor did my user have the neccessary permissions to create it either.

So I believe this was the culpit at least in my case.

Maybe a fix could be to catch the 'Permission denied' on [Configuration.php:L352](https://github.com/bobthecow/psysh/blob/master/src/Psy/Configuration.php#L352) and revert to using `sys_get_temp_dir()` as a fallback? This is already done in [ConfigPaths.php:L149](https://github.com/bobthecow/psysh/blob/master/src/Psy/ConfigPaths.php#L149) so maybe could be moved to it's own method for falling back on?

Just thinking out loud - take it with a grain of salt =).

**Comment by TheBigK** [comment]
I'm facing this issue as well. In my case, even adding 

```
return [
	'runtimeDir'	=> './.psysh',
];
```

in the laravel root directory didn't work. Would really appreciate a fix.

**Comment by tgr** [comment]
The ugly workaround is running PsySH with `XDG_RUNTIME_DIR= psysh` or similar (or make sure `sudo` resets the environment, which it does by default). Filed dnoegel/php-xdg-base-dir#26 upstream, not sure if that's a better place to handle it than `Psy/Configuration` though.

**Comment by fgilio** [comment]
Thanks @alberto-bottarini!

**Comment by TheBigK** [comment]
@rvsth - When you are switching user; use `su - USER` instead of `su USER`. That `-` after su makes all the difference. Give it a try.

**Comment by tbruckmaier** [comment]
You can also set `XDG_RUNTIME_DIR` on the fly if you do not want to create an extra config file:
```sh
XDG_RUNTIME_DIR=../.psysh php artisan tinker
```
Or if you want to use a temp directory (though a new psysh environment is created each time):
```sh
XDG_RUNTIME_DIR=$(mktemp -d) php artisan tinker
```

**Comment by AshishDhamala** [comment]
> This error occurs because you switch user (guessing using `su`) without "dash" option.
> 
> Replace `su www-data` with `su - www-data` and everything should works!
> 
> psysh tries to write runtime data in "original user" folder, instead of in "current user" folder...
> 
> PS my "current user" has `XDG_RUNTIME_DIR` env defined. Switching user without -, forced www-data to use the same env variable, while www-data hasn't write permission in that folder.

Thanks. This solution worked for me..

**Comment by bobthecow** [comment]
This should be fixed in v0.10.0!

**Comment by sommarnatt** [comment]
I ran into this on a shared hosting server running CloudLinux OS where my env was:
`env|grep RUNTIME
XDG_RUNTIME_DIR=/run/user/1022`
That directory didn't exist so i exported XDG_RUNTIME_DIR in .bashrc instead:
`export XDG_RUNTIME_DIR=/tmp`
(note that in cloudlinux with cagefs /tmp doesnt mean the shared /tmp on the server but a directory in the users homedir.)
After that it worked fine for me.

**Comment by BafS** [comment]
Would be good to have an option to disable this totally for read-only systems
