### ISSUE TITLE
psysh 0.8.16 from Homebrew reported fatal error when started.

### ISSUE THREAD

**Issue by caiknife** [bobthecow/psysh#445]
I'm using ZSH 5.4.2, PHP 5.6.32 on MacOS 10.12.6

When I started psysh, I got this

```
->psysh
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /usr/local/Cellar/psysh/0.8.16/libexec/vendor/symfony/console/Application.php on line 83
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/psysh/0.8.16/libexec/bin/psysh:0
PHP   2. spl_autoload_call() /usr/local/Cellar/psysh/0.8.16/libexec/bin/psysh:109
PHP   3. Composer\Autoload\ClassLoader->loadClass() /usr/local/Cellar/psysh/0.8.16/libexec/bin/psysh:109
PHP   4. Composer\Autoload\includeFile() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:322
PHP   5. include() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:444
PHP   6. spl_autoload_call() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:46
PHP   7. Composer\Autoload\ClassLoader->loadClass() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:46
PHP   8. Composer\Autoload\includeFile() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:322

Fatal error: Default value for parameters with a class type hint can only be NULL in /usr/local/Cellar/psysh/0.8.16/libexec/vendor/symfony/console/Application.php on line 83

Call Stack:
    0.0003     261312   1. {main}() /usr/local/Cellar/psysh/0.8.16/libexec/bin/psysh:0
    0.0025     577136   2. spl_autoload_call() /usr/local/Cellar/psysh/0.8.16/libexec/bin/psysh:109
    0.0025     577168   3. Composer\Autoload\ClassLoader->loadClass() /usr/local/Cellar/psysh/0.8.16/libexec/bin/psysh:109
    0.0025     577312   4. Composer\Autoload\includeFile() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:322
    0.0033     796992   5. include('/usr/local/Cellar/psysh/0.8.16/libexec/src/Psy/Shell.php') /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:444
    0.0033     797304   6. spl_autoload_call() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:46
    0.0033     797360   7. Composer\Autoload\ClassLoader->loadClass() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:46
    0.0033     797520   8. Composer\Autoload\includeFile() /usr/local/Cellar/psysh/0.8.16/libexec/vendor/composer/ClassLoader.php:322
```

Any ideas?

**Comment by bobthecow** [comment]
Hrm.

It looks like Composer has started taking advantage of PHP 7+ features, so the bundled Composer code in the psysh Phar is exploding on older PHP version. We'll need to start building a Phar on PHP 5.x, like we already do for the legacy PHP 5.3 build.

After we fix that, the Homebrew recipe will likely need to be updated to grab the appropriate Phar version depending on your linked PHP version. Or split into multiple `phpx-psysh` recipes? Right now I think it just always grabs the latest We should probably take it up with the maintainers of homebrew-php to figure out the best way to make this work.

**Comment by bobthecow** [comment]
Okay, I've released v0.8.17 which _should_ fix this issue. We just need to wait for Travis to finish the build, and Homebrew test bot to pick up the updated version and prep a release :)

**Comment by xeBuz** [comment]
I got the same error:
> PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /usr/local/Cellar/psysh/0.8.17/libexec/vendor/symfony/console/Application.php on line 83
> Fatal error: Default value for parameters with a class type hint can only be NULL in /usr/local/Cellar/psysh/0.8.17/libexec/vendor/symfony/console/Application.php on line 83


PHP 5.6.32  psysh 0.8.17 macOS 10.13.2

**Comment by bobthecow** [comment]
You’re right, this is definitely not solved. It seemed like the change would work, based on local testing. I’ll give it another shot.

**Comment by bobthecow** [comment]
I got it. I (incorrectly) assumed the Homebrew formula was using the pre-built phars, and updated the process so that they would be built to work on most PHP versions.

But Homebrew doesn't do that. It uses Composer to install from source. Which wouldn't be a bad thing, except that they bottle the result from PHP 7.1.x and reuse it for every other install. This pulls in the 7.1+ features in Symfony 4.0.

Unfortunately there's no good answer for this, at least as far as I can see.

* We could split the `psysh` formula into `php53-psysh`, `php54-psysh`, etc. But that's awkward, and doesn't match what any of the other composer-installable formulas use.
* We could stop recommending installing via Homebrew for anyone not running PHP 7.1. But that'd be a shame.
* We could recommend building from source (i.e. skipping the bottle) for everyone using PHP < 7.1: `brew install -s psysh`.

The last option actually works great, and seems like the least-bad option, at least until we have a better Homebrew install story available.

**Comment by bobthecow** [comment]
homebrew-php is done, and it looks like psysh won't make the jump into homebrew-core, so this is kind of a moot point now :(

current recommendation is to use one of the other installation methods.
