### ISSUE TITLE
keywordprg in vim

### ISSUE THREAD

**Issue by greg0ire** [bobthecow/psysh#446]
The `doc` command is so nice I would like to use it as `keywordprg` in vim, meaning that when I press `K`, the doc for the word under the cursor would popup. Is there a way to invoke psysh so that it would display the manual? Something like `psysh doc array_map`?

**Comment by bobthecow** [comment]
There isn't currently, but you should be able to easily do this with a custom command!

**Comment by greg0ire** [comment]
I shall try that, thanks!

**Comment by greg0ire** [comment]
Found a simple answer: `echo "doc array_search"|psysh`

**Comment by greg0ire** [comment]
```
cat ~/bin/psysh-wrapper 
#!/bin/bash
echo "doc $1"|psysh
```

set keywordprg=psysh-wrapper
