### ISSUE TITLE
Add an "incognito" mode

### ISSUE THREAD

**Issue by supriyo-biswas** [bobthecow/psysh#447]
PsySH, just like any other shell has a history. However, sometimes it's necessary for something not to be stored in the history; for example when calculating password hashes manually.

With bash, you just need to add a space in front of the command:

```
# (space) echo hunter2
```

Can we have this in PsySH? Spaces probably won't be suitable here because people might expect indented code to be saved, so something like this could be done:

```
>>> incognito password_hash("hunter2", PASSWORD_BCRYPT)
```

(Probably with `incognito` aliased to `i` or something so that it's easier to type.)

**Comment by bobthecow** [comment]
It seems like spaces could work, since indenting should only matter on wrapped lines. We just skip history for blocks where the _first line_ starts with a space?

**Comment by supriyo-biswas** [comment]
Yup. That's how it works in bash too.

**Comment by bobthecow** [comment]
See 417b921 :)

Thanks for the request!

Note that this is only in the dev branch at this point, and the exact details might change a bit before it lands in master. In this case, we might add a config setting for opting into (or out of) this behavior.

**Comment by supriyo-biswas** [comment]
Thank you :)
