### ISSUE TITLE
psysh 0.8.16 from Homebrew reported syntax error

### ISSUE THREAD

**Issue by chiangzg** [bobthecow/psysh#451]
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /usr/local/Cellar/psysh/0.8.16/libexec/vendor/symfony/console/Output/Output.php on line 40

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /usr/local/Cellar/psysh/0.8.16/libexec/vendor/symfony/console/Output/Output.php on line 40

PHP 7.0.26 — cli

![wx20171228-174615](https://user-images.githubusercontent.com/13807350/34406991-05e689f4-ebf7-11e7-94b7-cdb87dae2c0f.png)

**Comment by bobthecow** [comment]
Yeah, this is the same issue as #445.

Homebrew is making some drastic changes to the PHP formulas, so I'm waiting on doing anything crazy here until that all settles down. In the meantime, I can build the stable version with Symfony 3.x rather than 4.x so it'll be compatible with PHP 5.
