### ISSUE TITLE
Custom command on exit

### ISSUE THREAD

**Issue by bartonhammond** [bobthecow/psysh#452]
I would like to run `$driver->quit()` whenever I `quit|exit` the shell.  Is that possible? 

I using `psysh` with Selenium Standalone Server and w/o the `$driver->quit()` I have browser windows scattered around.

**Comment by bobthecow** [comment]
I'm not sure about the value of adding this as a feature to PsySH, as I haven't personally had or heard of much use for it. Where is your `$driver` coming from? If it's coming from a wrapper of some sort, that might be the ideal place to add it?

**Comment by bartonhammond** [comment]
I don't need this now that I've changed to Behat Mink extension - seems Mink closes the windows on finish so I don't have `browser windows scattered around`.
