### ISSUE TITLE
Cannot access self:: when no class scope is active

### ISSUE THREAD

**Issue by bartonhammond** [bobthecow/psysh#453]
Following [https://www.sitepoint.com/interactive-php-debugging-psysh/](https://www.sitepoint.com/interactive-php-debugging-psysh/)  I added the line:

`  \Psy\Shell::debug(get_defined_vars());` to my test.

I also added the phpunit options : ` vendor/bin/phpunit  --verbose --debug `

When the script stops in the PsyShell at the `debug` command, I tried to:

```
>>> echo self::$_selectors['category_add_button']
PHP Error:  Cannot access self:: when no class scope is active on line 1
```

How do I get access to the class scope?

**Comment by bobthecow** [comment]
you need to pass the class scope through. you can pass `$this` as the second argument to `debug` or you can use the shortcut `eval(Psy\sh())` ([which does just that](https://github.com/bobthecow/psysh/blob/master/src/Psy/functions.php#L31)

**Comment by bartonhammond** [comment]
Thanks - that's awesome!
