### ISSUE TITLE
Incorrect evaluation of expression

### ISSUE THREAD

**Issue by peterchaula** [bobthecow/psysh#455]
![image](https://user-images.githubusercontent.com/13304490/34520833-4b1349d6-f093-11e7-89f5-17b1bc40bfab.png)

The PHP interpreter correctly outputs 1. I'm running PHP 7.1

**Comment by bobthecow** [comment]
Thanks for reporting! This is a bug in an underlying library, and I've raised the issue there:

nikic/PHP-Parser#459

**Comment by bobthecow** [comment]
This is fixed as of v3.1.4 of PHP Parser :)
