### ISSUE TITLE
Class not found in eval()'d code

### ISSUE THREAD

**Issue by bartonhammond** [bobthecow/psysh#456]
When I try to execute the following statement, I get error as shown.  How do I get access to class?

```
>>> $webDriverSelect = new WebDriverSelect($this->find(self::$_selectors['category']));
PHP Fatal error:  Class 'WebDriverSelect' not found in eval()'d code on line 1
```
Where Am i?
```
>>> whereami
From test/uwce/adminCreateSessions/pageObjects/CoursePage.class.php:156:
    151|             $this->find($selector);
    152|         }
    153|     }
    154| 
    155|     function setCategory() {
  > 156|         \Psy\Shell::debug(get_defined_vars(),$this);        
    157|         $webDriverSelect = new WebDriverSelect($this->find(self::$_selectors['category']));
    158|         $webDriverSelect->selectByVisibleText("Fond du Lac (Staging) - BWH Music Category Name");
    159|     
    160|     }
    161| 
```

**Comment by bobthecow** [comment]
The PsySH execution context doesn't automatically inherit `use` statements from where it's called (though this doesn't sound like a horrible idea, if it isn't too weird to implement). This means, from inside PsySH, you'll have to either use the full class name, or enter a `use` statement yourself.

**Comment by bartonhammond** [comment]
Ah - that makes sense, to just use `use`;

Thanks!

**Comment by GrahamCampbell** [comment]
> The PsySH execution context doesn't automatically inherit use statements from where it's called

Yeh, I found that out yesterday the hard way after typing out a lot of code, then having to go back. :P

**Comment by bobthecow** [comment]
I mean, you're calling a function. It would be kind of weird if a function call passed the caller's `use` statements through to the callee.

That said, it probably should. If we can figure it out. Wanna take a shot at it, @GrahamCampbell? :)

**Comment by bobthecow** [comment]
Wait! What could this be??!?!!

<img width="762" alt="screen shot 2018-01-06 at 11 09 51 am" src="https://user-images.githubusercontent.com/53660/34643039-39876210-f2d2-11e7-820d-e3d2f8fc5b77.png">

<sub>(Coming soon to a dev branch near you)</sub>
