### ISSUE TITLE
Ctrl + 4: quit (core dumped)  php bin/psysh

### ISSUE THREAD

**Issue by kocoten1992** [bobthecow/psysh#463]
## Step to reproduce
1. git clone https://github.com/bobthecow/psysh
2. cd psysh && composer install
3. php bin/psysh
4. press **Ctrl + 4** (the button above 'r' character)

## Result
```
quit (core dumped)  php bin/psysh
```

It not affecting me, just discover it by accident :peace_symbol:

**Comment by bobthecow** [comment]
Congrats! You've accidentally discovered the keyboard shortcut to send the `SIGQUIT` signal on *nix machines!

This is exactly what programs are supposed to do when you press ctrl-4 :)

<img width="954" alt="screen shot 2018-01-20 at 2 59 21 pm" src="https://user-images.githubusercontent.com/53660/35188825-997893bc-fdf2-11e7-9071-5f6ed1d730c1.png">

**Comment by kocoten1992** [comment]
Shortcut are dangerous these days

Ctrl+R to search old command, a miss press, sigquit and a whole session gone

On chrome, Ctrl+Shift+Tab to turn back one tab, miss Tab to Q and you got f*** :disappointed:
