### ISSUE TITLE
Make Symphony/Var_dumper optimal

### ISSUE THREAD

**Issue by amenk** [bobthecow/psysh#467]
The var dumper project registers the global function dump which makes is hard to use psysh in projects which also register this function (Contao 3.5).

Could we make this dependency optional? What is it needed for?

**Comment by bobthecow** [comment]
VarDumper is the “P” in our REPL. We kind of need it :)

VarDumper only creates a global `dump` function if one isn’t already defined:

https://github.com/symfony/var-dumper/blob/master/Resources/functions/dump.php

If Contao did the same, you wouldn’t have a problem. 

If you can’t convince them to do that, ensuring that Contao’s version is defined first will prevent collisions.

**Comment by amenk** [comment]
Understood.

Unfortunately Contao does not do the same ... 
I am using it in https://github.com/imi-digital/imi-conrun - which is supposed to work with most versions of Contao, so I properly can also not convince the Contao maintainers to check for function_exists.

I have to check how I can ensure that Contao is loaded first.

**Comment by amenk** [comment]
Wait a second .. I guess PsySh would not need the dump() function - just dumper itself? Maybe it is a bad idea for widely used composer packages to "pollute" the global namespace.. :thinking:

**Comment by amenk** [comment]
I decided to not use PsySH in conrun for now ... will just leave the interactive console out for now and concentrate on using PsySH in non-Contao projects :-)

**Comment by bobthecow** [comment]
Yeah, PsySH doesn’t use `dump` anywhere.
