### ISSUE TITLE
eval throws an error

### ISSUE THREAD

**Issue by peterchaula** [bobthecow/psysh#469]
Calling `eval` throws an error

In cli:

![image](https://user-images.githubusercontent.com/13304490/36030825-59270392-0db1-11e8-9d1d-ca14006a3e4f.png)

In Psysh:

![image](https://user-images.githubusercontent.com/13304490/36030785-318339be-0db1-11e8-9275-80f58013e8f3.png)

**Comment by zonuexe** [comment]
@peterchaula It is missing line terminator `;`

```
 % psysh
Psy Shell v0.8.17 (PHP 7.1.14 — cli) by Justin Hileman
>>> eval('echo 1/2;')
0.5⏎
=> null
```

This behavior is consistent with the usual PHP evaluation.

```
% php -r "eval('echo 1/2;');"
0.5

% php -r "eval('echo 1/2');"
PHP Parse error:  syntax error, unexpected end of file, expecting ',' or ';' in Command line code(1) : eval()'d code on line 1

Parse error: syntax error, unexpected end of file, expecting ',' or ';' in Command line code(1) : eval()'d code on line 1
```

**Comment by peterchaula** [comment]
Ah, thank you.
