### ISSUE TITLE
Website hangs - Locking problem (Windows, Laravel)

### ISSUE THREAD

**Issue by adam1010** [bobthecow/psysh#474]
I'm not sure if this issue is in psych or in Laravel, but if I run

`php artisan tinker`

I correctly see: 

> Psy Shell v0.8.17 (PHP 7.2.2 — cli) by Justin Hileman

Now if I try to access the website in my browser with the Psy shell open, the website will not load. The page tries to load for over a minute and eventually times out. **If I close the shell while the page is trying to load then the page successfully loads.**

My guess is that Psy (or Artisan) is locking a file that is used by the Laravel instance and that is causing Laravel to hang until the file is no longer in use.

Any idea how I can debug this further to see where the problem is coming from?

The problem exists in all versions of Psy shell and Laravel that I've used.

**Comment by adam1010** [comment]
I was able to reproduce the problem using just Artisan commands, so at this point it appears the bug is with Laravel and not Psy -- I will file this issue with Laravel instead.

**Comment by bobthecow** [comment]
:+1:

**Comment by adam1010** [comment]
I found the solution so I'll post it here in case anyone else runs into this. The problem is actually with **xdebug**

In PHPStorm you need to set Languages > PHP > Debug > Max Simultaneous Connections

By default it is 1 for some reason, so just jack it up to 5 and you're all set!
