### ISSUE TITLE
Composer Install getting hung up

### ISSUE THREAD

**Issue by nathanaelphilip** [bobthecow/psysh#478]
Setup:
Laravel 5.6 on PHP 7.1

Installing psy/psysh (v0.8.17):

```
 Failed to download psy/psysh from source: The process "git clone --no-checkout 'https://github.com/bobthecow/psysh.git' '/app/vendor/psy/psysh' && cd '/app/vendor/psy/psysh' && git remote add composer 'https://github.com/bobthecow/psysh.git' && git fetch composer" exceeded the timeout of 300 seconds.
          Now trying to download from dist
        - Installing psy/psysh (v0.8.17): Loading from cache
          Skipped installation of bin bin/psysh for package psy/psysh: name conflicts with an existing file
      psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
      psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
      psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSIX extension as well.)
      psy/psysh suggests installing ext-readline (Enables support for arrow-key history navigation, and showing and manipulating command history.)
      psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
```

When I hit the local dev url, I get this fatal error:
`Warning: require(/app/vendor/composer/../psy/psysh/src/Psy/functions.php): failed to open stream: No such file or directory in /app/vendor/composer/autoload_real.php on line 66 Fatal error: require(): Failed opening required '/app/vendor/composer/../psy/psysh/src/Psy/functions.php' (include_path='.:') in /app/vendor/composer/autoload_real.php on line 66 `

**Comment by bobthecow** [comment]
Installation seems to have failed in a couple of places, most notably when trying to download the actual repo.

I bet if you open `vendor/psy/psysh` in your project it won't be there. Which would make it hard to include :)

I don't know too much about debugging composer issues, but I'd start with

```
composer clear-cache
composer install psy/psysh
```

… to try to get a successful install?

**Comment by nathanaelphilip** [comment]
ok, thanks @bobthecow ! i’ll try that :)

**Comment by nathanaelphilip** [comment]
no go. still getting the timeout issue I’m afraid.

**Comment by bobthecow** [comment]
call it with `-vvv` for super verbose output in case it clarifies what's timing out?

or you can try to manually check out the git repo in case it's an issue with git or something?

**Comment by nathanaelphilip** [comment]
@bobthecow i _think_ it may have something to do with me using Nanobox. I’ll keep this thread updated if/when I find out anything.

**Comment by nathanaelphilip** [comment]
@bobthecow turns out it was just my internet being really slow 😂
Thanks for you response!

**Comment by bobthecow** [comment]
Ha! Glad you were able to track that down :)
