### ISSUE TITLE
Special characters inputs not working for me (arrows and tab)

### ISSUE THREAD

**Issue by alvahro** [bobthecow/psysh#479]
Hello,

First of all: great job!

MacOS High Sierra 10.13.3
PHP 5.6.30
psysh ver: New version is available (current: v0.8.17, latest: v0.8.18). It says that even when i just downloaded it again.
Terminal encoding: UTF-8

When I press the arrow keys to move on a line or between them this code appears:
`>>> echo "hell^[[D^[[C^[[A^[[B`

And when I press the tab key instead of execute the "Auto [tab][tab] complete" feature it just put tow tab spaces at the end of the line.

Thanks!

**Comment by bobthecow** [comment]
It sounds like your PHP install doesn’t have readline support. Do you mind pasting the output of `Psy\info()`?

**Comment by bobthecow** [comment]
Oh! Re update available: I cut a new release last night but forgot to update the one on the website. I’ll fix that this evening :)

**Comment by alvahro** [comment]
Hi! thanks for the quick response!
 Here is the output of the `Psy/info()`:

`>>>  Psy\info()
=> [
     "PsySH version" => "v0.8.17",
     "PHP version" => "5.6.30",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => null,
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "updates" => [
       "update available" => true,
       "latest release version" => "v0.8.18",
       "update check interval" => "weekly",
       "update cache file" => "~/.config/psysh/update_check.json",
     ],
     "pcntl" => [
       "pcntl available" => true,
       "posix available" => true,
     ],
     "readline" => [
       "readline available" => false,
     ],
     "history" => [
       "history file" => "~/.config/psysh/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => false,
       "custom matchers" => [],
       "bracketed paste" => false,
     ],
   ]`

**Comment by attrib** [comment]
I have the same issue now with PHP 7.2 on MacOS. Installing php using homebrew (`brew install php@7.2`).

Readline support is enabled
```
readline

Readline Support => enabled
Readline library => EditLine wrapper

Directive => Local Value => Master Value
cli.pager => no value => no value
cli.prompt => \b \>  => \b \>
```

`Psy/info()` is not working anymore?

```
Psy Shell v0.9.9 (PHP 7.2.13 — cli) by Justin Hileman
Psy/info()
PHP Fatal error:  Call to undefined function info() in Psy Shell code on line 1
```
