### ISSUE TITLE
Scope variables set before runtime via Shell::setScopeVariables are not passed to shell

### ISSUE THREAD

**Issue by connordavison** [bobthecow/psysh#483]
Scope variables set before runtime via `\Psy\Shell::setScopeVariables` are not passed to the shell. See the following minimal example (using `psy/psysh:0.9.1`):

```php
<?php // demo.php

require_once 'vendor/autoload.php';

$sh = new \Psy\Shell();
$sh->setScopeVariables(['hello' => 'world']);
$sh->run();
```

```bash
$ php demo.php
Psy Shell v0.9.1 (PHP 7.0.27 — cli) by Justin Hileman
>>> ls
>>> // No variables defined
```

The same behaviour occurs when using `\Psy\debug(['hello' => 'world'])`. The immediate cause appears to be that the manually-set scope variables are being overwritten by variables from user-defined includes. See [here](https://github.com/bobthecow/psysh/blob/master/src/ExecutionLoop.php#L86):

```php
$load = function (Shell $__psysh__) {
    set_error_handler([$__psysh__, 'handleError']);
    foreach ($__psysh__->getIncludes() as $__psysh_include__) {
        try {
            include $__psysh_include__;
        } catch (\Error $_e) {
            $__psysh__->writeException(ErrorException::fromError($_e));
        } catch (\Exception $_e) {
            $__psysh__->writeException($_e);
        }
    }
    restore_error_handler();
    unset($__psysh_include__);

    $__psysh__->setScopeVariables(get_defined_vars());
};
```

See [here](https://github.com/luxifer/symfony-repl/blob/master/bin/symfony-repl) for the full failing example.

**Comment by connordavison** [comment]
The quick response is much appreciated - thanks!

**Comment by bobthecow** [comment]
No problem!
