### ISSUE TITLE
PHP input containing text matching PsySH command names cause the command to be executed.

### ISSUE THREAD

**Issue by phil-s** [bobthecow/psysh#490]
Psy Shell v0.9.3

Examples:

```
>>> "q";
Exit:  Goodbye
```
```
>>> [
... "q",
RuntimeException with message 'Too many arguments, expected arguments "command".'
```
```
>>> [
... "q"
Exit:  Goodbye
```
```
>>> $data = [
... 'foo',
... 'bar',
... 'show',
Unknown target: ,
```

**Comment by bobthecow** [comment]
Heh. Interesting.

I mean, it's not surprising that it does this. But it's a bit surprising that I have never run into it.

For a quick fix, changing those lines into any equivalent (valid) PHP that doesn't start with a string with exactly that value will work around it. For example:

```
>>> ("q")
=> "q"
>>> ;"q"
=> "q"
>>> $q = "q"
=> "q"
```

**Comment by bobthecow** [comment]
This has been fixed in the `develop` branch and will go out with the next stable release. Thanks for reporting it :)

**Comment by phil-s** [comment]
Thanks for the quick fix!

Is it possible to restrict the recognition of commands to initial (non-continuation) input lines?  Otherwise I can still contrive a situation where I can make a command be interpreted during PHP input. e.g.:

    >>> define('show', 'foo');
    => true
    >>> $x = [ show ];
    => [
         "foo",
       ]
    >>> $x = [
    ... show
    Not enough arguments (missing: "target")

**Comment by bobthecow** [comment]
The original issue is undeniably a bug. What you're asking for now isn't quite as clear cut :)

There are quite a few commands that are awesome when used in the middle of code, and the command system is intentionally built so that they work that way. For example, the `buffer` command is worthless if it doesn't work when there's actually code in the buffer.

Commands like `sudo` and `throw-up` are also kind of cool when used along with code:

```
>>> class Sekrit {
...   private $password = 'hunter2';
... }
>>> $sekrit = new Sekrit
=> Sekrit {#1757}
```

```
>>> function get($obj, $prop) {
...   sudo return $obj->$prop;
... }
```

```
>>> get($sekrit, 'password')
=> "hunter2"
```

```
>>> function set($obj, $prop, $val = null) {
...   sudo $obj->$prop = $val;
... }
```

```
>>> set($sekrit, 'password', 'monkeymonkeymonkeymonkeymonkey')
=> null
>>> get($sekrit, 'password')
=> "monkeymonkeymonkeymonkeymonkey"
```

**Comment by phil-s** [comment]
Yikes.

I've never played with that command, and it hadn't occurred to me that it could be embedded like that.  Is that rewriting the code before passing it to the php process?  If so, perhaps it's already contextually-aware enough to be able to figure out things like "we're in a string -- don't do any magic"?

**Comment by phil-s** [comment]
Thinking more on this, I'm convinced that a change is needed.  I do not believe it is reasonable that PsySH can fall over or misbehave in the face of valid PHP input; and the fact that it's possible to add new arbitrary PsySH commands means the potential for failures or other unintended behaviour can be *dramatically* higher than it is by default.  (In my current Drupal project, with "drush php" importing all the available commands/aliases, I actually have 418 PsySH commands which can trigger this kind of issue.)

I understand that there is intentional behaviour here, so I would suggest that some new options and constraints be applied.

(1) As per my previous comment, I think that when *inside a string* such commands should never be executed -- if it's at all possible to detect that context (and I hope that it is).  The `buffer` command *might* still be a desirable exception to that, but possibly that's the *only* command for which this behaviour could be wanted?  (Or PsySH commands could perhaps be required to explicitly register that they need to be able to run within a string context, in order for that to be permitted.)

(2) I think there needs to be a config option to specify that unless they appear at the *beginning* of the PHP input, plain command names like this will *never* be executed.  Because the commands can cause PsySH to fail in such a confusing manner, I would be firmly in favour of this being the *default* setting. (I had encountered these kinds of errors many times before I figured out what was happening, and it was very frustrating.)

(3) I think there needs to be a *non*-plain form of invoking the commands, such that users can still utilise them even when (2) disallows the plain names. I'm not sure if that would entail some kind of `\Psy\` name-spacing, or some kind of other syntax which is not valid PHP, but which PsySH recognises.  Maybe both.  I suspect the "invalid syntax" approach could be more convenient (less typing).  Either approach would still be valid inside strings, of course, which is partly why I think (1) is important.

In combination, I feel that these changes would make PsySH far more robust, without losing any of its useful functionality/magic.

**Comment by bobthecow** [comment]
I'm with you on 1. I think we can safely say that inside a string context, there's no reason to run a command — even the `buffer` command. In fact, I'm pushing a fix for it now.

I'm not there yet on 2 or 3, though. 

In practice, I think fixing these two — the previous bug with quoted command names, and the issue with open strings — should be sufficient to prevent most if not all real-world issues. After all, it took six years for the string issues to even come up ;)

**Comment by phil-s** [comment]
Thanks for implementing (1).  I agree that dealing with strings and comments dramatically reduces the scope of the problem.

Still, my personal feeling is that PsySH should do the right thing for any valid PHP input; and if that's not necessarily the case by default, then I do wish there would at least be an *option* which would guarantee that behaviour.

Perhaps you'd be more amenable to the other ideas as opt-in settings?

My major concern with it not being the *default* behaviour is that, when a command is inadvertently triggered, it's not trivial for the user to relate that behaviour (and/or possible error message) to the input they believed they had provided, in which case they may have no idea where to start looking.  However, perhaps that aspect can be tackled differently, such that when a PsySH command is executed, it simply tells the user what it is doing?

If there was some output along the lines of `Running PsySH command '<cmd>'` when such a command was invoked then, in cases where that happened accidentally, it would be *far* more apparent to the user what was going on.  That's probably a bit verbose; but perhaps it could be abbreviated without losing the utility, and without feeling too clunky for the normal situation of an intentional execution? e.g.: `PsySH::<cmd>`.  You might experiment with different formats.  Add a bit of colour, and it might not seem too overt.

I'll add that displaying those details when the command triggers an *error* would be less verbose and still an obvious improvement on the current situation; but providing the information in non-error cases might actually be even more important -- a command can run successfully without any other output, which can then corrupt the PHP input silently; and if the end result is still valid PHP then the bugs could prove to be very difficult to track down.

I suppose "whether to display the command being run" could always be a setting as well.  If displaying that information was opt-out, and the other changes were opt-in, and the settings documentation explained the connection between them, that could be a fair solution to the issue, and users who chose to disable the display would (in theory) at least still be made aware of the issue.

(And if you also find that idea too unappealing, opt-in settings would be better than no settings at all.)
