### ISSUE TITLE
Option to not treat "}" as an immediate end to the input?

### ISSUE THREAD

**Issue by phil-s** [bobthecow/psysh#491]
Even with `requireSemicolons` set to `true`, a `}` which *might* be the end of the code is always treated as the end of the code.  This can be annoying when typing (or pasting) code into the repl.

e.g.

    >>> if ($condition) {
    ...   // do something
    ... }
    >>> else { 
    PHP Parse error: Syntax error, unexpected T_ELSE on line 1
    >>>

Obviously one can type `} else {`, but when pasting code (especially) it is inconvenient to require such reformatting to take place.

I think a fair approach would be to require two newlines after such a `}`. The first newline would simply produce a continuation prompt (e.g. so that an `else` clause could be entered), but a newline at *that* prompt would conclude the input.

Waiting for configurable number of newlines would probably be even better.

`};` could still be treated as an immediate end, and it might be good to also offer a stricter version of the new option in which a `}` without a semicolon *never* ends the input, which some people might find helpful.

The latter might make more sense as a stricter third value option for `requireSemicolons` -- or perhaps as a `-1` value for the configurable number of newlines?

**Comment by bobthecow** [comment]
Double newlines doesn’t fix the issue, though, it just defers it a bit :) And it makes closing brackets inconsistent with the way PsySH works the rest of the time. 

If you end the line with a `\\` it will let PsySH know that you wish to continue your code on the next line, much like Bash and most other shells.  

To get pasting to do the right thing, use readline-enabled PHP, and a modern terminal app, and enable bracketed paste (set `useBracketedPaste` to true in PsySH config).

**Comment by phil-s** [comment]
> Double newlines doesn’t fix the issue, though, it just defers it a bit :)

True, but I suspect it would account for the "manual typing" cases the vast majority of the time.

> And it makes closing brackets inconsistent with the way PsySH works the rest of the time.

Also true, so it would definitely be an opt-in feature for that reason.

> If you end the line with a \ it will let PsySH know that you wish to continue your code on the next line

That I did not know.  Still, in cases when I was mindful of the issue, I've successfully used `} ... {`.  It's the cases where I've *forgotten* to take such steps that are the annoying ones.

> To get pasting to do the right thing, use readline-enabled PHP, and a modern terminal app, and enable bracketed paste

I think this issue in general and its various mitigations are probably worthy of a section in the manual. I can't see a Troubleshooting or FAQ section, but I can only presume that this would crop up for people on a fairly regular basis.

I do have something similar in place as it happens, so for me personally pasting is actually ok; but I do still manually type code into the repl from time to time, and was bitten by this on numerous occasions.

I actually implemented my double-newline suggestion in my own wrapper today, and I do think it works nicely, so I'd still recommend it as an enhancement.

**Comment by bobthecow** [comment]
I just pushed a naive implementation in `feature/require-newline-after-block`. It leaves all lines ending with `}` open, including functions and classes where there's no chance that the user intended to add an `else`. Try that out and let me know what you think?

After playing with it for a while, I don't think I love it. The inconsistency added between this and other input is strange, and it would be even worse if only input which _could_ have an `else` were left open.

**Comment by phil-s** [comment]
Excellent. That's pretty much how I had it working in practice in my wrapper.  The one other thing I did was to delete that extra continuation prompt if the second newline happened, as the output looked tidier that way.  I'm not sure whether that's simple to do at your end?  (My wrapper is filtering the inputs and outputs -- and completely faking this continuation -- so I don't actually know what's happening inside PsySH.)

Thank you for implementing it.  Even if removing the extraneous continuation prompt isn't possible/practical, I'd be glad to see this feature merged as-is -- I think that other people like myself will be grateful for the option, and won't mind the inconsistency (and I became accustomed to it very quickly).

The other approach you could consider is the require-a-semicolon-even-after-a-block option.  In a sense the `requireSemicolons` behaviour is already a bit odd/inconsistent in that some kinds of block require a semicolon (e.g. function definitions), and others do not (e.g. if statements);  so a variant which required a semicolon to end the input in all cases might well be considered an improvement from the consistency perspective.  (For clarity, I'm very much in favour of still offering this `requireNewlineAfterBlocks` option even if you decided to also implement this other approach.)

**Comment by jchook** [comment]
The `edit` command should solve this problem for pastes, for future readers.

**Comment by bobthecow** [comment]
Sorry, I’ve used this for a while and I can’t bring myself to love it, so I’m going to close the ticket. The inconsistency around when something will actually execute is too much to get over, and it makes everything feel unresponsive.
