### ISSUE TITLE
References behave differently on single line vs. multiple

### ISSUE THREAD

**Issue by cmounce** [bobthecow/psysh#498]
If I use references on a single line, they work as expected:
```
>>> $x = 1; $y = &$x; $y++; var_dump($x)
int(2)
=> null
```

But if I spread them out over different lines, I get a different result:
```
>>> $x = 1
=> 1
>>> $y = &$x
=> 1
>>> $y++
=> 1
>>> var_dump($x)
int(1)
=> null
```

Don't know if this is possible to fix, or if there's something fundamental about psysh that breaks references (and if it is unfixable, don't know if it's possible to detect it/warn the user).

**Comment by bobthecow** [comment]
Thank you for reporting this. It is a regression since v0.8.x. I've pushed a change that should fix it!
