### ISSUE TITLE
How do I reload the previous command into the prompt?

### ISSUE THREAD

**Issue by systemovich** [bobthecow/psysh#499]
With the regular PHP REPL, this can be done by pressing the "UP" arrow.

**Comment by bobthecow** [comment]
Also by pressing the up arrow :)

**Comment by systemovich** [comment]
I was using it in Git Bash in Windows. The Up arrow worked as expected in an Ubuntu virtual machine.

**Comment by bobthecow** [comment]
Right. You need a version of PHP compiled with readline or libedit in order for the arrow keys to work, and the one in Git Bash probably doesn't have it. I believe you can fix that with dlls, though I haven't done this myself, so I can't give specifics.

Alternatively, if you have `hoa/console` installed, it will polyfill some support for arrow keys and the like. If you're using phar installs, grab one of the ones with `-compat` in the name. If you're using Composer, run `composer require --dev hoa/console`.

**Comment by dakujem** [comment]
**Psysh** works very well in **Cmder** / **ConEmu** on Windows. Cmder is a perfect replacement for standard cmd.
