### ISSUE TITLE
>>> list($replyTo, ,) =

### ISSUE THREAD

**Issue by AidasK** [bobthecow/psysh#503]
>>> list($replyTo, ,) = $publisher->getChannel()->queue_declare(
...             '',
...             false,
...             false,
...             true,
...             true
...         );
PHP Error:  Call to a member function getLine() on null in /var/www/versions/1528116071/vendor/psy/psysh/src/CodeCleaner/ListPass.php on line 65

**Comment by bobthecow** [comment]
Thanks for reporting. This has been fixed in `develop` and will go out with the next release!
