### ISSUE TITLE
can't initiate psysh:  Failed opening required 'bin/check-requirements.php'

### ISSUE THREAD

**Issue by hansbogert** [bobthecow/psysh#510]
When I try to run psysh in a docker environment it fails with:

```
PHP Fatal error:  require(): Failed opening required 'bin/check-requirements.php' (include_path='.:/usr/share/php:/usr/share/pear') in phar:///home/customerpanel/psysh/.box/check_requirements.php on line 15
```
Same psysh.phar in same filesystem on the host (i.e. not in docker) works properly.

**Comment by corytheboyd** [comment]
Same thing happens for me

**Comment by bobthecow** [comment]
What docker image are you using?

**Comment by schnittstabil** [comment]
Ref: humbug/box#253

**Comment by bobthecow** [comment]
This should be fixed in the current release. Let me know if you're still having issues.
