### ISSUE TITLE
PhpParser\Parser is an interface, but new is called on it

### ISSUE THREAD

**Issue by elijah-z142** [bobthecow/psysh#513]
ParserFactory.php line 86 attempts to create an instance of "Parser" ("use PhpParser\Parser;"), however, PhpParser\Parser is an interface.

**Comment by bobthecow** [comment]
That line only gets run if `hasKindsSupport` is false, i.e. if there's no class called `\PhpParser\ParserFactory`. And _that_ is only true in PHP Parser v1.x. And in PHP Parser v1.x, `PhpParser\Parser` is a class, not an interface :)
