### ISSUE TITLE
CTRL+R support

### ISSUE THREAD

**Issue by digitall-it** [bobthecow/psysh#515]
One of the basic shell history navigation shortcuts is CTRL+R, to search history for partial matches. I use it all the time, but couldn't find in the documentation of psysh how to obtain it.

**Comment by bobthecow** [comment]
It works in PsySH as well, just like it does in bash.

If it's not working for you, you probably don't have readline (or libedit) enabled in your PHP install.

**Comment by digitall-it** [comment]
what's best of the two?

**Comment by bobthecow** [comment]
Whichever one you can get. They’re basically equivalent.

**Comment by bobthecow** [comment]
what does `\Psy\info()` inside a psysh session say?

**Comment by digitall-it** [comment]
```
=> [
     "PsySH version" => "v0.7.2",
     "PHP version" => "7.0.30",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => null,
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "pcntl" => [
       "pcntl available" => true,
       "posix available" => false,
     ],
     "readline" => [
       "readline available" => true,
       "readline enabled" => true,
       "readline service" => "Psy\Readline\Libedit",
       "readline library" => "EditLine wrapper",
     ],
     "history" => [
       "history file" => "/home/vagrant/.config/psysh/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => true,
       "custom matchers" => [],
     ],
   ]
```

**Comment by digitall-it** [comment]
By the way, TAB completion works. It's reverse-i-search that doesn't work. I'm on a Mac in a standard terminal. PsySH is installed in vagrant machine running CentOS 7 that I access using `vagrant ssh`. In the bash shell, reverse-i-search works. Should I try another keyboard shortcut?

**Comment by bobthecow** [comment]
It looks like libedit is to blame.

If you add `bind` to the end of `~/.editrc` then start psysh it'll dump your current libedit bindings.

On my local PHP install (with libedit rather than readline) it doesn't include `em-inc-search-prev`. Additionally, `^R` seems to be bound by default to `ed-redisplay` by default, which is definitely nothing like `reverse-i-search`.

Adding `bind "^R" em-inc-search-prev` to `~/.editrc` seems to fix it.

I guess, in answer to your previous question, readline is the best of the two :P

**Comment by digitall-it** [comment]
I've tried that, but to no avail. I press this keystroke all the time...

**Comment by bobthecow** [comment]
what do you see bound to `^R` if you add `bind` to your `~/.editrc` and launch psysh?

i imagine you'll have the same issue with `php -a`, right?

**Comment by bobthecow** [comment]
Closing as this due to inactivity. It also seems to be an environmental issue, and the libedit config I listed above fixed the issue for me. Please feel free to re-open if you think there's something more we can do on our end.

**Comment by hackel** [comment]
FYI, I also ran into this issue, and it turns out the cause was that CentOS 7 only has libedit 3.0 which doesn't support Ctrl-R searching or .editrc at all.  I had to compile and install libedit 3.1 from CentOS 8 to get it to work.  Very frustrating indeed!
