### ISSUE TITLE
Unable to call 'ls' on class with a constant

### ISSUE THREAD

**Issue by garret-gunter** [bobthecow/psysh#516]
When calling `ls` on an class with a constant an exception is thrown about the constant not existing.  The error reported is `ReflectionException with message 'Class Constant ReflectionObject::TEST does not exist.`  I tested it with both a namespaced class and a global class.  Psysh has worked just fine until recently.

Here are the classes I tested with.  

```php  

namespace App;

/**
 * Class FooClass
 *
 * @package App
 */
class FooClass {

	public const TEST = 'something';

}

```  

```php  

/**
 * Class FooClass
 */
class FooClassGlobal {
	public const TEST = 'something';
}

```  
 
The exception was thrown with this code.  
```php
>>> $foo = new \FooClassGlobal();
=> FooClassGlobal {#3800}
>>> ls $foo
ReflectionException with message 'Class Constant ReflectionObject::TEST does not exist'
```
```php
>>> $foo = new \FooClass();
[!] Aliasing 'FooClass' to 'App\FooClass' for this Tinker session.
=> App\FooClass {#3800}
>>> $foo = new \FooClassGlobal();
PHP Fatal error:  Class 'FooClassGlobal' not found in Psy Shell code on line 1
```

I've tried a couple things to fix the issue.  

*  I've dumped composer's autoload.  
*  Cleared any application caches.  (Should not be relevant, but I did anyway. )  
*  Removed composer's vendor directory and reinstalled packages.  
*  Rolled back to previous composer.lock version.  

Environment:  
*  PHP 7.2.8
*  Laravel 5.5.41  
*  Ubuntu 16.04

**Comment by bobthecow** [comment]
Thanks for reporting! This has been fixed and will go out in the next release.
