### ISSUE TITLE
instanceof syntax check does not work for arrays

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#519]
More of a curiosity than a bug, really.

    Psy Shell v0.9.7 (PHP 7.0.30-0ubuntu0.16.04.1 — cli) by Justin Hileman
    >>> false instanceof StdClass
    PHP Fatal error:  instanceof expects an object instance, constant given in Psy Shell code on line 1
    >>> [] instanceof StdClass
    PHP Fatal error:  instanceof expects an object instance, constant given in phar:///home/tgr/bin/psysh/src/ExecutionLoopClosure.php(53) : eval()'d code on line 1

**Comment by tgr** [comment]
OK, that wasn't very helpful... so the first error is from PsySH's syntax checker (red background, does not break history), the second is a real PHP fatal (plain background, breaks history).

**Comment by bobthecow** [comment]
yeah, it looks like [our list of "valid" `instanceof` calls](https://github.com/bobthecow/psysh/blob/4f5b6c090948773a8bfeea6a0f07ab7d0b24e932/test/CodeCleaner/InstanceOfPassTest.php#L61-L67) isn't quite right.

`array(1) instanceof stdClass`, `(1+1) instanceof stdClass` and `DateTime::ISO8601 instanceof stdClass` all fail.

**Comment by bobthecow** [comment]
This has shipped with v0.10.0
