### ISSUE TITLE
ls project files (psysh installed globaly)

### ISSUE THREAD

**Issue by lov3catch** [bobthecow/psysh#520]
H!!
How I can reflect objects in my project if psysh are installed globaly?

I try (for example):
```
use App\User;
$u = new User();
```
And get error: PHP Fatal error: Class not found in Psy Shell code on line 1

If install psysh into project - all is work.

**Comment by bobthecow** [comment]
When installed as a project dependency, psysh automatically includes composer autoload, so if your project is also using composer autoload, it just works as you'd expect.

If you're using a globally installed psysh, you can get this same behavior by [requiring Composer autoload to your psysh config file](https://github.com/bobthecow/psysh/wiki/Configuration#automatically-load-composer-dependencies)… or by adding whatever other autoloading you want :)

**Comment by lov3catch** [comment]
Oh, thanx!
