### ISSUE TITLE
Support for binary literals

### ISSUE THREAD

**Issue by peterchaula** [bobthecow/psysh#522]
![image](https://user-images.githubusercontent.com/13304490/45262651-315b8c00-b41b-11e8-8edb-72c12730c136.png)

The parser doesn't seem to recognise binary literals

**Comment by bobthecow** [comment]
Did you mean to type `0b10` and `0b10*2`?

**Comment by peterchaula** [comment]
My bad. Sorry!

**Comment by bobthecow** [comment]
Hey, no worries :)
