### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by okj579** [bobthecow/psysh#524]
I downloaded the Phar via wget and when running it with php 5.6 get a simple "Segmentation fault".
With 7.1 and 7.2 I get the following error:
```
PHP Fatal error:  require(): Failed opening required 'bin/check-requirements.php' (include_path='.:/usr/share/php:..') in phar:///www/htdocs/w0175945/psysh/.box/check_requirements.php on line 15

Fatal error: require(): Failed opening required 'bin/check-requirements.php' (include_path='.:/usr/share/php:..') in phar:///www/htdocs/w0175945/psysh/.box/check_requirements.php on line 15
```

**Comment by bobthecow** [comment]
This is probably #510 which is https://github.com/humbug/box/issues/253 which seems to be fixed by https://github.com/humbug/box/pull/284 so the next build of psysh
