### ISSUE TITLE
Use declarations are ignored for built-in commands

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#547]
```
Psy Shell v0.9.9 (PHP 7.0.32-0ubuntu0.16.04.1 — cli) by Justin Hileman
>>> namespace Foo
>>> use \stdClass as Bar
>>> new Bar()
=> {#2309}
>>> doc Bar
InvalidArgumentException with message 'Unknown class or function: Bar'
>>> ls Bar
InvalidArgumentException with message 'Unknown class or function: Bar'
>>> 
```

**Comment by bobthecow** [comment]
Thank you for reporting this! It's fixed in `develop` and will go out with the next release.

<img width="762" alt="screen shot 2019-01-26 at 2 33 10 pm" src="https://user-images.githubusercontent.com/53660/51794121-edc2ae00-2180-11e9-9c53-7c90b38e1d40.png">
