### ISSUE TITLE
VIM Mode

### ISSUE THREAD

**Issue by henrikbjorn** [bobthecow/psysh#55]
Psysh is great! But i find i mingle stuff up because i cant use my normalt vim bindings and mode as in my normalt terminal.

**Comment by still-dreaming-1** [comment]
@henrikbjorn I have found using psysh from inside [vimshell](https://github.com/Shougo/vimshell.vim) to work really well. Then you will truly have Vim keybindings.

**Comment by JesseLeite** [comment]
Awesome thanks for tip!  Having trouble binding `ESC` to `jk` in my .inputrc file though.  Any of you doing this?
