### ISSUE TITLE
 Call to undefined method Symfony\Component\Console\Helper\QuestionHelper::getInputStream()

### ISSUE THREAD

**Issue by marcosdipaolo** [bobthecow/psysh#551]
```
In Application.php line 895:
Call to undefined method Symfony\Component\Console\Helper\QuestionHelper::getInputStream()
```
This is when trying to launch psysh after I installed doctrine ORM package. 
It's relevant to mention that psysh is installed globally, configured to load vendor/autoload if there's any, and that everything goes ok until doctrine/orm is installed.

**Comment by bobthecow** [comment]
If you're using PsySH installed via Phar, it might conflict with locally installed versions of Symfony\Console. Adding `psy/psysh` as a dev dependency in Composer should fix it!

**Comment by bobthecow** [comment]
Did this work for you? Feel free to re-open if you're still running into the issue.

**Comment by marcosdipaolo** [comment]
Hi Justin, in the end it wasn't a problem neither of psysh nor doctrine orm. I don't remeber clearly now but i think i uninstalled another dependency and everything went back to normal. Thanks a lot .

**Comment by bobthecow** [comment]
Glad you got it sorted out!
