### ISSUE TITLE
Check ownership of history file

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#552]
libedit apparently refuses to save the history (returns false from `readline_write_history`) if the history file is not owned by the user, even if it is writable. It would be nice if psysh would warn about this on startup (currently it only warns about the file not being writable) - with the total lack of error reporting in libedit/readline, it is frustrating to debug.

**Comment by bobthecow** [comment]
does it _always_ refuse to write, or just on some operating systems or implementations? should we detect the return false and warn about it then?

**Comment by tgr** [comment]
Ubunut Xenial and Debian Stretch are the ones where I can test easily and those both do it. I didn't find it documented anywhere but then documentation for libedit is not great in general.
Yeah, checking file permissions on return false seems the most robust.

**Comment by bobthecow** [comment]
I was able to reproduce this on macOS as well. I've added a warning when it happens :)
