### ISSUE TITLE
Make history file location configurable

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#554]
Currently there does not seem to be any way to store the history file outside the configuration directory. I'm trying to improve the usability of psysh in a multi-user environment, where users have to sudo to www-data to run PHP scripts, to avoid permission problems. I want every user to have a separate history file since otherwise weird accidents happen when people do debugging simultaneously; but don't want everyone to have separate config files.

It would be great if there was a configuration option on where to put history files (or, more generally, the kind of files you would put under `/var` on linux - files which are managed by the application and not by the user).

**Comment by bobthecow** [comment]
You can do this! You have access to the `Configuration` object in your config file, and your config file is PHP so you can do basically anything:

```php
<?php

$config->setHistoryFile(‘whatever’ . $code . $you->want());
```
