### ISSUE TITLE
Invalid 'Only variables can be passed by reference' fatal when using array unpacking

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#558]
$ psysh
    Psy Shell v0.9.9 (PHP 7.2.15-0ubuntu0.18.04.2 — cli) by Justin Hileman
    >>> $a = [1, 2];
    >>> end( $a );
    => 2
    >>> end( ...[$a] );
    PHP Fatal error:  Only variables can be passed by reference in Psy Shell code on line 1

The official PHP docs on array unpacking are spotty but [the RfC makes it clear](https://wiki.php.net/rfc/argument_unpacking#by-reference_passing) that this is a valid pattern. ([3v4l](https://3v4l.org/RIGYo) - works in all PHP versions, although HHVM gets it wrong.)

**Comment by tgr** [comment]
I like to use this as a workaround for not having a normal "last element of the array" method in PHP, and currently PsySH gets that exactly backwards:

    >>> end( explode( '.', 'foo.png' ) );
    PHP Notice:  Only variables should be passed by reference in phar://eval()'d code on line 1
    >>> end( ...[explode( '.', 'foo.png' )] );
    PHP Fatal error:  Only variables can be passed by reference in Psy Shell code on line 1
    >>> eval( "return end( ...[explode( '.', 'foo.png' )] );" );
   => "png"

so the invalid syntax is let through but the valid syntax is blocked. (Although it's not 100% clear from the RFC whether this is still intended to be valid or just a bug and the expression the spread is applied to is supposed to be a variable.)

**Comment by bobthecow** [comment]
Thank you for reporting this. The false positive fatal error is fixed in #37f8dac.

The warning for function, method or static calls is just a warning, so PsySH lets it through and expects PHP to sort it out :)
