### ISSUE TITLE
Lock down symfony/console version or supply a newer version

### ISSUE THREAD

**Issue by supriyo-biswas** [bobthecow/psysh#559]
When I run psysh's `help` command, with symfony/console v4.2.7, I get this error:

``` 
→ psysh
Psy Shell v0.9.9 (PHP 7.2.16 — cli) by Justin Hileman
>>> help
ErrorException with message 'The "Symfony/Component/Console/Helper/TableStyle::setVerticalBorderChar()" method is deprecated since Symfony 4.1, use setVerticalBorderChars() instead. at /home/supriyo/myproject/vendor/symfony/console/Helper/TableStyle.php:171'
```

Can we have a newer version of symfony/console in psysh, or if that's not possible, lock down to a specific symfony/console version?

**Comment by bobthecow** [comment]
Thanks for reporting. This has been fixed in 1569957, and will go out in the next stable release.
