### ISSUE TITLE
Imports shadow namespaces even with global prefix `\`

### ISSUE THREAD

**Issue by edudobay** [bobthecow/psysh#562]
I think I might have found a bug. I've found that imports (`use X`) shadow namespace prefixes, when the first component of the namespace matches a name that has already been imported. The following gist illustrates this situation:

https://gist.github.com/edudobay/8da9e26d5720798cc76fc7e85b5b735e

If `index.php` is run directly with PHP (version 7.3.6 here) or with PsySH via the CLI (`psysh index.php`), the program executes normally, printing the Carbon object.

If the code is typed into the PsySH REPL (directly into the REPL or via an external editor using the `edit` command), we get an error showing that the imported class has shadowed the `\Carbon` namespace:

```
PHP Fatal error:  Class 'Carbon/Carbon/CarbonTimeZone' not found in Psy Shell code on line 6
```

The same thing happens if we alias-import a different class, e.g.:

```php
use Carbon\CarbonImmutable as Carbon;
```
in which case the error message will point out that `CarbonTimeZone` was interpreted as `Carbon\CarbonImmutable\CarbonTimeZone`.

**Comment by bobthecow** [comment]
Thank you for reporting this issue. It has been fixed in 17ed529 and will go out with the next stable release.
