### ISSUE TITLE
PHP 7.4 ErrorException with message 'Unbinding $this of closure is deprecated'

### ISSUE THREAD

**Issue by HepplerDotNet** [bobthecow/psysh#567]
Running php artisan tinker on PHP 7.4 beta4
Throws:
ErrorException with message 'Unbinding $this of closure is deprecated'

**Comment by GrahamCampbell** [comment]
This will be resolved in PHP 7.4 RC1.

**Comment by GrahamCampbell** [comment]
In fact, it was resolved yesterday.

**Comment by bobthecow** [comment]
Feel free to re-open if this still is a problem!
