### ISSUE TITLE
Psy Shell dies on first input on OSX with PHP 7.3.10

### ISSUE THREAD

**Issue by xmacex** [bobthecow/psysh#574]
Hi

On OSX with PHP 7.3.10 Psysh v0.9.9 crashes silently on first input. It works fine on another machine I tried, which is a GNU/Linux. I really like what Psysh does, and I really think it is making PHP a whole lot more fun and I wish we always had such a nice REPL thing for PHP. So thanks 🐚 .

Anyway, here is my session with it:

```sh
howdonamesevenwork:~ $ psysh
Psy Shell v0.9.9 (PHP 7.3.10 — cli) by Justin Hileman
>>> $kittens = "mittens";
howdonamesevenwork:~ $ _
```

Where can I get more information, so that this bug report could be productive and helpful? Maybe I can contribute? Does psysh produce some log files or is there a debug mode (I tried `--debug`).

**Comment by bobthecow** [comment]
This is a bug in Homebrew(?) PHP + PCRE2 + PCNTL. See #540 

It's been an issue for a while. The workaround for now is to disable JIT for PCRE by adding `pcre.jit=0` to your `php.ini`.

**Comment by bobthecow** [comment]
I pinned the other issue so it'll be more visible to everyone else :)

**Comment by xmacex** [comment]
Thank you @bobthecow that solved it 🏅 . I created the following `/usr/local/etc/php/7.3/conf.d/psysh-540-workaround.ini`:

```
# https://github.com/bobthecow/psysh/issues/540
# https://github.com/bobthecow/psysh/issues/574#issuecomment-545584408
pcre.jit = 0
```
