### ISSUE TITLE
DateTime::getLastErrors() result cleared if not invoked immediately 

### ISSUE THREAD

**Issue by sserbin** [bobthecow/psysh#576]
It seems that `DateTime::getLastErrors()` yields correct results only If you invoke `getLastErrors()` immediately after constructing a `DateTime`.

Here everything's as expected:
```php
>>> $dt = new DateTime('2019-02-30');$dt::getLastErrors();
=> [
     "warning_count" => 1,
     "warnings" => [
       11 => "The parsed date was invalid",
     ],
     "error_count" => 0,
     "errors" => [],
   ]
```

And here, `getLastErrors()` returns empty result set.
```php
>>> $dt = new DateTime('2019-02-30');
=> DateTime @1551477600 {#2337
     date: 2019-03-02 00:00:00.0 Europe/Helsinki (+02:00),
   }
>>> $dt::getLastErrors();
=> [
     "warning_count" => 0,
     "warnings" => [],
     "error_count" => 0,
     "errors" => [],
   ]
```

**Comment by bobthecow** [comment]
Unfortunately this is a collision of a couple of factors, and there's not much we can do about this :-/

First, `DateTime::getLastErrors` is global mutable state. You can't get errors on `$dt`, you can only get errors on the last time `DateTime` parsing happened.

Second, the result from your last eval'd input is printed using userland PHP. If anywhere in that output we call `new \DateTime`, it'll reset that global mutable state and clear out your errors. In fact, that's exactly what Symfony VarDumper does: https://github.com/symfony/var-dumper/blob/master/Caster/DateCaster.php#L31

As a workaround, you don't have to call `DateTime::getLastErrors` immediately. You just need to prevent any DateTime instances from being printed before calling it. One way to do this is to return anything else besides that new DateTime from your input:

```php
>>> $dt = new DateTime('2019-02-30');null
=> null
>>> DateTime::getLastErrors()
=> [
     "warning_count" => 1,
     "warnings" => [
       11 => "The parsed date was invalid",
     ],
     "error_count" => 0,
     "errors" => [],
   ]
```

**Comment by sserbin** [comment]
Thanks, @bobthecow 

>  You can't get errors on $dt, you can only get errors on the last time DateTime parsing happened.

sure, this was just an example from elsewhere.

>  If anywhere in that output we call new \DateTime, it'll reset that global mutable state and clear out your errors. __In fact, that's exactly what Symfony VarDumper does__

aha, that's something I didn't think about. I thought there might be something more intricate involved here :) Thanks for clarifying this!
