### ISSUE TITLE
PHP-Scoper incorrectly scopes `\ReflectionClassConstant`

### ISSUE THREAD

**Issue by bobthecow** [bobthecow/psysh#581]
`ReflectionClassConstant::create` tries to decide whether to create an instance of the actual `\ReflectionClassConstant`, or our ponyfill. When trying to re-enable `PHP-Scoper` it was incorrectly scoping that class name, which caused test failures:

```php
    public static function create($class, $name)
    {
        if (\class_exists('_HumbugBox4f95cd3d5edb\\ReflectionClassConstant')) {
            return new \ReflectionClassConstant($class, $name);
        }
        return new self($class, $name);
    }
```

cc @theofidry

**Comment by theofidry** [comment]
Maybe it should be fixed via a patched; Also maybe PhpScoper should be
enabled for the most cutting edge PHAR and omit it for the others where you
include various polyfills

**Comment by bobthecow** [comment]
In this case, the ReflectionClassConstant bit is part of PsySH core and is in everything, not optionally just in compatibility builds.

This feels like it might be a bug in PHP Scoper, tbh. the original code was

```php
if (\class_exists('\\ReflectionClassConstant')) {
  // ...
```

… which couldn't be anything but a reference to an internal class.

**Comment by theofidry** [comment]
Hm indeed

**Comment by bobthecow** [comment]
@theofidry is there an easy way to work around this on our end while we're waiting for the issue in PHP Scoper to be resolved?

**Comment by theofidry** [comment]
Yes, by relying on a [patcher](https://github.com/humbug/php-scoper#patchers)
