### ISSUE TITLE
Removing broken tutorial link

### ISSUE THREAD

**Issue by peter279k** [bobthecow/psysh#606]
The [link](http://www.stillat.com/blog/2016/08/16/becoming-a-laravel-rock-star-with-artisan-tinker/) has been broken and returns `404 not found` on [Tutorials](https://github.com/bobthecow/psysh/wiki/Tutorials/8fdbbcd4fe168bc7e15fbbf66c723f363fe80601) section wiki page.

**Comment by peter279k** [comment]
done.

**Comment by bobthecow** [comment]
Thanks!
