### ISSUE TITLE
Allow Custom Color Configuration

### ISSUE THREAD

**Issue by ooglek** [bobthecow/psysh#608]
Symphony OutputFormatter allows you to override the colors for errors and such.

https://github.com/symfony/console/blob/d487d68fd7e85e2d3fc5cc69e41d66edd15cec1e/Formatter/OutputFormatter.php#L62-L76

Because it is used statically in `formatException` there is a missed opportunity to override these default colors.

https://github.com/bobthecow/psysh/blob/6f608b7b1cdb56861e1590ff6075e1602cafe800/src/Shell.php#L1039

Why does this matter? The default on my screen, black background and green text (yeah, I'm old), the error is virtually unreadable with "white text on red background." In my ANSI setup, "white" is light gray and "bold white" is white white.

It'd be great to make this user-configurable.

<img width="436" alt="Screen Shot 2020-03-02 at 11 44 15 PM" src="https://user-images.githubusercontent.com/100755/75743684-cc1aeb00-5cdf-11ea-8c0e-0e64d2921709.png">

Bonus Points: it'd be nice to change the default colors too.

https://github.com/bobthecow/psysh/blob/6f608b7b1cdb56861e1590ff6075e1602cafe800/src/ConsoleColorFactory.php#L49-L58

**Comment by bobthecow** [comment]
I'm with you. I prefer black text on red background. That's what PsySH used for the longest time. But that also doesn't work for a bunch of people, which is why it changed.

I just pushed a commit to the `master` branch that adds `formatterStyles` to the config options. If you install `@dev` via Composer, you will get that version and be able to play around with it.

Adding something like this to `~/.config/psysh/config.php` should do it:

```
return [
    'formatterStyles' => [
        // name => [fg, bg, [options]]
        'error' => ['black', 'red', ['bold']],
    ],
];
```

**Comment by ooglek** [comment]
I'd like to test this but the instructions for checking it out of Git and building it leaves me with a script in `bin/psysh` that is not all-in-one-self-contained.

Do you mind posting instructions for how to build a portable version? Or throw a Makefile in there... :-)

**Comment by bobthecow** [comment]
It’s in the current release now, so you can upgrade and just use that :)

**Comment by bobthecow** [comment]
Also, there’s a Makefile! 😁

**Comment by ooglek** [comment]
HOLY CRAP there is. I'm blind. Sorry! 

Do you need to run `gmake dist` or can you target just the most-recent portable version?

Got the latest, it's working! One error I found, not handling exceptions.

I put in "normal" in the options list, and this failed (invalid value). However `psysh` crashed because it was attempting to re-read config.php and it hit a function I defined there and threw a "Cannot redeclare myfunc()" and crashed. This was odd. You might want to add some validation for formatterStyles to make sure the user doesn't totally break psysh unwittingly and without knowing why.

Likely a simple `try { } catch` around `new OutputFormatterStyle` will catch the errors thrown by Symphony.

I wish `OutputFormatterStyle` would make the definitions of the colors accessible, so when throwing an exception you could iterate through the list of valid colors and save the user some hassle looking up what valid values are. (Yes, I see `normal` is not a valid value)

Thanks!

**Comment by bobthecow** [comment]
The error message does list the valid colors (at least with the version of Symfony I'm currently testing against):

> Invalid background color specified: "redd". Expected one of (black, red, green, yellow, blue, magenta, cyan, white, default).

I don't know about swallowing errors and continuing. I mean, the current experience far from ideal, but it's pretty clear what went wrong:

<img width="1130" alt="Screen Shot 2020-04-08 at 2 24 17 PM" src="https://user-images.githubusercontent.com/53660/78835216-a3ec6f00-79a4-11ea-91e7-0b34f3305608.png">

Part of the difficulty is that during the "parse config" stage, we don't even have a Shell instance running, so we can't really log errors and continue. I'll think for a bit about how to provide a better. I'd also appreciate your thoughts :)

**Comment by bobthecow** [comment]
I'm also planning to update documentation and add examples so nobody has to figure it out by trial and error :)

**Comment by ooglek** [comment]
Try adding a function to your config.php  and re-run with the bad option (not a bad color) --

```
function hiBob() {
  // do nothing
  return true;
}
```

I got this in my php-errors, not the beautiful fatal error:
```
[08-Apr-2020 20:08:34 UTC] PHP Fatal error:  Cannot redeclare tdgo() (previously declared in /usr/home/beckman/.config/psysh/config.php:12) in /usr/home/beckman/.config/psysh/config.php on line 12
```

I suspect that the error may be causing `config.php` to be re-read, attempting to redeclare a function, thus hiding the fatal error that would have indicated where I messed up.

**Comment by bobthecow** [comment]
Ahh, I see what's happening.

As of the latest release, we added more robust command line option parsing, namely this:

https://github.com/bobthecow/psysh/blob/963ff8bae790afb2032ae02ce7e474f115c84ac8/src/functions.php#L335-L340

What it's _supposed_ to be doing is creating a Configuration object with your command line options, catching any errors those options throw, and falling back to a default Configuration object (which surely can't fail... right?).

But in your case, the failure is in the config file, not the command line options, so when we swallow the original error and try again, the second one fails too, but this time with a "you already defined this function" error, not the error which caused the config failure to begin with.

We _could_ solve it by falling back to not creating a Configuration object when creating the Shell at all, but funny story:

https://github.com/bobthecow/psysh/blob/963ff8bae790afb2032ae02ce7e474f115c84ac8/src/Shell.php#L82-L84

... if we did that, we'd just trigger the error again a split second later when we tried to initialize the Shell :-/ 

At the very least, you should be defensively defining that function in your config file by wrapping it in `if (!\function_exists('...')) ...`. We absolutely will require that file more than once. For example, if you launch a shell multiple times in a single web request to look at state in different places, we'll need to initialize configuration for each one, which would mean re-requiring that file.

As for what to do about the configuration error explosion, I'll think about that :)

**Comment by bobthecow** [comment]
Alright, got it. The next release won't have cascading config failures anymore!

**Comment by bobthecow** [comment]
I also added a note to the Configuration page in the wiki about defensively defining things in your config:

https://github.com/bobthecow/psysh/wiki/Configuration#define-things-defensively
