### ISSUE TITLE
Class not found exception in v0.10.0 w/ php 7.4

### ISSUE THREAD

**Issue by ju1ius** [bobthecow/psysh#610]
Hi,

Using php 7.3:
```
> php7.3 ./psysh-0.10.0
Psy Shell v0.10.0 (PHP 7.3.15-3 — cli) by Justin Hileman
>>> $a = ''
=> ""
>>> 
```

Using php 7.4:
```
> php7.4 ./psysh-0.10.0
Psy Shell v0.10.0 (PHP 7.4.3 — cli) by Justin Hileman
>>> $a = ''
PHP Error:  Class '_HumbugBoxa633f5ba8717/ReflectionReference' not found in phar:///path/to/psysh-0.10.0/vendor/symfony/var-dumper/Cloner/VarCloner.php on line 46
>>> 
```

**Comment by bobthecow** [comment]
Thanks for reporting this!

@theofidry Looks similar to #581?

https://github.com/symfony/var-dumper/blob/v5.0.5/Cloner/VarCloner.php#L68-L70

**Comment by theofidry** [comment]
Indeed, will check that one this week

**Comment by bobthecow** [comment]
Sorry @ju1ius. This is a bug in one of the libraries we use to compile the pre-built binary. For now, the workaround is using either a local or global composer install instead.

**Comment by bobthecow** [comment]
@ju1ius This should be fixed as of (the just released) v0.10.1. Please let me know if you see any further issues!

**Comment by bobthecow** [comment]
Oh, sorry, it's still broken. I tested locally and thought I'd fixed it, but I had PHP 7.2 linked 😬

**Comment by bobthecow** [comment]
Okay _now_ it should be fixed. Let me know otherwise :)

**Comment by ju1ius** [comment]
Fixed it is.
Thanks !
