### ISSUE TITLE
Tidelift

### ISSUE THREAD

**Issue by GrahamCampbell** [bobthecow/psysh#619]
[Tidelift](https://tidelift.com/) will give you $417/month (before income tax) to maintain this package btw @bobthecow. ;)

**Comment by bobthecow** [comment]
Huh. Do you know anyone doing it?

**Comment by GrahamCampbell** [comment]
Yeh, me for my packages. Been with them for around 9 months. The income so far as been exactly what they estimated, to the cent. They pay through a PayPal owned company: Hyperwallet.

**Comment by GrahamCampbell** [comment]
There's no referral bonus for me or anything. I just thought you might wanna check it out, since there's basically no obligations beyond what you are already doing to get started and paid. ;)
