### ISSUE TITLE
Command input without a PTY no longer works in 0.10

### ISSUE THREAD

**Issue by phil-s** [bobthecow/psysh#621]
There's probably a method that doesn't need ssh, but for instance try this with both 0.9 and 0.10:

    ssh localhost -T -C /path/to/psysh

In 0.9:
```
Psy Shell v0.9.12 (PHP 7.2.24-0ubuntu0.18.04.3 — cli) by Justin Hileman
New version is available (current: v0.9.12, latest: v0.10.2)
42
=> 42
"hello"
=> "hello"
^C
```

In 0.10:
```
Psy Shell v0.10.2 (PHP 7.2.24-0ubuntu0.18.04.3 — cli) by Justin Hileman
42   
"hello"
PHP Parse error: Syntax error, unexpected T_CONSTANT_ENCAPSED_STRING on line 2
Exit:  Exiting main thread
```

My interface connects to the psysh process via a pipe rather than a pty, so this has bitten me in practice, and I've downgraded to 0.9 in the interim.

**Comment by phil-s** [comment]
Ah, so this is the new `--no-interaction` option implicitly kicking in.  If I run `psysh --no-interaction` in a terminal in the normal way, I get the same 'problem' behaviour.

**Comment by phil-s** [comment]
I can't see a config file option for this.  A new config file option which forces the normal "interaction" behaviour would be perfect.

Tangentially, the `--help` text is missing `--no-interaction` and all the other new options listed in the release notes:
```
Psy Shell v0.10.2 (PHP 7.2.24-0ubuntu0.18.04.3 — cli)

Usage:
  psysh [--version] [--help] [files...]

Options:
  --help     -h Display this help message.
  --config   -c Use an alternate PsySH config file location.
  --cwd         Use an alternate working directory.
  --version  -V Display the PsySH version.
  --color       Force colors in output.
  --no-color    Disable colors in output.
```

Perhaps that help could be brought up to date?

**Comment by bobthecow** [comment]
Yeah, something’s not quite right with non-interactive input right now. I’ll dig into it and see what’s up.

In the meantime, I’m pushing a fix for the `--help` output :)

![CC0F4FA4-3234-473A-82BF-61818100A1F5](https://user-images.githubusercontent.com/53660/78382555-e9b3cc80-758b-11ea-9bf1-aeb60e371564.jpeg)

**Comment by bobthecow** [comment]
Looking at your use case, I think we’ll need a flag for “force interactive mode”? I’m assuming you’re piping input as well as output?

**Comment by phil-s** [comment]
That's right, and yes, I believe a flag to force interaction is the solution here.

I think a command-line option could be warranted, but in my particular case a config file option would be preferable, as I can then configure that without caring about which version of `psysh` ends up being invoked (as it will complain about an unrecognised command-line option, but not about an unrecognised config file option, and so I could safely use the same config everywhere).

This might be analogous to the colour support, with off/on command-line options, and the disabled/auto/forced config file option?

**Comment by bobthecow** [comment]
@phil-s I think I've got a little fix for you. See #622 :)

I'd appreciate if you could try it out and let me know if you run into any issues before I merge it.

**Comment by phil-s** [comment]
Oh wow, you've done a lot there!  Thank you; I will definitely give it a whirl and let you know how I get on.  (Hopefully that will be sometime tomorrow.)

**Comment by phil-s** [comment]
I've done some cursory testing with the `feature/better-plumbing` branch, and it looks good.  As far as I can tell, setting `'interactiveMode' => 'forced'` in my config file definitely resolves the problem, as does using  `--interaction` on the command-line.  I haven't used it much yet otherwise, but possibly don't need to for the purposes of this issue.  Let me know if there's anything particular that you'd like me to try.

**Comment by bobthecow** [comment]
Nah, you should notice right away if it’s back to normal. Thanks for checking!

One thing I’d be interested in knowing is if there’s a better heuristic for “interactive-ish despite not being a tty” that would prevent you from having to specify explicitly.

**Comment by phil-s** [comment]
I can't suggest any better heuristic, sorry.  For my part I'm happy to use the new configuration (and my default config now includes it, so I won't need to set it manually anywhere).

The only question that springs to mind (now -- I do wish I'd thought to query it before) is whether the *automatic* behaviour for something used primarily as a shell should *ever* default to a non-interactive mode?  Maybe that's the wrong thing to do, and it should instead be up to the program *using* psysh to tell it explicitly to do that?

That might be the less-surprising approach and, as a relatively recent feature, it might not be too late to impose such a change; but I'm not sure what the non-interactive use-cases are, so perhaps it would merely be creating similar issues for a bunch of other people.

(I'll be happy with it either way, though. :)

Thanks again for the very quick fix!

**Comment by phil-s** [comment]
(I suppose this should be open until the branch is merged, so just re-opening for that.)
