### ISSUE TITLE
Console Highlighter Deprecated

### ISSUE THREAD

**Issue by PeterDKC** [bobthecow/psysh#624]
It seems the author of https://packagist.org/packages/jakub-onderka/php-console-highlighter has moved his packages around and deprecated a couple? Just started getting this today:

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
```

```
composer depends jakub-onderka/php-console-highlighter
psy/psysh  v0.10.2  requires  jakub-onderka/php-console-highlighter (0.4.*|0.3.*)
```

I'll be honest I have no idea what it would take to switch to his suggested packages. 

https://packagist.org/packages/php-parallel-lint/php-console-color
https://packagist.org/packages/php-parallel-lint/php-console-highlighter

But that seems to be what's necessary to clear the warning. Ideally they're just drop in replacements?...

**Comment by bobthecow** [comment]
It’s already fixed in `master`. You can switch to `@dev` if you need it right now, otherwise it’ll land in the next stable release.

**Comment by PeterDKC** [comment]
Ah, very good. Just wanted to make sure you were aware. 🙇 I'll wait for next.
