### ISSUE TITLE
Delete develop branch

### ISSUE THREAD

**Issue by GrahamCampbell** [bobthecow/psysh#625]
Asking for `0.10.*@dev` downloads the develop branch instead of master...

**Comment by bobthecow** [comment]
:-/

I did when I first switched over to master-based development, but brought it back so I could reopen a couple of pull requests that seemed still valid.

**Comment by GrahamCampbell** [comment]
Could you at least sync up the develop branch with master then, perhaps?

**Comment by GrahamCampbell** [comment]
This hack shouldn't be necessary:

![image](https://user-images.githubusercontent.com/2829600/78580360-361c3800-782a-11ea-9005-52c265d896d8.png)

**Comment by bobthecow** [comment]
Would removing the branch alias from composer.json in the dev branch fix it?

**Comment by bobthecow** [comment]
Okay, I pushed master to develop, which both makes it up to date, and removes the branch alias from `composer.json`. Feel free to reopen if this doesn't resolve your issue!

**Comment by GrahamCampbell** [comment]
Great. I think develop not having the branch alias too will do the trick, since now packagist will only see master as being alised to 0.10.
