### ISSUE TITLE
The effects of running exec programs that open up a whole new terminal.

### ISSUE THREAD

**Issue by CMCDragonkai** [bobthecow/psysh#63]
Try this:

```
exec('nano randomfile');
```

It does actually work. And you can edit the file. However you can't see what you're doing.

Would it even be possible to replicate how it works in Bash?

**Comment by zachflower** [comment]
I just stumbled upon this issue and—while I'm not exactly sure how to _automatically_ compensate for the problem within psysh—this can be accomplished manually by piping the output of the command directly into the current login session, like so:

    exec('nano randomfile > `tty`')

**Comment by bobthecow** [comment]
I was never able to come up with something that worked here. Feel free to reopen if you have any ideas :)
