### ISSUE TITLE
php artisan tinker produces error: ThrowUp no longer needs to be ContextAware

### ISSUE THREAD

**Issue by ImSeaWorld** [bobthecow/psysh#632]
I've very recently started working with laravel, checking out tinker I ran into an issue that Google could only find obscure websites with vague mention of my query. Appreciate any help :)

``...\api\vendor\psy\psysh\src\Command\ThrowUpCommand.php:58
      trigger_error("ThrowUp no longer needs to be ContextAware")``

Error from ``src\Shell.php`` Line 143

Specs
```
Win 10 Pro (18362.720)
psysh v0.10.3
PHP 7.3.3 (cli) (built: Mar  6 2019 21:53:02) ( NTS MSVC15 (Visual C++ 2017) x64 )
Zend Engine v3.3.3
with Xdebug v2.7.0
```

**Comment by bobthecow** [comment]
Thanks for reporting. This will be fixed in the next stable release.

In the meantime, you can update your `psy/psysh` dependency in Composer to `@dev`, or you can turn down your error reporting level so it stops making noise :)
