### ISSUE TITLE
Undefined constant 'STDIN' in v0.10.3

### ISSUE THREAD

**Issue by NateWr** [bobthecow/psysh#634]
I'm receiving the following error when using `eval(\Psy\sh())` with the built-in server.

```
In Configuration.php line 1721:
                              
  Undefined constant 'STDIN'  
                              
```

This error no longer appears when I downgraded to v0.9.12. I have not tried intervening 0.10.x versions.

I am running the built-in server with the following command:

```
php -S localhost:8000 -c ../_server/php.ini
```

The `php.ini` that's being loaded is:

```
display_errors = Off
error_log = ./../_server/error.log
log_errors = On
# error_reporting = E_ALL
error_reporting = E_ALL ^ E_STRICT
date.timezone = Europe/London
```

And my PHP version is:

```
$ php -v
PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
```

Thanks for an amazing tool!

**Comment by bobthecow** [comment]
Thanks for reporting! This has been fixed in the development branch, and will go out with the next stable release. In the meantime, you can install the `@dev` version in Composer to fix your issue.

**Comment by NateWr** [comment]
Fix confirmed. Thanks for the quick update!
