### ISSUE TITLE
Issue with PHP 7.4 numeric literal operator

### ISSUE THREAD

**Issue by Kocal** [bobthecow/psysh#637]
Hi, 

I'm using Psysh and I'm facing an issue with the numeric literal separator introduced in PHP 7.4:
![Sélection_660](https://user-images.githubusercontent.com/2103975/81950996-e9840380-9604-11ea-9376-53f74bef5527.png)

I don't understand where the issue can come from, it's working fine with `php -a`.

Here is my `Psy\info()` if it can helps you:
```txt
➜  ~ psysh
Psy Shell v0.10.4 (PHP 7.4.4 — cli) by Justin Hileman
>>> Psy\info()
=> [
     "PsySH version" => "v0.10.4",
     "PHP version" => "7.4.4",
     "OS" => "Linux",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => null,
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "loop listeners" => [
       "Psy\ExecutionLoop\ProcessForker",
     ],
     "commands" => [
       "help" => "Psy\Command\HelpCommand",
       "?" => "Psy\Command\HelpCommand",
       "ls" => "Psy\Command\ListCommand",
       "dir" => "Psy\Command\ListCommand",
       "dump" => "Psy\Command\DumpCommand",
       "doc" => "Psy\Command\DocCommand",
       "rtfm" => "Psy\Command\DocCommand",
       "man" => "Psy\Command\DocCommand",
       "show" => "Psy\Command\ShowCommand",
       "wtf" => "Psy\Command\WtfCommand",
       "last-exception" => "Psy\Command\WtfCommand",
       "wtf?" => "Psy\Command\WtfCommand",
       "whereami" => "Psy\Command\WhereamiCommand",
       "throw-up" => "Psy\Command\ThrowUpCommand",
       "timeit" => "Psy\Command\TimeitCommand",
       "trace" => "Psy\Command\TraceCommand",
       "buffer" => "Psy\Command\BufferCommand",
       "buf" => "Psy\Command\BufferCommand",
       "clear" => "Psy\Command\ClearCommand",
       "edit" => "Psy\Command\EditCommand",
       "sudo" => "Psy\Command\SudoCommand",
       "history" => "Psy\Command\HistoryCommand",
       "hist" => "Psy\Command\HistoryCommand",
       "exit" => "Psy\Command\ExitCommand",
       "quit" => "Psy\Command\ExitCommand",
       "q" => "Psy\Command\ExitCommand",
     ],
     "updates" => [
       "update available" => false,
       "latest release version" => "v0.10.4",
       "update check interval" => "weekly",
       "update cache file" => "~/.config/psysh/update_check.json",
     ],
     "pcntl" => [
       "pcntl available" => true,
       "posix available" => true,
       "use pcntl" => true,
     ],
     "input" => [
       "interactive mode" => "auto",
       "input interactive" => true,
     ],
     "readline" => [
       "readline available" => true,
       "readline enabled" => true,
       "readline service" => "Psy\Readline\GNUReadline",
       "readline library" => "7.0",
       "readline name" => "psysh",
     ],
     "output" => [
       "color mode" => "auto",
       "output decorated" => null,
       "output verbosity" => "normal",
     ],
     "history" => [
       "history file" => "~/.config/psysh/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => true,
       "bracketed paste" => false,
       "custom matchers" => [],
     ],
   ]
>>> 
```

Do you have an idea of what happens?

Thanks you!

**Comment by bobthecow** [comment]
Yeah, that's strange. It works great with v0.10.4 and PHP 7.4.4 for me.

Try it with the latest pre-built phar release to rule out weird dependency interactions?

**Comment by GrahamCampbell** [comment]
What other global packages do you have? Is there an old version of php-parser installer?

**Comment by bobthecow** [comment]
> What other global packages do you have? Is there an old version of php-parser installer?

Yeah, that's my guess too.

**Comment by bobthecow** [comment]
Ha! Latest php-parser backports numeric literal separators to older PHP versions!

<img width="762" alt="Screen Shot 2020-05-14 at 9 48 54 AM" src="https://user-images.githubusercontent.com/53660/81962116-21208a80-95c8-11ea-93d1-f66f76402e1d.png">

… this should probably be filed as a bug 😛

**Comment by Kocal** [comment]
> What other global packages do you have?

Sorry but I can't tell you right now, I'm not at work.

Normally I don't have any global packages except psysh, tomorrow I will try to remove and install it again and see what happens.

**Comment by GrahamCampbell** [comment]
> Ha! Latest php-parser backports numeric literal separators to older PHP versions!

Yeh, this is intended. It parses files as the latest PHP 7 syntax, regardless of the actual runtime version. It also has an option to parse as the latest PHP 5 syntax, regardless of the actual runtime version.

**Comment by bobthecow** [comment]
right. parsing as the latest syntax is fine, as long as writing it spits out the latest syntax when the ast is printed. but in this case, writing it removes the underscores, which makes it “execute invalid code” in psysh.

**Comment by Kocal** [comment]
Okay, so this is my global composer packages:
![Sélection_667](https://user-images.githubusercontent.com/2103975/82022558-285d9c00-968d-11ea-8094-5e0e4b6f4b33.png)

I removed psysh and installed it back and it's now working (nikic/php-parser has been updated from 4.2.2 to 4.4.0)
![Sélection_668](https://user-images.githubusercontent.com/2103975/82022578-31e70400-968d-11ea-9af9-447bd2b408d1.png)

My issue is now fixed, thanks! :)

Should I close this issue or there is really a bug? 
> … this should probably be filed as a bug 
> https://github.com/bobthecow/psysh/issues/637#issuecomment-628757773

**Comment by GrahamCampbell** [comment]
No, I don't think this is a bug. You simply had a version of PHP Parser that was parsing the code using an older version of the PHP 7 syntax.

**Comment by Kocal** [comment]
Right, I'm closing it then.

Thank you
