### ISSUE TITLE
Literals should be allowed as first operand of instanceof in PHP 7.3+

### ISSUE THREAD

**Issue by lucaswerkmeister** [bobthecow/psysh#644]
[Instanceof Operator accepts Literals](https://www.php.net/manual/en/migration73.new-features.php#migration73.new-features.core.instanceof-literals) is one of the new features in PHP 7.3, so this should not be rejected (anymore):

```console
$ php vendor/bin/psysh 
Psy Shell v0.10.4 (PHP 7.4.3 — cli) by Justin Hileman
>>> var_dump( null instanceof stdClass );
PHP Fatal error:  instanceof expects an object instance, constant given in Psy Shell code on line 1
>>> ^D
Exit:  Ctrl+D

$ php -a
Interactive mode enabled

php > var_dump( null instanceof stdClass );
php shell code:1:
bool(false)
php > ^D
```

**Comment by bobthecow** [comment]
Thanks for reporting. This has been fixed and will go in the next stable release :)
