### ISSUE TITLE
PsySH class existence check is too eager

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#647]
```
Psy Shell v0.10.4 (PHP 7.2.24-0ubuntu0.18.04.6 — cli) by Justin Hileman
>>> echo 0 ? Foo::CNS : 'x';
PHP Fatal error:  Class 'Foo' not found in Psy Shell code on line 1
```
Compare with [actual PHP behavior](https://3v4l.org/2rcmD):
```
php > echo 0 ? Foo::CNS : 'x';
x
```

Using non-existent classes is not that rare in code that needs to deal with conditional dependencies (like some plugin that changes behavior when a certain other plugin is enabled).

**Comment by bobthecow** [comment]
It's supposed to work :) 

We are pretty lenient with class existence validation in conditional contexts, but somehow [didn't include ternaries in the list of conditional contexts](https://github.com/bobthecow/psysh/blob/master/src/CodeCleaner/ValidClassNamePass.php#L99-L102) to allow :-/ 

Fix coming shortly!
