### ISSUE TITLE
Can't work under swoole

### ISSUE THREAD

**Issue by Arvin-Lee** [bobthecow/psysh#659]
Can't work under swoole

**Comment by Arvin-Lee** [comment]
![image](https://user-images.githubusercontent.com/16573739/99172902-0e3c6d80-2745-11eb-952f-03b82225c491.png)

**Comment by bobthecow** [comment]
Hi! I don't have a ton of context here, but I'm happy to help investigate. Can you help me set up minimal repro steps for the issue?

**Comment by Arvin-Lee** [comment]
The problem has been solved Thank you very much！
