### ISSUE TITLE
Unable to build phar on PHP 8 due to humbug/box PHP version requirements

### ISSUE THREAD

**Issue by ramsey** [bobthecow/psysh#661]
I'm unable to build the phar on PHP 8 due to humbug/box PHP version requirements of `^7.2` (in humbug/box 3.9.1). The latest version of humbug/box 3.10.1 has a PHP requirement of `^7.3`, so upgrading does not help.

```console
$ make build/psysh/psysh
composer bin box install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for humbug/box 3.9.1 -> satisfiable by humbug/box[3.9.1].
    - humbug/box 3.9.1 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
  Problem 2
    - Installation request for humbug/php-scoper 0.13.9 -> satisfiable by humbug/php-scoper[0.13.9].
    - humbug/php-scoper 0.13.9 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
  Problem 3
    - Installation request for paragonie/pharaoh v0.5.0 -> satisfiable by paragonie/pharaoh[v0.5.0].
    - paragonie/pharaoh v0.5.0 requires php ^7 -> your PHP version (8.0.0) does not satisfy that requirement.

make: *** [Makefile:50: vendor/bin/box] Error 2
```

**Comment by ramsey** [comment]
Here's the issue on humbug/box asking for PHP 8 support: https://github.com/box-project/box/issues/486

**Comment by bobthecow** [comment]
Thanks for raising the issue with humbug/box. 

We use PHP 7.2 for the stable release builds, so it's not a blocker for the project, but it does make local builds more of a pain 😕

**Comment by GrahamCampbell** [comment]
@bobthecow Can you instead install box using the vendor-bin plugin, or download the phar build, so you can still resolve dependencies using PHP 7.2 (either natively or via composer php version simulation)?

**Comment by bobthecow** [comment]
Yep, that's how we're using Box.

I'm fine, because I have a local copy of 7.2 that I use to match what we're doing for releases in CI (now GitHub Actions). It's more of a concern for people trying to build their own.

**Comment by ramsey** [comment]
Currently, I have to build my own because the version of nikic/php-parser that's bundled with 0.10.4 doesn't support recent PHP 8 features. 😄

**Comment by bobthecow** [comment]
🔜

**Comment by bobthecow** [comment]
(probably tonight?)

**Comment by bobthecow** [comment]
https://github.com/bobthecow/psysh/releases/tag/v0.10.5 👀

**Comment by ramsey** [comment]
Thanks!

**Comment by bobthecow** [comment]
Phar successfully builds and runs under PHP 8.0.3 🙂
