### ISSUE TITLE
Restore HHVM Tests

### ISSUE THREAD

**Issue by GrahamCampbell** [bobthecow/psysh#662]
See https://github.com/vlucas/phpdotenv/tree/3.6 for an example of testing on the LTS HHVM 3 versions, using Ubuntu 16.04 and Composer 2 on GitHub Actions. 🎉

**Comment by GrahamCampbell** [comment]
You basically just need to lift the files from https://github.com/vlucas/phpdotenv/tree/3.6/.github/bin and the hhvm job from https://github.com/vlucas/phpdotenv/blob/3.6/.github/workflows/tests.yml.

**Comment by bobthecow** [comment]
Awesome, thanks!

**Comment by bobthecow** [comment]
This worked great. Thanks for the pointer @GrahamCampbell.
