### ISSUE TITLE
Simulated fatal error when using multiple anonymous classes

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#665]
```
Psy Shell v0.10.5 (PHP 7.2.31-1+0~20200514.41+debian9~1.gbpe2a56b+wmf1+icu63 — cli) by Justin Hileman
>>> new class {}; new class {}
PHP Fatal error:  Class named  already exists in Psy Shell code on line 1
```
This makes it impossible to create an anonymous class which returns another anonymous class, which can be useful during debugging for making fake factories.

**Comment by bobthecow** [comment]
Thanks for reporting. This is fixed in cc5c404 and will go out in the next stable release.
