### ISSUE TITLE
History not handling namespaced calls

### ISSUE THREAD

**Issue by tyler36** [bobthecow/psysh#671]
There seems to be a problem with the way `\` are handled with the history function: basically they are removed.
Commands will function properly, but something happens when they are saved.

![bad-psysh-carbon](https://user-images.githubusercontent.com/7234392/110058748-4627f900-7da6-11eb-8322-1afc4c76b02a.png)
![bad-psyinfo](https://user-images.githubusercontent.com/7234392/110058750-47592600-7da6-11eb-9b9d-914b0edcf238.png)

```
>>> psy\info()
....
>>> hist
0: psyinfo()
```

- When I view the history file in a text editor (VS Code), there are no `\` characters.
- If I manually add the `\` character (eg. `psyinfo()` => `psy\info()`), when I start a new session and type `hist`, the `\` characters are remove from the history file and the displayed history.

OS: `Win10`
PHP: `7.3.24`
PSY Shell: `v0.10.6`

**Comment by bobthecow** [comment]
Can you paste the output from `psy\info()`?

**Comment by tyler36** [comment]
Sorry ... I forgot to include it

```json
>>> psy\info()
=> [
     "PsySH version" => "v0.10.6",
     "PHP version" => "7.3.24",
     "OS" => "WINNT",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => "~/.config/psysh/config.php",
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "loop listeners" => [],
     "commands" => [
       "help" => "Psy\Command\HelpCommand",
       "?" => "Psy\Command\HelpCommand",
       "ls" => "Psy\Command\ListCommand",
       "dir" => "Psy\Command\ListCommand",
       "dump" => "Psy\Command\DumpCommand",
       "doc" => "Psy\Command\DocCommand",
       "rtfm" => "Psy\Command\DocCommand",
       "man" => "Psy\Command\DocCommand",
       "show" => "Psy\Command\ShowCommand",
       "wtf" => "Psy\Command\WtfCommand",
       "last-exception" => "Psy\Command\WtfCommand",
       "wtf?" => "Psy\Command\WtfCommand",
       "whereami" => "Psy\Command\WhereamiCommand",
       "throw-up" => "Psy\Command\ThrowUpCommand",
       "timeit" => "Psy\Command\TimeitCommand",
       "trace" => "Psy\Command\TraceCommand",
       "buffer" => "Psy\Command\BufferCommand",
       "buf" => "Psy\Command\BufferCommand",
       "clear" => "Psy\Command\ClearCommand",
       "edit" => "Psy\Command\EditCommand",
       "sudo" => "Psy\Command\SudoCommand",
       "history" => "Psy\Command\HistoryCommand",
       "hist" => "Psy\Command\HistoryCommand",
       "exit" => "Psy\Command\ExitCommand",
       "quit" => "Psy\Command\ExitCommand",
       "q" => "Psy\Command\ExitCommand",
     ],
     "updates" => [
       "update available" => false,
       "latest release version" => "v0.10.6",
       "update check interval" => "weekly",
       "update cache file" => "~/AppData/Roaming/PsySH/update_check.json",
     ],
     "pcntl" => [
       "pcntl available" => false,
       "posix available" => false,
       "use pcntl" => false,
     ],
     "input" => [
       "interactive mode" => "auto",
       "input interactive" => true,
     ],
     "readline" => [
       "readline available" => true,
       "readline enabled" => true,
       "readline service" => "Psy\Readline\Libedit",
       "readline name" => "psysh",
     ],
     "output" => [
       "color mode" => "auto",
       "output decorated" => null,
       "output verbosity" => "normal",
     ],
     "history" => [
       "history file" => "~/AppData/Roaming/PsySH/psysh_history",
       "history size" => null,
       "erase duplicates" => true,
     ],
     "docs" => [
       "manual db file" => "~/AppData/Roaming/PsySH/php_manual.sqlite",
       "sqlite available" => true,
       "db lang" => "en",
       "db version" => "1.3.25",
       "db svn rev" => "349745",
       "db built at" => "Sun, 03 May 2020 19:41:17 +0000",
       "db hash" => "ac0a6554803d2eb12f253c7ce63807cb",
     ],
     "autocomplete" => [
       "tab completion enabled" => true,
       "bracketed paste" => false,
       "custom matchers" => [],
     ],
   ]
```

**Comment by bobthecow** [comment]
There's something weird happening here, but I haven't been able to reproduce it.

If you edit the history file and manually add slashes, you have to escape them as `\134`. For example, `psyinfo()` -> `psy\134info()`. Otherwise, it'll interpret the slash as the start of an escape sequence, so `\i` becomes just `i`.

Do you mind trying escaped slashes to see if the history file is read properly?

**Comment by tyler36** [comment]
`0.10.6`
- Start new session: `psysh`
```
hist --clear
psy\info()
```
- Up-arrow:  `psyinfo() `
- Open history file, update `psyinfo()` -> `psy\info()`. Close file
- Up-arrow => blank, down-arrow => blank. Seems like there's no history.
- type in console: `2+2`
- history file:
```
2+2
```
- type: `psy\info()`
- history file
```
2+2
psyinfo()
```
- Update `psyinfo()` -> `psy\\info()`. Close file
- Up / down arrows only show `2+2` in history, history file:
```
2+2
psy\\info()
```
- Exit psysh session. Start new session. History file:
```
2+2
exit
```
- Update to `0.10.7`
- Repeat steps above with same results.

**Comment by bobthecow** [comment]
An escaped slash in the history file is `\134` not `\\`. See the example in my comment above.

**Comment by tyler36** [comment]
My appologies. I read your comment, got side tracked by email and when I went back to "testing", remembered the "you have to escape them" part.

```
hist --clear
psy\info()
```
- Update history file: `psyinfo()` => `psy\134info()`. Close file.
- Arrow up shows: `psyinfo()`
- Exit session
- New session:
- Arrow up shows: `psyinfo()`
- History file:
```
psyinfo()
exit
```

**Comment by tyler36** [comment]
hmmm ... thats weird. I updated my environment path to use `php 7.4` and started a new console session:
```
❯ php -v
PHP 7.4.13 (cli) (built: Nov 24 2020 12:43:32) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```
This works. 
```
❯ psysh
psy\info()
...
```
- Up-arrow and histroy file correctly show: `psy\info()`.
- Exitting psysh and starting again also keep  `psy\info()`
- If I switch back to `php 7.3`
```
❯ php -v
PHP 7.3.24 (cli) (built: Oct 27 2020 14:44:04) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.24, Copyright (c) 1998-2018 Zend Technologies
``` 
- ... it reverts back to the bad behavior. Switch to `php 7.4` and its fine.

**Comment by tyler36** [comment]
- Switch to `php 8.0.1`
```
❯ php -v
PHP 8.0.1 (cli) (built: Jan  5 2021 23:43:39) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
```
- ... and everything works.

**Comment by bobthecow** [comment]
Yeah, that's weird. My best guess is a bug in PHP 7.3 / readline / editline on windows? I tried with PHP 7.3.24 on my Mac and it's just fine ¯\\\_(ツ)\_/¯

**Comment by tyler36** [comment]
Yep, seems to be a PHP 7.3 issue. I'm happy to try toggling an INI setting or 2 if you have any suggestions?
Otherwise, I'll close the ticket.

**Comment by bobthecow** [comment]
I really don't have any insight here, sorry.

**Comment by tyler36** [comment]
No problems. Thanks for following up.

Just for *** and giggles, I copied over the 7.4 ini, commented out some of the extentions that squawked and tried it again, but with no luck.

Nothing more to do really ... thanks again for the follow-up(s)
