### ISSUE TITLE
Thank you for Psysh; Wondering if there's a way to load Psysh without generating output ...

### ISSUE THREAD

**Issue by ppozon** [bobthecow/psysh#672]
Hello helpful folks on the Psysh team ...

Hope you are all well and safe ...

I'm not sure if this is really an issue rather than a question, so thank you in advance for reading (and please let me know if there's a better place for questions like this) ...

Psysh has been an enormous help for a team working on a legacy PHP codebase. Thank you very much for writing indispensable tool.

Right now, Psysh is helpful to the work we do, mostly as a library that is loaded in our test suite, where we can later set breakpoints when the `phpunit` is run from the command-line. Actually it's become so helpful that the Psysh script is `require_once()`'ed from our tests at a very deep level of test includes, so that it's always available for debugging. It is rarely or never used as a standalone script. This has been working very well ...

It looks like something happened in PHP 7.2 in that `session_set_save_handler()` became more rigorous about issuing a warning if output was already sent, before calling this function ... From digging in, it looks like my `require_once()` on the Psysh script is issuing:
```
#!/usr/bin/env php
```
which looks absolutely expected, since it's at the top of the file.

(There's other issues here where session_set_save_handler() is also being invoked from a deep system library by our tests shortly after Psysh has been `require()`d, so there's work that could be done to be judicious in what's being required ...)

Just wondering if you have a recommendation for folks who use it mainly as a pre-loaded "breakpoint library" instead of standalone shell script ... I considered simply removing the shebang line from my copy of the Psysh script but wanted to check with good folks at Psysh first...

Thank you in advance for any help!
Patty

**Comment by bobthecow** [comment]
Unfortunately that's just what happens when you import a Phar in PHP. The first line (which is required to make it executable by your system) isn't ignored like it is in many languages so it counts as output.

My recommendation would be to install psysh as a dev dependency via composer rather than relying on the prebuilt phars if you're importing it while testing.

**Comment by bobthecow** [comment]
If you have control of the require call, you can surround the require call with output buffering to swallow that one line:

```
ob_start();
require 'path/to/psysh';
ob_end_clean();
```

**Comment by ppozon** [comment]
This is super helpful ... We're making our way towards composer and still have a ways to go, but this gives us a nudge in the right direction ... We do have control of the require call and the `ob_start()` workaround works perfectly ...

Thank you, Bob, from me and the team (the catfish ...)

**Comment by ppozon** [comment]
I'm sorry! Bob the cow is either a band or a story 🤦  ... Thank you, **Justin**! (Well, we are catfish anyway 😌 )
