### ISSUE TITLE
Psy\Info is broken when extending the Shell class

### ISSUE THREAD

**Issue by chx** [bobthecow/psysh#673]
https://github.com/bobthecow/psysh/blob/main/src/functions.php#L286-L288 uses `loopListeners` which is defined as `private`. It either should be protected or something. https://github.com/bobthecow/psysh/blob/main/src/Shell.php#L72

This causes https://github.com/drush-ops/drush/issues/4709

**Comment by bobthecow** [comment]
Thanks @chx! This has been fixed in `main` and will go out with the next release. You should be able to install from dev rather than stable if you want the fix quicker.
