### ISSUE TITLE
PHP Parse error:  syntax error

### ISSUE THREAD

**Issue by TFYunho** [bobthecow/psysh#674]
Hi, I'm using psysh v0.10.7+php55-compat with PHP 5.6.40 on Ubuntu
On Ubuntu, it works well. but CentOS and Windows with PHP 5.5.38 is not.
Here is an error message

> PHP Parse error:  syntax error, unexpected '.' in phar://.../psysh/vendor/autoload.php on line 21

**Comment by bobthecow** [comment]
Thanks again for reporting. [The latest release](https://github.com/bobthecow/psysh/releases/tag/v0.10.8) enforces this change from the pre-built binaries, and reflects it in the asset names.

**Comment by TFYunho** [comment]
Thank you. I'm using psysh v0.9 now and it runs.
