### ISSUE TITLE
Strange behavior on array_push

### ISSUE THREAD

**Issue by MonsieurCellophane** [bobthecow/psysh#678]
Greetings.
It appears psysh has problems with array_push if arrays are referred to in array keys:

`Psy Shell v0.10.8 (PHP 7.3.27 — cli) by Justin Hileman
>>> $du=[]
=> []
>>> $du['a']=[]
=> []
>>> array_push($du['a'],4)
PHP Fatal error:  Only variables can be passed by reference in Psy Shell code on line 1
`
while 

`$du['a'][]=4` 

and 

`array_push($du,'foo')` 

work just fine.

**Comment by bobthecow** [comment]
Thanks for reporting! This has been fixed in `main` and will go out with the next release.
