### ISSUE TITLE
Using with Slim framework

### ISSUE THREAD

**Issue by taylorren** [bobthecow/psysh#68]
Hi Bob,

Trying to mix the PsySH in Slim framework. Installation seems fine. 

When invoking \Psy\Shell::debug(get_defined_vars()), got this error message and attached as screen shot. 

Any hint?
![ashampoo_snap_2014 05 02_15h13m14s_001_](https://cloud.githubusercontent.com/assets/3853711/2860373/735a1484-d1c9-11e3-9cac-7aae8103bd65.png)

**Comment by theofidry** [comment]
@taylorren, PsySH does not work with a web server like Apache or so I heard. However it should works with the PHP built in server.

**Comment by bobthecow** [comment]
To use PsySH inside a request context, you need to run it with the built-in PHP SAPI command line server. Something like this:

```sh
php -S localhost:3000 -t web web/index.php
```

… or something like that :)
