### ISSUE TITLE
Ctrl+Z and Ctrl+U on Windows

### ISSUE THREAD

**Issue by char101** [bobthecow/psysh#681]
Hi,

Is it possible to handle `Ctrl+Z` and `Ctrl+U` on Windows? `Ctrl+Z` (ASCII 26) is usually used to exit the prompt and `Ctrl+U` (ASCII 21) is used to clear the line.

```
Psy Shell v0.10.8 (PHP 8.0.7 — cli) by Justin Hileman
>>> 
PHP Parse error: Unexpected character "" (ASCII 26) on line 1
>>> 
PHP Parse error: Unexpected character "" (ASCII 21) on line 1
>>> 
```

I can use `Ctrl+D` and `Ctrl+U` on linux terminal but I can't seem to use any shortcut (other than `Tab` for completion) in Windows console.

**Comment by char101** [comment]
By coincidence I found that pressing `Esc` + `Ctrl-k` twice clears the line.

**Comment by bobthecow** [comment]
`ctrl+z` is a unix shell command to send `SIGSTOP`. `ctrl-c`, `ctrl-d`, `crtl-u`, etc are all also ways to send signals to processes in unix shells. i don't know what the windows equivalent for these are, but it is possible to get a "real" shell in windows via WSL, so that might do it for you?

**Comment by char101** [comment]
I already run psysh in Virtualbox so my problem is not about accessing psych rather that without the usual shortcuts the readline experience in the Windows terminal feels quite limited.

For example, after rotating through the history, and if I want to clear the line, I have to press `Backspace` continuously where in linux I can use `Ctrl+u` to erase the line. Also to exit the shell I have to type `exit` while in linux I can press `Ctrl+d`.

**Comment by char101** [comment]
Looks like php readline implementation is line oriented so it is not possible to process single char input without newline. 

I think I can use Autohotkey to map `Ctrl-u` to `Esc+Ctrl-k+Ctrl-k` to clears the line and to map `Ctrl-d` to exit.

**Comment by bobthecow** [comment]
You might be able to use the Hoa/Console based userland readline implementation to get some of that functionality under Windows? PsySH supports it if it's there.

**Comment by char101** [comment]
I tried the `hoa/console` readline implementation by changing `getReadlineClass` in `Configuration.php`. There are a lot of problem with it:

1. at startup, `Warning: Private methods cannot be final as they are never overridden by other classes in hoa\stream\Stream.php on line 195`
2. the prompt does not appear instantly, rather I have to type `Enter` for it to appears. This happens at startup and after every line entered
3. `Tab` completion does not work, it only shows literal `Tab`
4. default keybindings listed at https://github.com/hoaproject/Console does not work (`Ctrl-A`/`Ctrl-E` does not move the cursor to the start/end of the line)

The only thing that works is that typing `Ctrl-Z` exits the shell.

**Comment by bobthecow** [comment]
Hmm. It's effectively abandoned at this point, so 1 is not surprising. The rest of them make it seem less than useful, though :(
