### ISSUE TITLE
Security - Deserialization of Untrusted Data (CWE ID 502)

### ISSUE THREAD

**Issue by kobusvw** [bobthecow/psysh#683]
SAST Security scan picks up a MEDIUM vulnerability on Deserialization of Untrusted Data

**Description:**
The application deserializes untrusted data without sufficiently verifying that the resulting data will be valid.

**File:**
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php Line 153

**Recommendations:**
The wide variance of encapsulation issues makes it impractical to generalize how these issues should be addressed, beyond
stating that encapsulation boundaries should be well-defined and adhered to.

**Code:**
if ($content) {
   $shell->setScopeVariables(@\unserialize($content));
}

**Comment by GrahamCampbell** [comment]
Yes? By design, this package allows for arbitrary code execution. I don't follow...

**Comment by kobusvw** [comment]
Hi Graham

Thanks for the super-fast response.
It pretty much looks like a false positive from a scanner that doesn't understand the context.
I will send the SAST security team a False Positive and see what they say.

Kind Regards Kobus
