### ISSUE TITLE
Can 'doc' be clever about {@inheritdoc} comments?

### ISSUE THREAD

**Issue by phil-s** [bobthecow/psysh#691]
A lot of object oriented PHP seems to have a convention whereby methods are essentially undocumented if they are overriding a documented method.  The undocumented methods contain only `{@inheritdoc}` and the user must either stumble manually through a potential mess of ancestors until they find the one with genuine docs, or else have intelligent tools at hand which do the leg work and automatically produce the documentation.

Could psysh be one of those intelligent tools, such that the `doc` command will track down the actual documentation if it encounters `{@inheritdoc}` ?

**Comment by bobthecow** [comment]
Try `doc --all`?

**Comment by phil-s** [comment]
Aha, I should have noticed that was a thing.  That's definitely a useful workaround; thanks!

I think my suggested feature would still be really helpful.  For example, with `doc --all` my test case produces 10 results, 8 of which are identical; so while it's super useful to have this option, it can still be cumbersome to process the output.

**Comment by bobthecow** [comment]
Ooh. It shouldn't be producing identical ones. Do you have a repro for that? Does it have to do with methods that come from grandparent classes and don't have a definition on parent classes or something?

**Comment by bobthecow** [comment]
Got it!

Duplication was happening due to interfaces and traits inherited from parent classes. In my repro case I was able to completely de-dupe them. If you see dupes after the change I made lands, please re-open 🙂

It also treats it as an implicit `--all` if the original docblock contains `{@inheritdoc}`. It would be great to intelligently replace the child docs with the parent docs, but that only works if we can do it cleanly, and the complexity of swapping out bits if they're only inherited, but merging child docs and parent docs if both are present, all while preserving formatting and intent … is a bit much. So for now, we'll get _something_ which is better than nothing, and doesn't require callers to know about `--all`.

**Comment by phil-s** [comment]
Tested, and working as described.  That's a huge improvement, thank you!

FYI the example I was testing now looks like the following (and it was indeed a ton of duplicate `interface Drupal\Core\Entity\EntityInterface` that I was seeing previously).

```
>>> doc Drupal\user\Entity\Role::preSave
class Drupal\user\Entity\Role extends Drupal\Core\Config\Entity\ConfigEntityBase implements Drupal\Core\Access\AccessibleInterface, Drupal\Core\Cache\CacheableDependencyInterface, Drupal\Core\Cache\RefinableCacheableDependencyInterface, Drupal\Core\Config\Entity\ConfigEntityInterface, Drupal\Core\Config\Entity\ThirdPartySettingsInterface, Drupal\Core\Entity\EntityInterface, Drupal\Core\Entity\SynchronizableInterface, Drupal\user\RoleInterface
public function preSave(Drupal\Core\Entity\EntityStorageInterface $storage)

Description:
  {@inheritdoc}

---

interface Drupal\Core\Entity\EntityInterface extends Drupal\Core\Access\AccessibleInterface, Drupal\Core\Cache\CacheableDependencyInterface, Drupal\Core\Cache\RefinableCacheableDependencyInterface
abstract public function preSave(Drupal\Core\Entity\EntityStorageInterface $storage)

Description:
  Acts on an entity before the presave hook is invoked.

  Used before the entity is saved and before invoking the presave hook. Note
  that in case of translatable content entities this callback is only fired
  on their current translation. It is up to the developer to iterate
  over all translations if needed. This is different from its counterpart in
  the Field API, FieldItemListInterface::preSave(), which is fired on all
  field translations automatically.

Throws:
  \Exception  When there is a problem that should prevent saving the entity.

Param:
  \Drupal\Core\Entity\EntityStorageInterface  $storage  The entity storage object.

Todo: Adjust existing implementations and the documentation according to
  https://www.drupal.org/node/2577609 to have a consistent API.

See: \Drupal\Core\Field\FieldItemListInterface::preSave()

---

abstract class Drupal\Core\Config\Entity\ConfigEntityBase extends Drupal\Core\Entity\EntityBase implements Drupal\Core\Access\AccessibleInterface, Drupal\Core\Cache\CacheableDependencyInterface, Drupal\Core\Cache\RefinableCacheableDependencyInterface, Drupal\Core\Config\Entity\ConfigEntityInterface, Drupal\Core\Config\Entity\ThirdPartySettingsInterface, Drupal\Core\Entity\EntityInterface, Drupal\Core\Entity\SynchronizableInterface
public function preSave(Drupal\Core\Entity\EntityStorageInterface $storage)

Description:
  {@inheritdoc}

---

abstract class Drupal\Core\Entity\EntityBase implements Drupal\Core\Access\AccessibleInterface, Drupal\Core\Cache\CacheableDependencyInterface, Drupal\Core\Cache\RefinableCacheableDependencyInterface, Drupal\Core\Entity\EntityInterface
public function preSave(Drupal\Core\Entity\EntityStorageInterface $storage)

Description:
  {@inheritdoc}
```
