### ISSUE TITLE
First-class callable syntax shows warning

### ISSUE THREAD

**Issue by joshlieb** [bobthecow/psysh#695]
First-class callable support is introduced in [php-parser](https://github.com/nikic/PHP-Parser/commit/13549aa7949c7c453e297003b70517bf8ddcec95)

There seems to be an incompatibility with psysh where the `VariadicPlaceholder` is expected to have some non-existent properties

I've attached a code snippet to reproduce

<details>
<summary>Code snippet</summary>

```
function foo($value, $bar)
{
    return $bar($value);
}

var_dump(foo('bar', strtoupper(...)))

// Dumps
// Warning: Undefined property: PhpParser\Node\VariadicPlaceholder::$value in src\CodeCleaner\CalledClassPass.php on line 81

// Warning: Undefined property: PhpParser\Node\VariadicPlaceholder::$byRef in src\CodeCleaner\CallTimePassByReferencePass.php on line 45

// Warning: Undefined property: PhpParser\Node\VariadicPlaceholder::$byRef in src\CodeCleaner\FunctionReturnInWriteContextPass.php on line 48

// string(3) "BAR"
```

</details>

Thanks for this wonderful package

Cheers!

**Comment by bobthecow** [comment]
Thanks! This (specific instance) has been fixed. If you see any more like this, I wouldn't be surprised. Please let me know!
