### ISSUE TITLE
Fix tests on symfony/console v6.0.3

### ISSUE THREAD

**Issue by bobthecow** [bobthecow/psysh#703]
This seems awfully breaky for a patch version update :-/

See https://github.com/bobthecow/psysh/runs/4992088701

cc @nicolas-grekas

**Comment by bobthecow** [comment]
The `'"\<string>eee\</string>"'` -> `'"\<string\>eee\</string\>"'` changes may be a pain to make work with older versions of symfony/console, but doable.

I'm worried about all the tokenization changes. Also some tests started dropping into an interactive shell when run locally (rather than finishing the test suite) so i'm not sure what that's about yet.

**Comment by nicolas-grekas** [comment]
It looks like the escaping changed after https://github.com/symfony/symfony/pull/44912
And that https://github.com/symfony/symfony/pull/45088 is responsible for remaining failures, including the interactive mode issue.

**Comment by nicolas-grekas** [comment]
If you can dig a bit more that'd be nice. I can have a look next week on my side.

**Comment by bobthecow** [comment]
Thanks @nicolas-grekas!

Since I'm not testing the escaping itself, I updated all tests with hardcoded escaped strings to test that they _are_ escaped, not how `OutputFormatter` chooses to do it.

All remaining issues are fixed by https://github.com/symfony/symfony/pull/45240
