### ISSUE TITLE
Commands inside psysh incorrectly parsed

### ISSUE THREAD

**Issue by amadeann** [bobthecow/psysh#704]
Version: v0.11.1

Steps To Reproduce:

1. Open psysh
2. type `exit`

Expected: Tinker closes with `Exit:  Goodbye`
Actual: `RuntimeException with message 'Too many arguments, expected arguments "command".'`

From what I see, it most likely caused by the change in `symfony/console` (line 27) commited 10 days ago:
https://github.com/symfony/console/commit/aa58a696655593b0a012166cfbcf34fafac6e945

Because of that change `Psy\Input\ShellInput::tokenize()` is not able to correctly parse arguments. Instead of catching the entire "exit" string, it parses it letter by letter.

**Comment by bobthecow** [comment]
I believe this is fixed by https://github.com/symfony/symfony/pull/45240

**Comment by mrpph** [comment]
When I typed 'exit'  in tinker,  it shows error message > RuntimeException with message 'Too many arguments, expected arguments "command".' 
But I typed 'exit;' with semi-colon, it's ok and shows > Exit: Goodbye

**Comment by bobthecow** [comment]
Yep, that's expected. It is because (inside PsySH) `exit` is a command, but `exit;` is PHP code. The Symfony Console issue only affects commands, not code, in PsySH.
