### ISSUE TITLE
How to deal with monostate pattern?

### ISSUE THREAD

**Issue by dereckson** [bobthecow/psysh#706]
According the [mysqli_driver class documentation](https://www.php.net/manual/en/class.mysqli-driver.php):

> The mysqli_driver class is an instance of the monostate pattern, i.e. there is only one driver which can be accessed though an arbitrary amount of mysqli_driver instances.

But here what's happening with psysh:

```php
>>> $driver = new mysqli_driver()
=> mysqli_driver {#2668
     +reconnect: false,
     +report_mode: 0,
   }

>>> $driver->report_mode = MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT;
=> 3

>>> new mysqli_driver
=> mysqli_driver {#2680
     +reconnect: false,
     +report_mode: 0,
   }
```

At object creation stage, we can see the value for report_mode doesn't respect that monostate pattern.
That can lead to error in diagnostics and debugging.

When we print it, access it, dump it, the object has the correct value:

```php
>>> print_r(new mysqli_driver)
mysqli_driver Object
(
    [client_info] => mysqlnd 8.1.2
    [client_version] => 80102
    [reconnect] => 
    [report_mode] => 3
)
```

I suspect this behavior is correct for the language: the mysqli_driver source code looks a global struct  for the value when we access the report_mode variable.

But it's not optimal to print something other than the real value of the property when we'll query it.

**Comment by bobthecow** [comment]
I believe the driver doesn't deal with forking very well. Try disabling it in PsySH (add `'usePcntl' => false` to your PsySH config).

**Comment by dereckson** [comment]
Same behavior with usePcntl at false.

**Comment by bobthecow** [comment]
the problem seems to be in the dumper, not the psysh itself:

<img width="411" alt="Screen Shot 2022-02-04 at 11 15 34 PM" src="https://user-images.githubusercontent.com/53660/152628273-aa6e4123-7f31-487f-915f-7b272061cd4c.png">

**Comment by dereckson** [comment]
Indeed, every var_dump() call reports the current state of the object.

**Comment by bobthecow** [comment]
Thanks! I'll see if I can figure out why VarDumper isn't reporting the current state. 

cc @nicolas-grekas in case you have any ideas :)

**Comment by nicolas-grekas** [comment]
That's an issue for https://github.com/symfony/symfony indeed. Please send a PR with a failing test case and a fix if you can.

**Comment by bobthecow** [comment]
Closing this in favor of symfony/symfony#45487. Thanks @dereckson!
