### ISSUE TITLE
Document icons not supported on all devices

### ISSUE THREAD

**Issue by BaseMax** [bobthecow/psysh#707]
Hi there,

I using last version of **Manjaro** (Arch-based) Linux distro and installed most needed packages and chrome and Firefox. 
But some icons not displayed correctly. (UTF-8 characters)

I know its my problem and probably that icons display correctly on Windows and Android.
I just want to say they not support in default.

![2](https://user-images.githubusercontent.com/2658040/152675412-c26124d6-1def-42c5-b4ff-229063c8b29f.jpg)
![1](https://user-images.githubusercontent.com/2658040/152675418-1b6e9f64-1940-4809-ae17-53016f1fa54b.jpg)

**Comment by bobthecow** [comment]
The icons are standard emojis (with the exception of the Windows icon). It's 2022. At this point, I consider this to be a bug in your operating system, not a problem with PsySH's documentation.

**Comment by BaseMax** [comment]
Thank you. Anyway this project is awesome and so useful. @bobthecow 
Best
