### ISSUE TITLE
[Suggestion] Add "self update" command 

### ISSUE THREAD

**Issue by kfriend** [bobthecow/psysh#71]
I know Psysh is still very young, but it would be nice to have a self-update command which you could fire and have Psysh update itself.

Thanks for the great work.

**Comment by harikt** [comment]
Hey @bobthecow ,

This is a nice feature to have. But I do understand the complexity it may need. Why I am here was 

I tried to update to latest version today downloading via `wget https://git.io/psys`

After moving downloaded file to `/usr/local/bin` and executing psysh it shows 

> Psy Shell v0.8.15 (PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
> New version is available (current: v0.8.15, latest: v0.8.17)

So was wondering if there is a command :) .

**Comment by bobthecow** [comment]
Oh, oops. Updating!

You can always get the current release from the releases tab here on GitHub :)

**Comment by harikt** [comment]
What confused me was which one I should download :D .

**Comment by bobthecow** [comment]
Heh. Fair enough. We'll get a self-update one of these days :P
