### ISSUE TITLE
All output is paged with `less` and pager must be manually quit after every command

### ISSUE THREAD

**Issue by bakerkretzmar** [bobthecow/psysh#721]
Thanks so much for Psysh, it's a fantastic tool! 🙏🏻 

Since v0.11.3 all output in a console session is paged, even when it doesn't take up the whole screen. It looks like this was intentional, but I initially thought it was a bug in Psysh or an issue with my shell.

Using the pager seems to me like a much worse user experience for a couple reasons:

- paged output isn't wrapped, so now all output wider than the width of the terminal is cut off and must be scrolled/navigated to
- the pager is a separate program and has to be exited manually by the user, so every single command entered in a Psysh console/session now requires the extra step of quitting the pager, which slows down working in the console considerably

Would you consider reverting 6794814c6e9f252d573f9a77d555d6c3850762ac or putting it behind a config option? Happy to submit a PR for that myself. Thanks!

**Comment by bobthecow** [comment]
All output should always run through the pager. But with the default PsySH settings, it _should_ do the "right thing" with short output, i.e. pass it straight through (that's the `-F` in the less args). If you're not seeing that behavior, there might be an issue with your pager settings, or with your `less` implementation, or with my assumptions :) 

Can you share the output of `\psy\info()`, your `cli.pager` ini setting, and the output of `which less`?

**Comment by bobthecow** [comment]
First, there are a couple of ways to disable output paging, but none of them are super intuitive. I've just added support for setting `'pager' => false` in your PsySH config to completely disable output paging. You can try that out by installing the `@dev` version via Composer.

Second, the pager isn't supposed to be breaking wrapping. Per the options we set for `less` by default, it should look like this:

<img width="762" alt="Screen Shot 2022-05-30 at 10 09 34 PM" src="https://user-images.githubusercontent.com/53660/171078957-beff60cc-da19-46e3-9091-e3edfa17b095.png">

Yours is super obnoxious, and I don't blame you for disliking it :) 

… but there does seem to be something goofy about your setup. Are you using it inside screen, maybe?

**Comment by bobthecow** [comment]
Yes, paging used to work but at some point it broke for two types of output (return values and stdout). It still worked for everything else. And yes, I do consider that a bug.

I'm open to the idea that people prefer not to have paging by default. If that's the case, making it opt-in is reasonable too. But I do think that it should be _consistently_ applied, which it wasn't before 🙂

**Comment by bakerkretzmar** [comment]
Gotcha, definitely a bug. Sorry, didn't mean to imply that you just 'decided' it was buggy and changed it—I thought this was new, didn't know it used to be applied everywhere and had been broken.

Totally agree it should be consistent either way. I may PR a change to the default but I'd want to make sure that's really a widespread preference and not just me 😅
