### ISSUE TITLE
Website wget link still 0.11.4 instead of 0.11.5 3 days after release

### ISSUE THREAD

**Issue by ooglek** [bobthecow/psysh#723]
Just a helpful reminder to update the downloadable phar that one gets when executing `wget https://psysh.org/psysh` to version 0.11.5

I'm happy to help build or write automation that automatically builds the new version and pushes it to the correct location, if one would appreciate said help! 😁 

Bonus Points: Add self-updating to the code, so once you have psysh, you just run a command flag `--update` and it will check for a new version and download and install (if psysh is writable by the current user).

**Comment by bobthecow** [comment]
Sorry about that, updated! It is a manual deploy, and this time I forgot :) 

At one point I fought with Github Actions for a while trying to get automated website deploys triggered based on PsySH releases, but never quite got it working ¯\\\_(ツ)\_/¯ 

If you want to build a self-update feature, go for it!
