### ISSUE TITLE
stream_wrapper_register(): Protocol hoa:// is already defined in psy/psysh/src/Readline/Hoa/ProtocolWrapper.php:473

### ISSUE THREAD

**Issue by TAGHREEDAA** [bobthecow/psysh#728]
When using laravel tinker extension with PHPStorm editor I got this issue 

local.ERROR: Uncaught ErrorException: stream_wrapper_register(): Protocol hoa:// is already defined. in 
/vendor/psy/psysh/src/Readline/Hoa/ProtocolWrapper.php:473

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'stream_wrapper_...', '/Users/taghreed...', 473, Array)
#1 vendor/psy/psysh/src/Readline/Hoa/ProtocolWrapper.php(473): stream_wrapper_register('hoa', 'Psy\\Readline\\Ho...')
#2 vendor/composer/ClassLoader.php(444): include('/Users/taghreed...')
#3 vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/taghreed...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Psy\\Readline\\Ho...')
#5 [internal function]: spl_autoload_call('Psy\\Readline\\Ho...')
#6 vendor/psy/psysh/src/Readline/Userland.php(83): {"exception":"[object] 

- Tinker Version: ^2.0
- Laravel Version: ^8.0
- PHP Version: ^7.4
- Database Driver & Version: mysql 8.0.21 - Homebrew

**Comment by bobthecow** [comment]
Thanks for reporting! This was fixed in [v0.11.8](https://github.com/bobthecow/psysh/releases/tag/v0.11.8)
