### ISSUE TITLE
Pager process crashes on macOS

### ISSUE THREAD

**Issue by zonuexe** [bobthecow/psysh#729]
An error occurs when outputting a long value to the pager on macOS.
No value can be output once the process crashes.

https://user-images.githubusercontent.com/822086/176931967-6e17cb49-008e-49af-a688-9442489579fc.mov

From what I've looked at, `range(1, 3563)` doesn't cause any problems and `range(1, 3564)` raises an exception.

This problem does not occur on Linux.

**Comment by bobthecow** [comment]
Yeah, that's weird. Your workaround helps it successfully recover, though, so that's great!

At least on my machine, after your change it only fails when trying to close the pager, so at that point it's … probably fine? The workaround makes it not terrible :)
