### ISSUE TITLE
Cmder link in wiki leads to ads

### ISSUE THREAD

**Issue by Rarst** [bobthecow/psysh#735]
At https://github.com/bobthecow/psysh/wiki/Windows#cmder the link to Cmder project `cmder.net` leads to advertisement page, seems they lost that domain.

The current site listed on GitHub page is https://cmder.app

Think wiki is restricted from public edits (or I forgot how that works?) don't see the option to correct it myself. :)

See https://github.com/cmderdev/cmder/issues/2728

**Comment by bobthecow** [comment]
Thanks, fixed!
