### ISSUE TITLE
Not dropped into a PsySH shell, after execution.

### ISSUE THREAD

**Issue by tarky** [bobthecow/psysh#75]
If possible, I don't understand how psysh works.
The document says "When your script reaches this point, execution will be suspended and you'll be dropped into a PsySH shell.".

I assume that after execution,a new terminal will be launched automatically on which  PsySH shell   is running.
Is that correct?

In my case, web browser response was suspended. But nothing else happened.

Without "\Psy\Shell::debug(get_defined_vars());", a page was rendered at the top of which the strings "#!/usr/bin/env php" was displayed for some reason.

[My enviroment]
OS X 10.8.5
Apache/2.4.7(XAMPP)
PHP/5.9.9(XAMPP)

[PS]
I hope video tutorial. That makes developers understand how it is supposed to work.

**Comment by bobthecow** [comment]
Closing, as this is an old issue, and lacks enough information to actually resolve.
