### ISSUE TITLE
Wiki Update: Install psysh through homebrew

### ISSUE THREAD

**Issue by sbani** [bobthecow/psysh#751]
Hi,

yesterday, I created a PR to the homebrew project that makes it possible to install psysh via brew.

Homebrew is a third party Mac package manager and is probably the most used one in the Mac world. For more information on how to install and use Homebrew see [their homepage](https://brew.sh/).

My pull pequest: https://github.com/Homebrew/homebrew-core/pull/118589
Details about the PsySH formula: https://formulae.brew.sh/formula/psysh

I wanted to add the installation method to your wiki too but found out that there's no option to add pull requests for wiki pages on Github.

In case you don't want to maintain the newest version in brew by yourself, you might want to add the brew installation as "unofficial" or "not supported". I'm happy to contribute here though, just let me know what I can do.

**Comment by bobthecow** [comment]
Thanks, done!
