### ISSUE TITLE
psysh refuses to show character '0' in input

### ISSUE THREAD

**Issue by aaarbk** [bobthecow/psysh#754]
I'm on MacOS 12.6, trying to use "Psy Shell v0.11.11 (PHP 8.0.8 — cli)". Pressing the `0` key doesn't show anything on the input line (the cursor doesn't move at all), even though the actual keypress gets registered and shows up in the output.

![](https://i.imgur.com/SeiVMlw.png)

So the inputs above are `0`, `0+0`, `0*1*2*3` and `$arr = [0, 0, 0, 1]` respectively.

If it matters, I've tried it both on iTerm2 and the built-in Terminal app with the same result.

**Comment by bobthecow** [comment]
Wow, that's really weird. I can't think of a thing that PsySH itself could be doing to mess that up, but there may be something weird with your readline setup.

Can you paste the output of `psy\info()`?

**Comment by bobthecow** [comment]
Okay, I've got a fix in 3089d4a, and it'll go out in the next release. If you have time to confirm that HEAD is working for you, that'd be amazing :)

**Comment by aaarbk** [comment]
Can you confirm that that fixed it.. thanks! :)
