### ISSUE TITLE
Loop only returns the last value if the curly brackets start on a new line

### ISSUE THREAD

**Issue by victorelec14** [bobthecow/psysh#756]
- Psy Shell v0.11.12 (PHP 8.1.10 — cli) by Justin Hileman

### Description:

psysh displays only the last value of a loop if the curly backet starts in new line

### Steps To Reproduce:

```php
$data = [
    "1111",
    "2222",
    "3333",
    "4444",
];
foreach ($data as $pos)
{
    echo $pos . "\n";
}
```

Result:
```
4444
```

Now with the curly backet in the same line of the foreach
```php
$data = [
    "1111",
    "2222",
    "3333",
    "4444",
];
foreach ($data as $pos){
    echo $pos . "\n";
}`
```

Result :
```
1111
2222
3333
4444
```

Thanks

Related: https://github.com/laravel/tinker/issues/161

**Comment by bobthecow** [comment]
Oh, I just left a comment explaining it on https://github.com/laravel/tinker/issues/161#issuecomment-1481037313 😛
