### ISSUE TITLE
Strange files in root directory

### ISSUE THREAD

**Issue by qshop123** [bobthecow/psysh#762]
I have found a strange issue based on psysh and Laravel framework nad PHP 8.0.2. Sometimes i discover three files in root dir:
1) Microsoft - 0 kb
2) PHP - 0 kb
3) subject('Test - 60kb with "Psy Shell v0.11.13 (PHP 8.1.3 — cli) by Justin Hileman"

Can you tell me what's is going on?

installed.json from vendor 

"name": "psy/psysh",
"version": "v0.11.13",
"version_normalized": "0.11.13.0",

Laravel 8.83.27

Slawek

**Comment by bobthecow** [comment]
I have no idea what that is. how are you running psysh / tinker? are you redirecting the output somehow?

**Comment by bobthecow** [comment]
There's nothing inherent to PsySH that would do this. Without more info about how you're using it, there's not much I can do to help debug. Feel free to reopen with more info!
