### ISSUE TITLE
Enforce declare(strict_types=1) ?

### ISSUE THREAD

**Issue by vedadkajtaz** [bobthecow/psysh#764]
Hello,

I couldn't find any way to enforce `declare(strict_types=1)` when starting a psysh session. It'd be great if that could be available in config, either as injected code option, or as a dedicated config option.

Thanks,

**Comment by vedadkajtaz** [comment]
This is great, thanks!

**Comment by bobthecow** [comment]
No problem 😄

**Comment by bobthecow** [comment]
And now it's released! Thanks again for the request.
