### ISSUE TITLE
No colors or ">>>" prompt when using in phpunit

### ISSUE THREAD

**Issue by wulftone** [bobthecow/psysh#78]
I can put the `\Psy\Shell::debug(get_defined_vars());` into my phpunit tests and it drops into a shell just fine, but the colors do not work, and the `>>>` prompt doesn't appear--it's just blank.  It doesn't seem to be interpreting any arrow key codes either.

It still works well enough, but these features are pretty nice to have, and they DO work when I just run `psysh` on its own.  Any ideas?

**Comment by kenjis** [comment]
I have colored output but no `>>>` at first. But once an error is outputted, `>>>` appears.

~~~
PHPUnit 4.8.6 by Sebastian Bergmann and contributors.

Psy Shell v0.6.0-dev (PHP 5.5.26 — cli) by Justin Hileman
ls
Variables: $mock, $mock2, $this
ls
Variables: $mock, $mock2, $this
show
RuntimeException with message 'Not enough arguments.'
>>> ls
Variables: $mock, $mock2, $this
>>> 
~~~

**Comment by toddmazierski** [comment]
Hi, all! I had trouble getting ANSI colors to appear in PHPUnit when debugging with PsySH, too. When running PHPUnit (a fairly old version—4.1.5), the following value:

```php
@posix_isatty(STDOUT)
```

…returns `false`, so the following two dependencies automatically disable colors:

* [`StreamOutput` in Symfony](https://github.com/symfony/symfony/blob/2dbb75aef49c39ac680a31f44514f94c29de681d/src/Symfony/Component/Console/Output/StreamOutput.php#L99)
* [`ConsoleColor` in PHP Console Color](https://github.com/JakubOnderka/PHP-Console-Color/blob/6855b75259010f67e8425aff1259c6e3f63750b7/src/JakubOnderka/PhpConsoleColor/ConsoleColor.php#L207)

Both libraries _do_ support overriding this auto-detection mechanism (`$decorated` in Symfony, `setForceStyle()` in PHP Console Color), so perhaps Psysh could support a configuration flag itself, and pass it along.

Hope that's useful!

**Comment by bobthecow** [comment]
This should be solved by `colorMode` config, and `—color` and `—no-color` command line flags :)

**Comment by mkolom** [comment]
`colorMode` setting worked for me as for colors but what about prompt and, more importantly, arrow codes?
Is it possible to use arrows from within PHPUnit? Outside it works well.
Readline is available and enabled.

**Comment by igorsantos07** [comment]
I just wanted to mention I still face this issue, @bobthecow . Composer doesn't provide a dime of documentation on how to make interactive scripts (composer/composer#4036), so upon some googling I found I should(?) add `< /dev/tty` - wondering if this is correct? Still so, I face the issue above: I can force colors, but the prompt is not there - even a custom one.

Any hints on those topics?

> Context: I was looking to run the container-wide `psysh` using a composer script to configure it, instead of adding psysh to the project dependencies (yep, this legacy project has committed dependencies), or another config file to the repo (that maybe only I will use haha).

**Comment by bobthecow** [comment]
I'm not sure how you get Composer to treat a script as interactive. You should ask them :)
