### ISSUE TITLE
history navigation

### ISSUE THREAD

**Issue by szepeviktor** [bobthecow/psysh#87]
Is it possible to navigate in history with `↑` and `↓` keys.
Now it prints `^[[A` and `^[[B`.

**Comment by ezmiller** [comment]
what about on a mac, where apt-get is not available?

**Comment by szepeviktor** [comment]
PHP readline must be available on all platforms.

**Comment by ezmiller** [comment]
@szepeviktor not sure how to interpret what you wrote: if it's not available in Brew, do you know where it would be available?

![](http://take.ms/41EO3)

**Comment by szepeviktor** [comment]
`brew install php56 --with-readline`

**Comment by ezmiller** [comment]
@szepeviktor thanks!
