### ISSUE TITLE
psysh has no logo

### ISSUE THREAD

**Issue by yuvii** [bobthecow/psysh#97]
psysh is amazing, it really helped me a lot. So anyway, I was trying to make psysh available from the unity launcher when I realized it had _no official logo_ (gasp!). 

So how about it? I even made a quick sketch of one idea I had (yeah yeah it looks terrible. I spent 5 minutes making it, it's just supposed to be a general idea for a design, not the end result):

![psysh-logo](https://cloud.githubusercontent.com/assets/5923462/4234369/4bb3e43c-39b6-11e4-9fb3-74f9dc83b8e3.png)

**Comment by bobthecow** [comment]
Thanks for suggestions on this. I think I'm okay with PsySH having no logo :)
